-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity getPeakBinOf5 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    et_0_read : IN STD_LOGIC_VECTOR (15 downto 0);
    et_1_read : IN STD_LOGIC_VECTOR (15 downto 0);
    et_2_read : IN STD_LOGIC_VECTOR (15 downto 0);
    et_3_read : IN STD_LOGIC_VECTOR (15 downto 0);
    et_4_read : IN STD_LOGIC_VECTOR (15 downto 0);
    etSum : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of getPeakBinOf5 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal etSum_read_reg_337 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal iEtSum_fu_220_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal iEtSum_reg_345 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal tmp_9_fu_86_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_s_fu_100_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_1_fu_114_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_3_fu_134_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_18_fu_148_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_19_fu_152_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp5_fu_156_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_4_fu_170_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_2_fu_96_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_128_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_16_fu_124_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_5_fu_110_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp2_fu_190_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp8_fu_184_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp9_fu_196_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_202_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_17_fu_144_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp1_fu_162_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_20_fu_180_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_fu_208_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp3_fu_214_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_10_fu_239_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_13_cast_fu_233_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_14_cast1_fu_236_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_15_cast_fu_246_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_13_cast1_fu_230_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_12_fu_256_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_14_fu_268_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_15_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp4_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal iAve_fu_281_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp2_fu_301_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp5_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_323_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_309_p3 : STD_LOGIC_VECTOR (2 downto 0);


begin



    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then
                etSum_read_reg_337 <= etSum;
                iEtSum_reg_345 <= iEtSum_fu_220_p2;
            end if;
        end if;
    end process;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return <= 
        ap_const_lv3_1 when (sel_tmp6_fu_323_p2(0) = '1') else 
        sel_tmp4_fu_309_p3;
    iAve_fu_281_p3 <= 
        ap_const_lv3_4 when (tmp_15_fu_275_p2(0) = '1') else 
        ap_const_lv3_3;
    iEtSum_fu_220_p2 <= std_logic_vector(unsigned(tmp_6_fu_208_p2) + unsigned(tmp3_fu_214_p2));
    sel_tmp1_fu_295_p2 <= (tmp_7_fu_226_p2 and tmp4_fu_289_p2);
    sel_tmp2_fu_301_p3 <= 
        iAve_fu_281_p3 when (sel_tmp1_fu_295_p2(0) = '1') else 
        ap_const_lv3_2;
    sel_tmp4_fu_309_p3 <= 
        sel_tmp2_fu_301_p3 when (tmp_7_fu_226_p2(0) = '1') else 
        ap_const_lv3_0;
    sel_tmp5_fu_317_p2 <= (tmp_11_fu_250_p2 xor ap_const_lv1_1);
    sel_tmp6_fu_323_p2 <= (tmp_7_fu_226_p2 and sel_tmp5_fu_317_p2);
    tmp1_fu_162_p3 <= (tmp5_fu_156_p2 & ap_const_lv2_0);
    tmp2_fu_190_p2 <= std_logic_vector(unsigned(tmp_fu_128_p2) + unsigned(tmp_16_fu_124_p1));
    tmp3_fu_214_p2 <= std_logic_vector(unsigned(tmp1_fu_162_p3) + unsigned(tmp_20_fu_180_p1));
    tmp4_fu_289_p2 <= (tmp_13_fu_262_p2 and tmp_11_fu_250_p2);
    tmp5_fu_156_p2 <= std_logic_vector(unsigned(tmp_18_fu_148_p1) + unsigned(tmp_19_fu_152_p1));
    tmp8_fu_184_p2 <= std_logic_vector(unsigned(tmp_2_fu_96_p1) + unsigned(et_1_read));
    tmp9_fu_196_p2 <= std_logic_vector(unsigned(tmp_5_fu_110_p1) + unsigned(tmp2_fu_190_p2));
    tmp_10_fu_239_p3 <= (etSum_read_reg_337 & ap_const_lv1_0);
    tmp_11_fu_250_p2 <= "1" when (unsigned(tmp_13_cast_fu_233_p1) > unsigned(tmp_10_fu_239_p3)) else "0";
    tmp_12_fu_256_p2 <= std_logic_vector(unsigned(tmp_14_cast1_fu_236_p1) + unsigned(tmp_15_cast_fu_246_p1));
    tmp_13_cast1_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(iEtSum_reg_345),18));
    tmp_13_cast_fu_233_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(iEtSum_reg_345),17));
    tmp_13_fu_262_p2 <= "1" when (unsigned(tmp_13_cast1_fu_230_p1) > unsigned(tmp_12_fu_256_p2)) else "0";
    tmp_14_cast1_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(etSum_read_reg_337),18));
    tmp_14_fu_268_p3 <= (etSum_read_reg_337 & ap_const_lv2_0);
    tmp_15_cast_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_10_fu_239_p3),18));
    tmp_15_fu_275_p2 <= "1" when (unsigned(tmp_13_cast1_fu_230_p1) > unsigned(tmp_14_fu_268_p3)) else "0";
    tmp_16_fu_124_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_1_fu_114_p4),16));
    tmp_17_fu_144_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_134_p4),16));
    tmp_18_fu_148_p1 <= et_4_read(14 - 1 downto 0);
    tmp_19_fu_152_p1 <= et_3_read(14 - 1 downto 0);
    tmp_1_fu_114_p4 <= et_2_read(15 downto 1);
    tmp_20_fu_180_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_170_p4),16));
    tmp_2_fu_96_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_86_p4),16));
    tmp_3_fu_134_p4 <= et_3_read(15 downto 1);
    tmp_4_fu_170_p4 <= et_4_read(15 downto 1);
    tmp_5_fu_110_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_100_p4),16));
    tmp_6_fu_208_p2 <= std_logic_vector(unsigned(tmp_8_fu_202_p2) - unsigned(tmp_17_fu_144_p1));
    tmp_7_fu_226_p2 <= "1" when (unsigned(iEtSum_reg_345) > unsigned(etSum_read_reg_337)) else "0";
    tmp_8_fu_202_p2 <= std_logic_vector(unsigned(tmp8_fu_184_p2) + unsigned(tmp9_fu_196_p2));
    tmp_9_fu_86_p4 <= et_0_read(15 downto 1);
    tmp_fu_128_p2 <= std_logic_vector(shift_left(unsigned(et_2_read),to_integer(unsigned('0' & ap_const_lv16_1(16-1 downto 0)))));
    tmp_s_fu_100_p4 <= et_1_read(15 downto 1);
end behav;
