// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module getClustersin3x4Regi (
        ap_clk,
        ap_rst,
        crystals_tower_0_0_0_0_read,
        crystals_tower_0_0_0_1_read,
        crystals_tower_0_0_0_2_read,
        crystals_tower_0_0_0_3_read,
        crystals_tower_0_0_0_4_read,
        crystals_tower_0_0_1_0_read,
        crystals_tower_0_0_1_1_read,
        crystals_tower_0_0_1_2_read,
        crystals_tower_0_0_1_3_read,
        crystals_tower_0_0_1_4_read,
        crystals_tower_0_0_2_0_read,
        crystals_tower_0_0_2_1_read,
        crystals_tower_0_0_2_2_read,
        crystals_tower_0_0_2_3_read,
        crystals_tower_0_0_2_4_read,
        crystals_tower_0_0_3_0_read,
        crystals_tower_0_0_3_1_read,
        crystals_tower_0_0_3_2_read,
        crystals_tower_0_0_3_3_read,
        crystals_tower_0_0_3_4_read,
        crystals_tower_0_0_4_0_read,
        crystals_tower_0_0_4_1_read,
        crystals_tower_0_0_4_2_read,
        crystals_tower_0_0_4_3_read,
        crystals_tower_0_0_4_4_read,
        crystals_tower_0_1_0_0_read,
        crystals_tower_0_1_0_1_read,
        crystals_tower_0_1_0_2_read,
        crystals_tower_0_1_0_3_read,
        crystals_tower_0_1_0_4_read,
        crystals_tower_0_1_1_0_read,
        crystals_tower_0_1_1_1_read,
        crystals_tower_0_1_1_2_read,
        crystals_tower_0_1_1_3_read,
        crystals_tower_0_1_1_4_read,
        crystals_tower_0_1_2_0_read,
        crystals_tower_0_1_2_1_read,
        crystals_tower_0_1_2_2_read,
        crystals_tower_0_1_2_3_read,
        crystals_tower_0_1_2_4_read,
        crystals_tower_0_1_3_0_read,
        crystals_tower_0_1_3_1_read,
        crystals_tower_0_1_3_2_read,
        crystals_tower_0_1_3_3_read,
        crystals_tower_0_1_3_4_read,
        crystals_tower_0_1_4_0_read,
        crystals_tower_0_1_4_1_read,
        crystals_tower_0_1_4_2_read,
        crystals_tower_0_1_4_3_read,
        crystals_tower_0_1_4_4_read,
        crystals_tower_0_2_0_0_read,
        crystals_tower_0_2_0_1_read,
        crystals_tower_0_2_0_2_read,
        crystals_tower_0_2_0_3_read,
        crystals_tower_0_2_0_4_read,
        crystals_tower_0_2_1_0_read,
        crystals_tower_0_2_1_1_read,
        crystals_tower_0_2_1_2_read,
        crystals_tower_0_2_1_3_read,
        crystals_tower_0_2_1_4_read,
        crystals_tower_0_2_2_0_read,
        crystals_tower_0_2_2_1_read,
        crystals_tower_0_2_2_2_read,
        crystals_tower_0_2_2_3_read,
        crystals_tower_0_2_2_4_read,
        crystals_tower_0_2_3_0_read,
        crystals_tower_0_2_3_1_read,
        crystals_tower_0_2_3_2_read,
        crystals_tower_0_2_3_3_read,
        crystals_tower_0_2_3_4_read,
        crystals_tower_0_2_4_0_read,
        crystals_tower_0_2_4_1_read,
        crystals_tower_0_2_4_2_read,
        crystals_tower_0_2_4_3_read,
        crystals_tower_0_2_4_4_read,
        crystals_tower_0_3_0_0_read,
        crystals_tower_0_3_0_1_read,
        crystals_tower_0_3_0_2_read,
        crystals_tower_0_3_0_3_read,
        crystals_tower_0_3_0_4_read,
        crystals_tower_0_3_1_0_read,
        crystals_tower_0_3_1_1_read,
        crystals_tower_0_3_1_2_read,
        crystals_tower_0_3_1_3_read,
        crystals_tower_0_3_1_4_read,
        crystals_tower_0_3_2_0_read,
        crystals_tower_0_3_2_1_read,
        crystals_tower_0_3_2_2_read,
        crystals_tower_0_3_2_3_read,
        crystals_tower_0_3_2_4_read,
        crystals_tower_0_3_3_0_read,
        crystals_tower_0_3_3_1_read,
        crystals_tower_0_3_3_2_read,
        crystals_tower_0_3_3_3_read,
        crystals_tower_0_3_3_4_read,
        crystals_tower_0_3_4_0_read,
        crystals_tower_0_3_4_1_read,
        crystals_tower_0_3_4_2_read,
        crystals_tower_0_3_4_3_read,
        crystals_tower_0_3_4_4_read,
        crystals_tower_1_0_0_0_read,
        crystals_tower_1_0_0_1_read,
        crystals_tower_1_0_0_2_read,
        crystals_tower_1_0_0_3_read,
        crystals_tower_1_0_0_4_read,
        crystals_tower_1_0_1_0_read,
        crystals_tower_1_0_1_1_read,
        crystals_tower_1_0_1_2_read,
        crystals_tower_1_0_1_3_read,
        crystals_tower_1_0_1_4_read,
        crystals_tower_1_0_2_0_read,
        crystals_tower_1_0_2_1_read,
        crystals_tower_1_0_2_2_read,
        crystals_tower_1_0_2_3_read,
        crystals_tower_1_0_2_4_read,
        crystals_tower_1_0_3_0_read,
        crystals_tower_1_0_3_1_read,
        crystals_tower_1_0_3_2_read,
        crystals_tower_1_0_3_3_read,
        crystals_tower_1_0_3_4_read,
        crystals_tower_1_0_4_0_read,
        crystals_tower_1_0_4_1_read,
        crystals_tower_1_0_4_2_read,
        crystals_tower_1_0_4_3_read,
        crystals_tower_1_0_4_4_read,
        crystals_tower_1_1_0_0_read,
        crystals_tower_1_1_0_1_read,
        crystals_tower_1_1_0_2_read,
        crystals_tower_1_1_0_3_read,
        crystals_tower_1_1_0_4_read,
        crystals_tower_1_1_1_0_read,
        crystals_tower_1_1_1_1_read,
        crystals_tower_1_1_1_2_read,
        crystals_tower_1_1_1_3_read,
        crystals_tower_1_1_1_4_read,
        crystals_tower_1_1_2_0_read,
        crystals_tower_1_1_2_1_read,
        crystals_tower_1_1_2_2_read,
        crystals_tower_1_1_2_3_read,
        crystals_tower_1_1_2_4_read,
        crystals_tower_1_1_3_0_read,
        crystals_tower_1_1_3_1_read,
        crystals_tower_1_1_3_2_read,
        crystals_tower_1_1_3_3_read,
        crystals_tower_1_1_3_4_read,
        crystals_tower_1_1_4_0_read,
        crystals_tower_1_1_4_1_read,
        crystals_tower_1_1_4_2_read,
        crystals_tower_1_1_4_3_read,
        crystals_tower_1_1_4_4_read,
        crystals_tower_1_2_0_0_read,
        crystals_tower_1_2_0_1_read,
        crystals_tower_1_2_0_2_read,
        crystals_tower_1_2_0_3_read,
        crystals_tower_1_2_0_4_read,
        crystals_tower_1_2_1_0_read,
        crystals_tower_1_2_1_1_read,
        crystals_tower_1_2_1_2_read,
        crystals_tower_1_2_1_3_read,
        crystals_tower_1_2_1_4_read,
        crystals_tower_1_2_2_0_read,
        crystals_tower_1_2_2_1_read,
        crystals_tower_1_2_2_2_read,
        crystals_tower_1_2_2_3_read,
        crystals_tower_1_2_2_4_read,
        crystals_tower_1_2_3_0_read,
        crystals_tower_1_2_3_1_read,
        crystals_tower_1_2_3_2_read,
        crystals_tower_1_2_3_3_read,
        crystals_tower_1_2_3_4_read,
        crystals_tower_1_2_4_0_read,
        crystals_tower_1_2_4_1_read,
        crystals_tower_1_2_4_2_read,
        crystals_tower_1_2_4_3_read,
        crystals_tower_1_2_4_4_read,
        crystals_tower_1_3_0_0_read,
        crystals_tower_1_3_0_1_read,
        crystals_tower_1_3_0_2_read,
        crystals_tower_1_3_0_3_read,
        crystals_tower_1_3_0_4_read,
        crystals_tower_1_3_1_0_read,
        crystals_tower_1_3_1_1_read,
        crystals_tower_1_3_1_2_read,
        crystals_tower_1_3_1_3_read,
        crystals_tower_1_3_1_4_read,
        crystals_tower_1_3_2_0_read,
        crystals_tower_1_3_2_1_read,
        crystals_tower_1_3_2_2_read,
        crystals_tower_1_3_2_3_read,
        crystals_tower_1_3_2_4_read,
        crystals_tower_1_3_3_0_read,
        crystals_tower_1_3_3_1_read,
        crystals_tower_1_3_3_2_read,
        crystals_tower_1_3_3_3_read,
        crystals_tower_1_3_3_4_read,
        crystals_tower_1_3_4_0_read,
        crystals_tower_1_3_4_1_read,
        crystals_tower_1_3_4_2_read,
        crystals_tower_1_3_4_3_read,
        crystals_tower_1_3_4_4_read,
        crystals_tower_2_0_0_0_read,
        crystals_tower_2_0_0_1_read,
        crystals_tower_2_0_0_2_read,
        crystals_tower_2_0_0_3_read,
        crystals_tower_2_0_0_4_read,
        crystals_tower_2_0_1_0_read,
        crystals_tower_2_0_1_1_read,
        crystals_tower_2_0_1_2_read,
        crystals_tower_2_0_1_3_read,
        crystals_tower_2_0_1_4_read,
        crystals_tower_2_0_2_0_read,
        crystals_tower_2_0_2_1_read,
        crystals_tower_2_0_2_2_read,
        crystals_tower_2_0_2_3_read,
        crystals_tower_2_0_2_4_read,
        crystals_tower_2_0_3_0_read,
        crystals_tower_2_0_3_1_read,
        crystals_tower_2_0_3_2_read,
        crystals_tower_2_0_3_3_read,
        crystals_tower_2_0_3_4_read,
        crystals_tower_2_0_4_0_read,
        crystals_tower_2_0_4_1_read,
        crystals_tower_2_0_4_2_read,
        crystals_tower_2_0_4_3_read,
        crystals_tower_2_0_4_4_read,
        crystals_tower_2_1_0_0_read,
        crystals_tower_2_1_0_1_read,
        crystals_tower_2_1_0_2_read,
        crystals_tower_2_1_0_3_read,
        crystals_tower_2_1_0_4_read,
        crystals_tower_2_1_1_0_read,
        crystals_tower_2_1_1_1_read,
        crystals_tower_2_1_1_2_read,
        crystals_tower_2_1_1_3_read,
        crystals_tower_2_1_1_4_read,
        crystals_tower_2_1_2_0_read,
        crystals_tower_2_1_2_1_read,
        crystals_tower_2_1_2_2_read,
        crystals_tower_2_1_2_3_read,
        crystals_tower_2_1_2_4_read,
        crystals_tower_2_1_3_0_read,
        crystals_tower_2_1_3_1_read,
        crystals_tower_2_1_3_2_read,
        crystals_tower_2_1_3_3_read,
        crystals_tower_2_1_3_4_read,
        crystals_tower_2_1_4_0_read,
        crystals_tower_2_1_4_1_read,
        crystals_tower_2_1_4_2_read,
        crystals_tower_2_1_4_3_read,
        crystals_tower_2_1_4_4_read,
        crystals_tower_2_2_0_0_read,
        crystals_tower_2_2_0_1_read,
        crystals_tower_2_2_0_2_read,
        crystals_tower_2_2_0_3_read,
        crystals_tower_2_2_0_4_read,
        crystals_tower_2_2_1_0_read,
        crystals_tower_2_2_1_1_read,
        crystals_tower_2_2_1_2_read,
        crystals_tower_2_2_1_3_read,
        crystals_tower_2_2_1_4_read,
        crystals_tower_2_2_2_0_read,
        crystals_tower_2_2_2_1_read,
        crystals_tower_2_2_2_2_read,
        crystals_tower_2_2_2_3_read,
        crystals_tower_2_2_2_4_read,
        crystals_tower_2_2_3_0_read,
        crystals_tower_2_2_3_1_read,
        crystals_tower_2_2_3_2_read,
        crystals_tower_2_2_3_3_read,
        crystals_tower_2_2_3_4_read,
        crystals_tower_2_2_4_0_read,
        crystals_tower_2_2_4_1_read,
        crystals_tower_2_2_4_2_read,
        crystals_tower_2_2_4_3_read,
        crystals_tower_2_2_4_4_read,
        crystals_tower_2_3_0_0_read,
        crystals_tower_2_3_0_1_read,
        crystals_tower_2_3_0_2_read,
        crystals_tower_2_3_0_3_read,
        crystals_tower_2_3_0_4_read,
        crystals_tower_2_3_1_0_read,
        crystals_tower_2_3_1_1_read,
        crystals_tower_2_3_1_2_read,
        crystals_tower_2_3_1_3_read,
        crystals_tower_2_3_1_4_read,
        crystals_tower_2_3_2_0_read,
        crystals_tower_2_3_2_1_read,
        crystals_tower_2_3_2_2_read,
        crystals_tower_2_3_2_3_read,
        crystals_tower_2_3_2_4_read,
        crystals_tower_2_3_3_0_read,
        crystals_tower_2_3_3_1_read,
        crystals_tower_2_3_3_2_read,
        crystals_tower_2_3_3_3_read,
        crystals_tower_2_3_3_4_read,
        crystals_tower_2_3_4_0_read,
        crystals_tower_2_3_4_1_read,
        crystals_tower_2_3_4_2_read,
        crystals_tower_2_3_4_3_read,
        crystals_tower_2_3_4_4_read,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] crystals_tower_0_0_0_0_read;
input  [15:0] crystals_tower_0_0_0_1_read;
input  [15:0] crystals_tower_0_0_0_2_read;
input  [15:0] crystals_tower_0_0_0_3_read;
input  [15:0] crystals_tower_0_0_0_4_read;
input  [15:0] crystals_tower_0_0_1_0_read;
input  [15:0] crystals_tower_0_0_1_1_read;
input  [15:0] crystals_tower_0_0_1_2_read;
input  [15:0] crystals_tower_0_0_1_3_read;
input  [15:0] crystals_tower_0_0_1_4_read;
input  [15:0] crystals_tower_0_0_2_0_read;
input  [15:0] crystals_tower_0_0_2_1_read;
input  [15:0] crystals_tower_0_0_2_2_read;
input  [15:0] crystals_tower_0_0_2_3_read;
input  [15:0] crystals_tower_0_0_2_4_read;
input  [15:0] crystals_tower_0_0_3_0_read;
input  [15:0] crystals_tower_0_0_3_1_read;
input  [15:0] crystals_tower_0_0_3_2_read;
input  [15:0] crystals_tower_0_0_3_3_read;
input  [15:0] crystals_tower_0_0_3_4_read;
input  [15:0] crystals_tower_0_0_4_0_read;
input  [15:0] crystals_tower_0_0_4_1_read;
input  [15:0] crystals_tower_0_0_4_2_read;
input  [15:0] crystals_tower_0_0_4_3_read;
input  [15:0] crystals_tower_0_0_4_4_read;
input  [15:0] crystals_tower_0_1_0_0_read;
input  [15:0] crystals_tower_0_1_0_1_read;
input  [15:0] crystals_tower_0_1_0_2_read;
input  [15:0] crystals_tower_0_1_0_3_read;
input  [15:0] crystals_tower_0_1_0_4_read;
input  [15:0] crystals_tower_0_1_1_0_read;
input  [15:0] crystals_tower_0_1_1_1_read;
input  [15:0] crystals_tower_0_1_1_2_read;
input  [15:0] crystals_tower_0_1_1_3_read;
input  [15:0] crystals_tower_0_1_1_4_read;
input  [15:0] crystals_tower_0_1_2_0_read;
input  [15:0] crystals_tower_0_1_2_1_read;
input  [15:0] crystals_tower_0_1_2_2_read;
input  [15:0] crystals_tower_0_1_2_3_read;
input  [15:0] crystals_tower_0_1_2_4_read;
input  [15:0] crystals_tower_0_1_3_0_read;
input  [15:0] crystals_tower_0_1_3_1_read;
input  [15:0] crystals_tower_0_1_3_2_read;
input  [15:0] crystals_tower_0_1_3_3_read;
input  [15:0] crystals_tower_0_1_3_4_read;
input  [15:0] crystals_tower_0_1_4_0_read;
input  [15:0] crystals_tower_0_1_4_1_read;
input  [15:0] crystals_tower_0_1_4_2_read;
input  [15:0] crystals_tower_0_1_4_3_read;
input  [15:0] crystals_tower_0_1_4_4_read;
input  [15:0] crystals_tower_0_2_0_0_read;
input  [15:0] crystals_tower_0_2_0_1_read;
input  [15:0] crystals_tower_0_2_0_2_read;
input  [15:0] crystals_tower_0_2_0_3_read;
input  [15:0] crystals_tower_0_2_0_4_read;
input  [15:0] crystals_tower_0_2_1_0_read;
input  [15:0] crystals_tower_0_2_1_1_read;
input  [15:0] crystals_tower_0_2_1_2_read;
input  [15:0] crystals_tower_0_2_1_3_read;
input  [15:0] crystals_tower_0_2_1_4_read;
input  [15:0] crystals_tower_0_2_2_0_read;
input  [15:0] crystals_tower_0_2_2_1_read;
input  [15:0] crystals_tower_0_2_2_2_read;
input  [15:0] crystals_tower_0_2_2_3_read;
input  [15:0] crystals_tower_0_2_2_4_read;
input  [15:0] crystals_tower_0_2_3_0_read;
input  [15:0] crystals_tower_0_2_3_1_read;
input  [15:0] crystals_tower_0_2_3_2_read;
input  [15:0] crystals_tower_0_2_3_3_read;
input  [15:0] crystals_tower_0_2_3_4_read;
input  [15:0] crystals_tower_0_2_4_0_read;
input  [15:0] crystals_tower_0_2_4_1_read;
input  [15:0] crystals_tower_0_2_4_2_read;
input  [15:0] crystals_tower_0_2_4_3_read;
input  [15:0] crystals_tower_0_2_4_4_read;
input  [15:0] crystals_tower_0_3_0_0_read;
input  [15:0] crystals_tower_0_3_0_1_read;
input  [15:0] crystals_tower_0_3_0_2_read;
input  [15:0] crystals_tower_0_3_0_3_read;
input  [15:0] crystals_tower_0_3_0_4_read;
input  [15:0] crystals_tower_0_3_1_0_read;
input  [15:0] crystals_tower_0_3_1_1_read;
input  [15:0] crystals_tower_0_3_1_2_read;
input  [15:0] crystals_tower_0_3_1_3_read;
input  [15:0] crystals_tower_0_3_1_4_read;
input  [15:0] crystals_tower_0_3_2_0_read;
input  [15:0] crystals_tower_0_3_2_1_read;
input  [15:0] crystals_tower_0_3_2_2_read;
input  [15:0] crystals_tower_0_3_2_3_read;
input  [15:0] crystals_tower_0_3_2_4_read;
input  [15:0] crystals_tower_0_3_3_0_read;
input  [15:0] crystals_tower_0_3_3_1_read;
input  [15:0] crystals_tower_0_3_3_2_read;
input  [15:0] crystals_tower_0_3_3_3_read;
input  [15:0] crystals_tower_0_3_3_4_read;
input  [15:0] crystals_tower_0_3_4_0_read;
input  [15:0] crystals_tower_0_3_4_1_read;
input  [15:0] crystals_tower_0_3_4_2_read;
input  [15:0] crystals_tower_0_3_4_3_read;
input  [15:0] crystals_tower_0_3_4_4_read;
input  [15:0] crystals_tower_1_0_0_0_read;
input  [15:0] crystals_tower_1_0_0_1_read;
input  [15:0] crystals_tower_1_0_0_2_read;
input  [15:0] crystals_tower_1_0_0_3_read;
input  [15:0] crystals_tower_1_0_0_4_read;
input  [15:0] crystals_tower_1_0_1_0_read;
input  [15:0] crystals_tower_1_0_1_1_read;
input  [15:0] crystals_tower_1_0_1_2_read;
input  [15:0] crystals_tower_1_0_1_3_read;
input  [15:0] crystals_tower_1_0_1_4_read;
input  [15:0] crystals_tower_1_0_2_0_read;
input  [15:0] crystals_tower_1_0_2_1_read;
input  [15:0] crystals_tower_1_0_2_2_read;
input  [15:0] crystals_tower_1_0_2_3_read;
input  [15:0] crystals_tower_1_0_2_4_read;
input  [15:0] crystals_tower_1_0_3_0_read;
input  [15:0] crystals_tower_1_0_3_1_read;
input  [15:0] crystals_tower_1_0_3_2_read;
input  [15:0] crystals_tower_1_0_3_3_read;
input  [15:0] crystals_tower_1_0_3_4_read;
input  [15:0] crystals_tower_1_0_4_0_read;
input  [15:0] crystals_tower_1_0_4_1_read;
input  [15:0] crystals_tower_1_0_4_2_read;
input  [15:0] crystals_tower_1_0_4_3_read;
input  [15:0] crystals_tower_1_0_4_4_read;
input  [15:0] crystals_tower_1_1_0_0_read;
input  [15:0] crystals_tower_1_1_0_1_read;
input  [15:0] crystals_tower_1_1_0_2_read;
input  [15:0] crystals_tower_1_1_0_3_read;
input  [15:0] crystals_tower_1_1_0_4_read;
input  [15:0] crystals_tower_1_1_1_0_read;
input  [15:0] crystals_tower_1_1_1_1_read;
input  [15:0] crystals_tower_1_1_1_2_read;
input  [15:0] crystals_tower_1_1_1_3_read;
input  [15:0] crystals_tower_1_1_1_4_read;
input  [15:0] crystals_tower_1_1_2_0_read;
input  [15:0] crystals_tower_1_1_2_1_read;
input  [15:0] crystals_tower_1_1_2_2_read;
input  [15:0] crystals_tower_1_1_2_3_read;
input  [15:0] crystals_tower_1_1_2_4_read;
input  [15:0] crystals_tower_1_1_3_0_read;
input  [15:0] crystals_tower_1_1_3_1_read;
input  [15:0] crystals_tower_1_1_3_2_read;
input  [15:0] crystals_tower_1_1_3_3_read;
input  [15:0] crystals_tower_1_1_3_4_read;
input  [15:0] crystals_tower_1_1_4_0_read;
input  [15:0] crystals_tower_1_1_4_1_read;
input  [15:0] crystals_tower_1_1_4_2_read;
input  [15:0] crystals_tower_1_1_4_3_read;
input  [15:0] crystals_tower_1_1_4_4_read;
input  [15:0] crystals_tower_1_2_0_0_read;
input  [15:0] crystals_tower_1_2_0_1_read;
input  [15:0] crystals_tower_1_2_0_2_read;
input  [15:0] crystals_tower_1_2_0_3_read;
input  [15:0] crystals_tower_1_2_0_4_read;
input  [15:0] crystals_tower_1_2_1_0_read;
input  [15:0] crystals_tower_1_2_1_1_read;
input  [15:0] crystals_tower_1_2_1_2_read;
input  [15:0] crystals_tower_1_2_1_3_read;
input  [15:0] crystals_tower_1_2_1_4_read;
input  [15:0] crystals_tower_1_2_2_0_read;
input  [15:0] crystals_tower_1_2_2_1_read;
input  [15:0] crystals_tower_1_2_2_2_read;
input  [15:0] crystals_tower_1_2_2_3_read;
input  [15:0] crystals_tower_1_2_2_4_read;
input  [15:0] crystals_tower_1_2_3_0_read;
input  [15:0] crystals_tower_1_2_3_1_read;
input  [15:0] crystals_tower_1_2_3_2_read;
input  [15:0] crystals_tower_1_2_3_3_read;
input  [15:0] crystals_tower_1_2_3_4_read;
input  [15:0] crystals_tower_1_2_4_0_read;
input  [15:0] crystals_tower_1_2_4_1_read;
input  [15:0] crystals_tower_1_2_4_2_read;
input  [15:0] crystals_tower_1_2_4_3_read;
input  [15:0] crystals_tower_1_2_4_4_read;
input  [15:0] crystals_tower_1_3_0_0_read;
input  [15:0] crystals_tower_1_3_0_1_read;
input  [15:0] crystals_tower_1_3_0_2_read;
input  [15:0] crystals_tower_1_3_0_3_read;
input  [15:0] crystals_tower_1_3_0_4_read;
input  [15:0] crystals_tower_1_3_1_0_read;
input  [15:0] crystals_tower_1_3_1_1_read;
input  [15:0] crystals_tower_1_3_1_2_read;
input  [15:0] crystals_tower_1_3_1_3_read;
input  [15:0] crystals_tower_1_3_1_4_read;
input  [15:0] crystals_tower_1_3_2_0_read;
input  [15:0] crystals_tower_1_3_2_1_read;
input  [15:0] crystals_tower_1_3_2_2_read;
input  [15:0] crystals_tower_1_3_2_3_read;
input  [15:0] crystals_tower_1_3_2_4_read;
input  [15:0] crystals_tower_1_3_3_0_read;
input  [15:0] crystals_tower_1_3_3_1_read;
input  [15:0] crystals_tower_1_3_3_2_read;
input  [15:0] crystals_tower_1_3_3_3_read;
input  [15:0] crystals_tower_1_3_3_4_read;
input  [15:0] crystals_tower_1_3_4_0_read;
input  [15:0] crystals_tower_1_3_4_1_read;
input  [15:0] crystals_tower_1_3_4_2_read;
input  [15:0] crystals_tower_1_3_4_3_read;
input  [15:0] crystals_tower_1_3_4_4_read;
input  [15:0] crystals_tower_2_0_0_0_read;
input  [15:0] crystals_tower_2_0_0_1_read;
input  [15:0] crystals_tower_2_0_0_2_read;
input  [15:0] crystals_tower_2_0_0_3_read;
input  [15:0] crystals_tower_2_0_0_4_read;
input  [15:0] crystals_tower_2_0_1_0_read;
input  [15:0] crystals_tower_2_0_1_1_read;
input  [15:0] crystals_tower_2_0_1_2_read;
input  [15:0] crystals_tower_2_0_1_3_read;
input  [15:0] crystals_tower_2_0_1_4_read;
input  [15:0] crystals_tower_2_0_2_0_read;
input  [15:0] crystals_tower_2_0_2_1_read;
input  [15:0] crystals_tower_2_0_2_2_read;
input  [15:0] crystals_tower_2_0_2_3_read;
input  [15:0] crystals_tower_2_0_2_4_read;
input  [15:0] crystals_tower_2_0_3_0_read;
input  [15:0] crystals_tower_2_0_3_1_read;
input  [15:0] crystals_tower_2_0_3_2_read;
input  [15:0] crystals_tower_2_0_3_3_read;
input  [15:0] crystals_tower_2_0_3_4_read;
input  [15:0] crystals_tower_2_0_4_0_read;
input  [15:0] crystals_tower_2_0_4_1_read;
input  [15:0] crystals_tower_2_0_4_2_read;
input  [15:0] crystals_tower_2_0_4_3_read;
input  [15:0] crystals_tower_2_0_4_4_read;
input  [15:0] crystals_tower_2_1_0_0_read;
input  [15:0] crystals_tower_2_1_0_1_read;
input  [15:0] crystals_tower_2_1_0_2_read;
input  [15:0] crystals_tower_2_1_0_3_read;
input  [15:0] crystals_tower_2_1_0_4_read;
input  [15:0] crystals_tower_2_1_1_0_read;
input  [15:0] crystals_tower_2_1_1_1_read;
input  [15:0] crystals_tower_2_1_1_2_read;
input  [15:0] crystals_tower_2_1_1_3_read;
input  [15:0] crystals_tower_2_1_1_4_read;
input  [15:0] crystals_tower_2_1_2_0_read;
input  [15:0] crystals_tower_2_1_2_1_read;
input  [15:0] crystals_tower_2_1_2_2_read;
input  [15:0] crystals_tower_2_1_2_3_read;
input  [15:0] crystals_tower_2_1_2_4_read;
input  [15:0] crystals_tower_2_1_3_0_read;
input  [15:0] crystals_tower_2_1_3_1_read;
input  [15:0] crystals_tower_2_1_3_2_read;
input  [15:0] crystals_tower_2_1_3_3_read;
input  [15:0] crystals_tower_2_1_3_4_read;
input  [15:0] crystals_tower_2_1_4_0_read;
input  [15:0] crystals_tower_2_1_4_1_read;
input  [15:0] crystals_tower_2_1_4_2_read;
input  [15:0] crystals_tower_2_1_4_3_read;
input  [15:0] crystals_tower_2_1_4_4_read;
input  [15:0] crystals_tower_2_2_0_0_read;
input  [15:0] crystals_tower_2_2_0_1_read;
input  [15:0] crystals_tower_2_2_0_2_read;
input  [15:0] crystals_tower_2_2_0_3_read;
input  [15:0] crystals_tower_2_2_0_4_read;
input  [15:0] crystals_tower_2_2_1_0_read;
input  [15:0] crystals_tower_2_2_1_1_read;
input  [15:0] crystals_tower_2_2_1_2_read;
input  [15:0] crystals_tower_2_2_1_3_read;
input  [15:0] crystals_tower_2_2_1_4_read;
input  [15:0] crystals_tower_2_2_2_0_read;
input  [15:0] crystals_tower_2_2_2_1_read;
input  [15:0] crystals_tower_2_2_2_2_read;
input  [15:0] crystals_tower_2_2_2_3_read;
input  [15:0] crystals_tower_2_2_2_4_read;
input  [15:0] crystals_tower_2_2_3_0_read;
input  [15:0] crystals_tower_2_2_3_1_read;
input  [15:0] crystals_tower_2_2_3_2_read;
input  [15:0] crystals_tower_2_2_3_3_read;
input  [15:0] crystals_tower_2_2_3_4_read;
input  [15:0] crystals_tower_2_2_4_0_read;
input  [15:0] crystals_tower_2_2_4_1_read;
input  [15:0] crystals_tower_2_2_4_2_read;
input  [15:0] crystals_tower_2_2_4_3_read;
input  [15:0] crystals_tower_2_2_4_4_read;
input  [15:0] crystals_tower_2_3_0_0_read;
input  [15:0] crystals_tower_2_3_0_1_read;
input  [15:0] crystals_tower_2_3_0_2_read;
input  [15:0] crystals_tower_2_3_0_3_read;
input  [15:0] crystals_tower_2_3_0_4_read;
input  [15:0] crystals_tower_2_3_1_0_read;
input  [15:0] crystals_tower_2_3_1_1_read;
input  [15:0] crystals_tower_2_3_1_2_read;
input  [15:0] crystals_tower_2_3_1_3_read;
input  [15:0] crystals_tower_2_3_1_4_read;
input  [15:0] crystals_tower_2_3_2_0_read;
input  [15:0] crystals_tower_2_3_2_1_read;
input  [15:0] crystals_tower_2_3_2_2_read;
input  [15:0] crystals_tower_2_3_2_3_read;
input  [15:0] crystals_tower_2_3_2_4_read;
input  [15:0] crystals_tower_2_3_3_0_read;
input  [15:0] crystals_tower_2_3_3_1_read;
input  [15:0] crystals_tower_2_3_3_2_read;
input  [15:0] crystals_tower_2_3_3_3_read;
input  [15:0] crystals_tower_2_3_3_4_read;
input  [15:0] crystals_tower_2_3_4_0_read;
input  [15:0] crystals_tower_2_3_4_1_read;
input  [15:0] crystals_tower_2_3_4_2_read;
input  [15:0] crystals_tower_2_3_4_3_read;
input  [15:0] crystals_tower_2_3_4_4_read;
input   ap_ce;

wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
reg    grp_getClustersInTower_fu_2412_ap_ce;
reg    grp_getClustersInTower_fu_2466_ap_ce;
reg    grp_getClustersInTower_fu_2520_ap_ce;
reg    grp_getClustersInTower_fu_2574_ap_ce;
reg    grp_getClustersInTower_fu_2628_ap_ce;
reg    grp_getClustersInTower_fu_2682_ap_ce;
reg    grp_getClustersInTower_fu_2736_ap_ce;
reg    grp_getClustersInTower_fu_2790_ap_ce;
reg    grp_getClustersInTower_fu_2844_ap_ce;
reg    grp_getClustersInTower_fu_2898_ap_ce;
reg    grp_getClustersInTower_fu_2952_ap_ce;
reg    grp_getClustersInTower_fu_3006_ap_ce;
wire    ap_block_pp0_stage0;
reg   [15:0] crystals_tower_0_0_0_0_read_int_reg;
reg   [15:0] crystals_tower_0_0_0_1_read_int_reg;
reg   [15:0] crystals_tower_0_0_0_2_read_int_reg;
reg   [15:0] crystals_tower_0_0_0_3_read_int_reg;
reg   [15:0] crystals_tower_0_0_0_4_read_int_reg;
reg   [15:0] crystals_tower_0_0_1_0_read_int_reg;
reg   [15:0] crystals_tower_0_0_1_1_read_int_reg;
reg   [15:0] crystals_tower_0_0_1_2_read_int_reg;
reg   [15:0] crystals_tower_0_0_1_3_read_int_reg;
reg   [15:0] crystals_tower_0_0_1_4_read_int_reg;
reg   [15:0] crystals_tower_0_0_2_0_read_int_reg;
reg   [15:0] crystals_tower_0_0_2_1_read_int_reg;
reg   [15:0] crystals_tower_0_0_2_2_read_int_reg;
reg   [15:0] crystals_tower_0_0_2_3_read_int_reg;
reg   [15:0] crystals_tower_0_0_2_4_read_int_reg;
reg   [15:0] crystals_tower_0_0_3_0_read_int_reg;
reg   [15:0] crystals_tower_0_0_3_1_read_int_reg;
reg   [15:0] crystals_tower_0_0_3_2_read_int_reg;
reg   [15:0] crystals_tower_0_0_3_3_read_int_reg;
reg   [15:0] crystals_tower_0_0_3_4_read_int_reg;
reg   [15:0] crystals_tower_0_0_4_0_read_int_reg;
reg   [15:0] crystals_tower_0_0_4_1_read_int_reg;
reg   [15:0] crystals_tower_0_0_4_2_read_int_reg;
reg   [15:0] crystals_tower_0_0_4_3_read_int_reg;
reg   [15:0] crystals_tower_0_0_4_4_read_int_reg;
reg   [15:0] crystals_tower_0_1_0_0_read_int_reg;
reg   [15:0] crystals_tower_0_1_0_1_read_int_reg;
reg   [15:0] crystals_tower_0_1_0_2_read_int_reg;
reg   [15:0] crystals_tower_0_1_0_3_read_int_reg;
reg   [15:0] crystals_tower_0_1_0_4_read_int_reg;
reg   [15:0] crystals_tower_0_1_1_0_read_int_reg;
reg   [15:0] crystals_tower_0_1_1_1_read_int_reg;
reg   [15:0] crystals_tower_0_1_1_2_read_int_reg;
reg   [15:0] crystals_tower_0_1_1_3_read_int_reg;
reg   [15:0] crystals_tower_0_1_1_4_read_int_reg;
reg   [15:0] crystals_tower_0_1_2_0_read_int_reg;
reg   [15:0] crystals_tower_0_1_2_1_read_int_reg;
reg   [15:0] crystals_tower_0_1_2_2_read_int_reg;
reg   [15:0] crystals_tower_0_1_2_3_read_int_reg;
reg   [15:0] crystals_tower_0_1_2_4_read_int_reg;
reg   [15:0] crystals_tower_0_1_3_0_read_int_reg;
reg   [15:0] crystals_tower_0_1_3_1_read_int_reg;
reg   [15:0] crystals_tower_0_1_3_2_read_int_reg;
reg   [15:0] crystals_tower_0_1_3_3_read_int_reg;
reg   [15:0] crystals_tower_0_1_3_4_read_int_reg;
reg   [15:0] crystals_tower_0_1_4_0_read_int_reg;
reg   [15:0] crystals_tower_0_1_4_1_read_int_reg;
reg   [15:0] crystals_tower_0_1_4_2_read_int_reg;
reg   [15:0] crystals_tower_0_1_4_3_read_int_reg;
reg   [15:0] crystals_tower_0_1_4_4_read_int_reg;
reg   [15:0] crystals_tower_0_2_0_0_read_int_reg;
reg   [15:0] crystals_tower_0_2_0_1_read_int_reg;
reg   [15:0] crystals_tower_0_2_0_2_read_int_reg;
reg   [15:0] crystals_tower_0_2_0_3_read_int_reg;
reg   [15:0] crystals_tower_0_2_0_4_read_int_reg;
reg   [15:0] crystals_tower_0_2_1_0_read_int_reg;
reg   [15:0] crystals_tower_0_2_1_1_read_int_reg;
reg   [15:0] crystals_tower_0_2_1_2_read_int_reg;
reg   [15:0] crystals_tower_0_2_1_3_read_int_reg;
reg   [15:0] crystals_tower_0_2_1_4_read_int_reg;
reg   [15:0] crystals_tower_0_2_2_0_read_int_reg;
reg   [15:0] crystals_tower_0_2_2_1_read_int_reg;
reg   [15:0] crystals_tower_0_2_2_2_read_int_reg;
reg   [15:0] crystals_tower_0_2_2_3_read_int_reg;
reg   [15:0] crystals_tower_0_2_2_4_read_int_reg;
reg   [15:0] crystals_tower_0_2_3_0_read_int_reg;
reg   [15:0] crystals_tower_0_2_3_1_read_int_reg;
reg   [15:0] crystals_tower_0_2_3_2_read_int_reg;
reg   [15:0] crystals_tower_0_2_3_3_read_int_reg;
reg   [15:0] crystals_tower_0_2_3_4_read_int_reg;
reg   [15:0] crystals_tower_0_2_4_0_read_int_reg;
reg   [15:0] crystals_tower_0_2_4_1_read_int_reg;
reg   [15:0] crystals_tower_0_2_4_2_read_int_reg;
reg   [15:0] crystals_tower_0_2_4_3_read_int_reg;
reg   [15:0] crystals_tower_0_2_4_4_read_int_reg;
reg   [15:0] crystals_tower_0_3_0_0_read_int_reg;
reg   [15:0] crystals_tower_0_3_0_1_read_int_reg;
reg   [15:0] crystals_tower_0_3_0_2_read_int_reg;
reg   [15:0] crystals_tower_0_3_0_3_read_int_reg;
reg   [15:0] crystals_tower_0_3_0_4_read_int_reg;
reg   [15:0] crystals_tower_0_3_1_0_read_int_reg;
reg   [15:0] crystals_tower_0_3_1_1_read_int_reg;
reg   [15:0] crystals_tower_0_3_1_2_read_int_reg;
reg   [15:0] crystals_tower_0_3_1_3_read_int_reg;
reg   [15:0] crystals_tower_0_3_1_4_read_int_reg;
reg   [15:0] crystals_tower_0_3_2_0_read_int_reg;
reg   [15:0] crystals_tower_0_3_2_1_read_int_reg;
reg   [15:0] crystals_tower_0_3_2_2_read_int_reg;
reg   [15:0] crystals_tower_0_3_2_3_read_int_reg;
reg   [15:0] crystals_tower_0_3_2_4_read_int_reg;
reg   [15:0] crystals_tower_0_3_3_0_read_int_reg;
reg   [15:0] crystals_tower_0_3_3_1_read_int_reg;
reg   [15:0] crystals_tower_0_3_3_2_read_int_reg;
reg   [15:0] crystals_tower_0_3_3_3_read_int_reg;
reg   [15:0] crystals_tower_0_3_3_4_read_int_reg;
reg   [15:0] crystals_tower_0_3_4_0_read_int_reg;
reg   [15:0] crystals_tower_0_3_4_1_read_int_reg;
reg   [15:0] crystals_tower_0_3_4_2_read_int_reg;
reg   [15:0] crystals_tower_0_3_4_3_read_int_reg;
reg   [15:0] crystals_tower_0_3_4_4_read_int_reg;
reg   [15:0] crystals_tower_1_0_0_0_read_int_reg;
reg   [15:0] crystals_tower_1_0_0_1_read_int_reg;
reg   [15:0] crystals_tower_1_0_0_2_read_int_reg;
reg   [15:0] crystals_tower_1_0_0_3_read_int_reg;
reg   [15:0] crystals_tower_1_0_0_4_read_int_reg;
reg   [15:0] crystals_tower_1_0_1_0_read_int_reg;
reg   [15:0] crystals_tower_1_0_1_1_read_int_reg;
reg   [15:0] crystals_tower_1_0_1_2_read_int_reg;
reg   [15:0] crystals_tower_1_0_1_3_read_int_reg;
reg   [15:0] crystals_tower_1_0_1_4_read_int_reg;
reg   [15:0] crystals_tower_1_0_2_0_read_int_reg;
reg   [15:0] crystals_tower_1_0_2_1_read_int_reg;
reg   [15:0] crystals_tower_1_0_2_2_read_int_reg;
reg   [15:0] crystals_tower_1_0_2_3_read_int_reg;
reg   [15:0] crystals_tower_1_0_2_4_read_int_reg;
reg   [15:0] crystals_tower_1_0_3_0_read_int_reg;
reg   [15:0] crystals_tower_1_0_3_1_read_int_reg;
reg   [15:0] crystals_tower_1_0_3_2_read_int_reg;
reg   [15:0] crystals_tower_1_0_3_3_read_int_reg;
reg   [15:0] crystals_tower_1_0_3_4_read_int_reg;
reg   [15:0] crystals_tower_1_0_4_0_read_int_reg;
reg   [15:0] crystals_tower_1_0_4_1_read_int_reg;
reg   [15:0] crystals_tower_1_0_4_2_read_int_reg;
reg   [15:0] crystals_tower_1_0_4_3_read_int_reg;
reg   [15:0] crystals_tower_1_0_4_4_read_int_reg;
reg   [15:0] crystals_tower_1_1_0_0_read_int_reg;
reg   [15:0] crystals_tower_1_1_0_1_read_int_reg;
reg   [15:0] crystals_tower_1_1_0_2_read_int_reg;
reg   [15:0] crystals_tower_1_1_0_3_read_int_reg;
reg   [15:0] crystals_tower_1_1_0_4_read_int_reg;
reg   [15:0] crystals_tower_1_1_1_0_read_int_reg;
reg   [15:0] crystals_tower_1_1_1_1_read_int_reg;
reg   [15:0] crystals_tower_1_1_1_2_read_int_reg;
reg   [15:0] crystals_tower_1_1_1_3_read_int_reg;
reg   [15:0] crystals_tower_1_1_1_4_read_int_reg;
reg   [15:0] crystals_tower_1_1_2_0_read_int_reg;
reg   [15:0] crystals_tower_1_1_2_1_read_int_reg;
reg   [15:0] crystals_tower_1_1_2_2_read_int_reg;
reg   [15:0] crystals_tower_1_1_2_3_read_int_reg;
reg   [15:0] crystals_tower_1_1_2_4_read_int_reg;
reg   [15:0] crystals_tower_1_1_3_0_read_int_reg;
reg   [15:0] crystals_tower_1_1_3_1_read_int_reg;
reg   [15:0] crystals_tower_1_1_3_2_read_int_reg;
reg   [15:0] crystals_tower_1_1_3_3_read_int_reg;
reg   [15:0] crystals_tower_1_1_3_4_read_int_reg;
reg   [15:0] crystals_tower_1_1_4_0_read_int_reg;
reg   [15:0] crystals_tower_1_1_4_1_read_int_reg;
reg   [15:0] crystals_tower_1_1_4_2_read_int_reg;
reg   [15:0] crystals_tower_1_1_4_3_read_int_reg;
reg   [15:0] crystals_tower_1_1_4_4_read_int_reg;
reg   [15:0] crystals_tower_1_2_0_0_read_int_reg;
reg   [15:0] crystals_tower_1_2_0_1_read_int_reg;
reg   [15:0] crystals_tower_1_2_0_2_read_int_reg;
reg   [15:0] crystals_tower_1_2_0_3_read_int_reg;
reg   [15:0] crystals_tower_1_2_0_4_read_int_reg;
reg   [15:0] crystals_tower_1_2_1_0_read_int_reg;
reg   [15:0] crystals_tower_1_2_1_1_read_int_reg;
reg   [15:0] crystals_tower_1_2_1_2_read_int_reg;
reg   [15:0] crystals_tower_1_2_1_3_read_int_reg;
reg   [15:0] crystals_tower_1_2_1_4_read_int_reg;
reg   [15:0] crystals_tower_1_2_2_0_read_int_reg;
reg   [15:0] crystals_tower_1_2_2_1_read_int_reg;
reg   [15:0] crystals_tower_1_2_2_2_read_int_reg;
reg   [15:0] crystals_tower_1_2_2_3_read_int_reg;
reg   [15:0] crystals_tower_1_2_2_4_read_int_reg;
reg   [15:0] crystals_tower_1_2_3_0_read_int_reg;
reg   [15:0] crystals_tower_1_2_3_1_read_int_reg;
reg   [15:0] crystals_tower_1_2_3_2_read_int_reg;
reg   [15:0] crystals_tower_1_2_3_3_read_int_reg;
reg   [15:0] crystals_tower_1_2_3_4_read_int_reg;
reg   [15:0] crystals_tower_1_2_4_0_read_int_reg;
reg   [15:0] crystals_tower_1_2_4_1_read_int_reg;
reg   [15:0] crystals_tower_1_2_4_2_read_int_reg;
reg   [15:0] crystals_tower_1_2_4_3_read_int_reg;
reg   [15:0] crystals_tower_1_2_4_4_read_int_reg;
reg   [15:0] crystals_tower_1_3_0_0_read_int_reg;
reg   [15:0] crystals_tower_1_3_0_1_read_int_reg;
reg   [15:0] crystals_tower_1_3_0_2_read_int_reg;
reg   [15:0] crystals_tower_1_3_0_3_read_int_reg;
reg   [15:0] crystals_tower_1_3_0_4_read_int_reg;
reg   [15:0] crystals_tower_1_3_1_0_read_int_reg;
reg   [15:0] crystals_tower_1_3_1_1_read_int_reg;
reg   [15:0] crystals_tower_1_3_1_2_read_int_reg;
reg   [15:0] crystals_tower_1_3_1_3_read_int_reg;
reg   [15:0] crystals_tower_1_3_1_4_read_int_reg;
reg   [15:0] crystals_tower_1_3_2_0_read_int_reg;
reg   [15:0] crystals_tower_1_3_2_1_read_int_reg;
reg   [15:0] crystals_tower_1_3_2_2_read_int_reg;
reg   [15:0] crystals_tower_1_3_2_3_read_int_reg;
reg   [15:0] crystals_tower_1_3_2_4_read_int_reg;
reg   [15:0] crystals_tower_1_3_3_0_read_int_reg;
reg   [15:0] crystals_tower_1_3_3_1_read_int_reg;
reg   [15:0] crystals_tower_1_3_3_2_read_int_reg;
reg   [15:0] crystals_tower_1_3_3_3_read_int_reg;
reg   [15:0] crystals_tower_1_3_3_4_read_int_reg;
reg   [15:0] crystals_tower_1_3_4_0_read_int_reg;
reg   [15:0] crystals_tower_1_3_4_1_read_int_reg;
reg   [15:0] crystals_tower_1_3_4_2_read_int_reg;
reg   [15:0] crystals_tower_1_3_4_3_read_int_reg;
reg   [15:0] crystals_tower_1_3_4_4_read_int_reg;
reg   [15:0] crystals_tower_2_0_0_0_read_int_reg;
reg   [15:0] crystals_tower_2_0_0_1_read_int_reg;
reg   [15:0] crystals_tower_2_0_0_2_read_int_reg;
reg   [15:0] crystals_tower_2_0_0_3_read_int_reg;
reg   [15:0] crystals_tower_2_0_0_4_read_int_reg;
reg   [15:0] crystals_tower_2_0_1_0_read_int_reg;
reg   [15:0] crystals_tower_2_0_1_1_read_int_reg;
reg   [15:0] crystals_tower_2_0_1_2_read_int_reg;
reg   [15:0] crystals_tower_2_0_1_3_read_int_reg;
reg   [15:0] crystals_tower_2_0_1_4_read_int_reg;
reg   [15:0] crystals_tower_2_0_2_0_read_int_reg;
reg   [15:0] crystals_tower_2_0_2_1_read_int_reg;
reg   [15:0] crystals_tower_2_0_2_2_read_int_reg;
reg   [15:0] crystals_tower_2_0_2_3_read_int_reg;
reg   [15:0] crystals_tower_2_0_2_4_read_int_reg;
reg   [15:0] crystals_tower_2_0_3_0_read_int_reg;
reg   [15:0] crystals_tower_2_0_3_1_read_int_reg;
reg   [15:0] crystals_tower_2_0_3_2_read_int_reg;
reg   [15:0] crystals_tower_2_0_3_3_read_int_reg;
reg   [15:0] crystals_tower_2_0_3_4_read_int_reg;
reg   [15:0] crystals_tower_2_0_4_0_read_int_reg;
reg   [15:0] crystals_tower_2_0_4_1_read_int_reg;
reg   [15:0] crystals_tower_2_0_4_2_read_int_reg;
reg   [15:0] crystals_tower_2_0_4_3_read_int_reg;
reg   [15:0] crystals_tower_2_0_4_4_read_int_reg;
reg   [15:0] crystals_tower_2_1_0_0_read_int_reg;
reg   [15:0] crystals_tower_2_1_0_1_read_int_reg;
reg   [15:0] crystals_tower_2_1_0_2_read_int_reg;
reg   [15:0] crystals_tower_2_1_0_3_read_int_reg;
reg   [15:0] crystals_tower_2_1_0_4_read_int_reg;
reg   [15:0] crystals_tower_2_1_1_0_read_int_reg;
reg   [15:0] crystals_tower_2_1_1_1_read_int_reg;
reg   [15:0] crystals_tower_2_1_1_2_read_int_reg;
reg   [15:0] crystals_tower_2_1_1_3_read_int_reg;
reg   [15:0] crystals_tower_2_1_1_4_read_int_reg;
reg   [15:0] crystals_tower_2_1_2_0_read_int_reg;
reg   [15:0] crystals_tower_2_1_2_1_read_int_reg;
reg   [15:0] crystals_tower_2_1_2_2_read_int_reg;
reg   [15:0] crystals_tower_2_1_2_3_read_int_reg;
reg   [15:0] crystals_tower_2_1_2_4_read_int_reg;
reg   [15:0] crystals_tower_2_1_3_0_read_int_reg;
reg   [15:0] crystals_tower_2_1_3_1_read_int_reg;
reg   [15:0] crystals_tower_2_1_3_2_read_int_reg;
reg   [15:0] crystals_tower_2_1_3_3_read_int_reg;
reg   [15:0] crystals_tower_2_1_3_4_read_int_reg;
reg   [15:0] crystals_tower_2_1_4_0_read_int_reg;
reg   [15:0] crystals_tower_2_1_4_1_read_int_reg;
reg   [15:0] crystals_tower_2_1_4_2_read_int_reg;
reg   [15:0] crystals_tower_2_1_4_3_read_int_reg;
reg   [15:0] crystals_tower_2_1_4_4_read_int_reg;
reg   [15:0] crystals_tower_2_2_0_0_read_int_reg;
reg   [15:0] crystals_tower_2_2_0_1_read_int_reg;
reg   [15:0] crystals_tower_2_2_0_2_read_int_reg;
reg   [15:0] crystals_tower_2_2_0_3_read_int_reg;
reg   [15:0] crystals_tower_2_2_0_4_read_int_reg;
reg   [15:0] crystals_tower_2_2_1_0_read_int_reg;
reg   [15:0] crystals_tower_2_2_1_1_read_int_reg;
reg   [15:0] crystals_tower_2_2_1_2_read_int_reg;
reg   [15:0] crystals_tower_2_2_1_3_read_int_reg;
reg   [15:0] crystals_tower_2_2_1_4_read_int_reg;
reg   [15:0] crystals_tower_2_2_2_0_read_int_reg;
reg   [15:0] crystals_tower_2_2_2_1_read_int_reg;
reg   [15:0] crystals_tower_2_2_2_2_read_int_reg;
reg   [15:0] crystals_tower_2_2_2_3_read_int_reg;
reg   [15:0] crystals_tower_2_2_2_4_read_int_reg;
reg   [15:0] crystals_tower_2_2_3_0_read_int_reg;
reg   [15:0] crystals_tower_2_2_3_1_read_int_reg;
reg   [15:0] crystals_tower_2_2_3_2_read_int_reg;
reg   [15:0] crystals_tower_2_2_3_3_read_int_reg;
reg   [15:0] crystals_tower_2_2_3_4_read_int_reg;
reg   [15:0] crystals_tower_2_2_4_0_read_int_reg;
reg   [15:0] crystals_tower_2_2_4_1_read_int_reg;
reg   [15:0] crystals_tower_2_2_4_2_read_int_reg;
reg   [15:0] crystals_tower_2_2_4_3_read_int_reg;
reg   [15:0] crystals_tower_2_2_4_4_read_int_reg;
reg   [15:0] crystals_tower_2_3_0_0_read_int_reg;
reg   [15:0] crystals_tower_2_3_0_1_read_int_reg;
reg   [15:0] crystals_tower_2_3_0_2_read_int_reg;
reg   [15:0] crystals_tower_2_3_0_3_read_int_reg;
reg   [15:0] crystals_tower_2_3_0_4_read_int_reg;
reg   [15:0] crystals_tower_2_3_1_0_read_int_reg;
reg   [15:0] crystals_tower_2_3_1_1_read_int_reg;
reg   [15:0] crystals_tower_2_3_1_2_read_int_reg;
reg   [15:0] crystals_tower_2_3_1_3_read_int_reg;
reg   [15:0] crystals_tower_2_3_1_4_read_int_reg;
reg   [15:0] crystals_tower_2_3_2_0_read_int_reg;
reg   [15:0] crystals_tower_2_3_2_1_read_int_reg;
reg   [15:0] crystals_tower_2_3_2_2_read_int_reg;
reg   [15:0] crystals_tower_2_3_2_3_read_int_reg;
reg   [15:0] crystals_tower_2_3_2_4_read_int_reg;
reg   [15:0] crystals_tower_2_3_3_0_read_int_reg;
reg   [15:0] crystals_tower_2_3_3_1_read_int_reg;
reg   [15:0] crystals_tower_2_3_3_2_read_int_reg;
reg   [15:0] crystals_tower_2_3_3_3_read_int_reg;
reg   [15:0] crystals_tower_2_3_3_4_read_int_reg;
reg   [15:0] crystals_tower_2_3_4_0_read_int_reg;
reg   [15:0] crystals_tower_2_3_4_1_read_int_reg;
reg   [15:0] crystals_tower_2_3_4_2_read_int_reg;
reg   [15:0] crystals_tower_2_3_4_3_read_int_reg;
reg   [15:0] crystals_tower_2_3_4_4_read_int_reg;

getClustersInTower grp_getClustersInTower_fu_2412(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .crystals_0_0_read(crystals_tower_0_0_0_0_read_int_reg),
    .crystals_0_1_read(crystals_tower_0_0_0_1_read_int_reg),
    .crystals_0_2_read(crystals_tower_0_0_0_2_read_int_reg),
    .crystals_0_3_read(crystals_tower_0_0_0_3_read_int_reg),
    .crystals_0_4_read(crystals_tower_0_0_0_4_read_int_reg),
    .crystals_1_0_read(crystals_tower_0_0_1_0_read_int_reg),
    .crystals_1_1_read(crystals_tower_0_0_1_1_read_int_reg),
    .crystals_1_2_read(crystals_tower_0_0_1_2_read_int_reg),
    .crystals_1_3_read(crystals_tower_0_0_1_3_read_int_reg),
    .crystals_1_4_read(crystals_tower_0_0_1_4_read_int_reg),
    .crystals_2_0_read(crystals_tower_0_0_2_0_read_int_reg),
    .crystals_2_1_read(crystals_tower_0_0_2_1_read_int_reg),
    .crystals_2_2_read(crystals_tower_0_0_2_2_read_int_reg),
    .crystals_2_3_read(crystals_tower_0_0_2_3_read_int_reg),
    .crystals_2_4_read(crystals_tower_0_0_2_4_read_int_reg),
    .crystals_3_0_read(crystals_tower_0_0_3_0_read_int_reg),
    .crystals_3_1_read(crystals_tower_0_0_3_1_read_int_reg),
    .crystals_3_2_read(crystals_tower_0_0_3_2_read_int_reg),
    .crystals_3_3_read(crystals_tower_0_0_3_3_read_int_reg),
    .crystals_3_4_read(crystals_tower_0_0_3_4_read_int_reg),
    .crystals_4_0_read(crystals_tower_0_0_4_0_read_int_reg),
    .crystals_4_1_read(crystals_tower_0_0_4_1_read_int_reg),
    .crystals_4_2_read(crystals_tower_0_0_4_2_read_int_reg),
    .crystals_4_3_read(crystals_tower_0_0_4_3_read_int_reg),
    .crystals_4_4_read(crystals_tower_0_0_4_4_read_int_reg),
    .ap_ce(grp_getClustersInTower_fu_2412_ap_ce)
);

getClustersInTower grp_getClustersInTower_fu_2466(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .crystals_0_0_read(crystals_tower_1_0_0_0_read_int_reg),
    .crystals_0_1_read(crystals_tower_1_0_0_1_read_int_reg),
    .crystals_0_2_read(crystals_tower_1_0_0_2_read_int_reg),
    .crystals_0_3_read(crystals_tower_1_0_0_3_read_int_reg),
    .crystals_0_4_read(crystals_tower_1_0_0_4_read_int_reg),
    .crystals_1_0_read(crystals_tower_1_0_1_0_read_int_reg),
    .crystals_1_1_read(crystals_tower_1_0_1_1_read_int_reg),
    .crystals_1_2_read(crystals_tower_1_0_1_2_read_int_reg),
    .crystals_1_3_read(crystals_tower_1_0_1_3_read_int_reg),
    .crystals_1_4_read(crystals_tower_1_0_1_4_read_int_reg),
    .crystals_2_0_read(crystals_tower_1_0_2_0_read_int_reg),
    .crystals_2_1_read(crystals_tower_1_0_2_1_read_int_reg),
    .crystals_2_2_read(crystals_tower_1_0_2_2_read_int_reg),
    .crystals_2_3_read(crystals_tower_1_0_2_3_read_int_reg),
    .crystals_2_4_read(crystals_tower_1_0_2_4_read_int_reg),
    .crystals_3_0_read(crystals_tower_1_0_3_0_read_int_reg),
    .crystals_3_1_read(crystals_tower_1_0_3_1_read_int_reg),
    .crystals_3_2_read(crystals_tower_1_0_3_2_read_int_reg),
    .crystals_3_3_read(crystals_tower_1_0_3_3_read_int_reg),
    .crystals_3_4_read(crystals_tower_1_0_3_4_read_int_reg),
    .crystals_4_0_read(crystals_tower_1_0_4_0_read_int_reg),
    .crystals_4_1_read(crystals_tower_1_0_4_1_read_int_reg),
    .crystals_4_2_read(crystals_tower_1_0_4_2_read_int_reg),
    .crystals_4_3_read(crystals_tower_1_0_4_3_read_int_reg),
    .crystals_4_4_read(crystals_tower_1_0_4_4_read_int_reg),
    .ap_ce(grp_getClustersInTower_fu_2466_ap_ce)
);

getClustersInTower grp_getClustersInTower_fu_2520(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .crystals_0_0_read(crystals_tower_2_0_0_0_read_int_reg),
    .crystals_0_1_read(crystals_tower_2_0_0_1_read_int_reg),
    .crystals_0_2_read(crystals_tower_2_0_0_2_read_int_reg),
    .crystals_0_3_read(crystals_tower_2_0_0_3_read_int_reg),
    .crystals_0_4_read(crystals_tower_2_0_0_4_read_int_reg),
    .crystals_1_0_read(crystals_tower_2_0_1_0_read_int_reg),
    .crystals_1_1_read(crystals_tower_2_0_1_1_read_int_reg),
    .crystals_1_2_read(crystals_tower_2_0_1_2_read_int_reg),
    .crystals_1_3_read(crystals_tower_2_0_1_3_read_int_reg),
    .crystals_1_4_read(crystals_tower_2_0_1_4_read_int_reg),
    .crystals_2_0_read(crystals_tower_2_0_2_0_read_int_reg),
    .crystals_2_1_read(crystals_tower_2_0_2_1_read_int_reg),
    .crystals_2_2_read(crystals_tower_2_0_2_2_read_int_reg),
    .crystals_2_3_read(crystals_tower_2_0_2_3_read_int_reg),
    .crystals_2_4_read(crystals_tower_2_0_2_4_read_int_reg),
    .crystals_3_0_read(crystals_tower_2_0_3_0_read_int_reg),
    .crystals_3_1_read(crystals_tower_2_0_3_1_read_int_reg),
    .crystals_3_2_read(crystals_tower_2_0_3_2_read_int_reg),
    .crystals_3_3_read(crystals_tower_2_0_3_3_read_int_reg),
    .crystals_3_4_read(crystals_tower_2_0_3_4_read_int_reg),
    .crystals_4_0_read(crystals_tower_2_0_4_0_read_int_reg),
    .crystals_4_1_read(crystals_tower_2_0_4_1_read_int_reg),
    .crystals_4_2_read(crystals_tower_2_0_4_2_read_int_reg),
    .crystals_4_3_read(crystals_tower_2_0_4_3_read_int_reg),
    .crystals_4_4_read(crystals_tower_2_0_4_4_read_int_reg),
    .ap_ce(grp_getClustersInTower_fu_2520_ap_ce)
);

getClustersInTower grp_getClustersInTower_fu_2574(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .crystals_0_0_read(crystals_tower_0_1_0_0_read_int_reg),
    .crystals_0_1_read(crystals_tower_0_1_0_1_read_int_reg),
    .crystals_0_2_read(crystals_tower_0_1_0_2_read_int_reg),
    .crystals_0_3_read(crystals_tower_0_1_0_3_read_int_reg),
    .crystals_0_4_read(crystals_tower_0_1_0_4_read_int_reg),
    .crystals_1_0_read(crystals_tower_0_1_1_0_read_int_reg),
    .crystals_1_1_read(crystals_tower_0_1_1_1_read_int_reg),
    .crystals_1_2_read(crystals_tower_0_1_1_2_read_int_reg),
    .crystals_1_3_read(crystals_tower_0_1_1_3_read_int_reg),
    .crystals_1_4_read(crystals_tower_0_1_1_4_read_int_reg),
    .crystals_2_0_read(crystals_tower_0_1_2_0_read_int_reg),
    .crystals_2_1_read(crystals_tower_0_1_2_1_read_int_reg),
    .crystals_2_2_read(crystals_tower_0_1_2_2_read_int_reg),
    .crystals_2_3_read(crystals_tower_0_1_2_3_read_int_reg),
    .crystals_2_4_read(crystals_tower_0_1_2_4_read_int_reg),
    .crystals_3_0_read(crystals_tower_0_1_3_0_read_int_reg),
    .crystals_3_1_read(crystals_tower_0_1_3_1_read_int_reg),
    .crystals_3_2_read(crystals_tower_0_1_3_2_read_int_reg),
    .crystals_3_3_read(crystals_tower_0_1_3_3_read_int_reg),
    .crystals_3_4_read(crystals_tower_0_1_3_4_read_int_reg),
    .crystals_4_0_read(crystals_tower_0_1_4_0_read_int_reg),
    .crystals_4_1_read(crystals_tower_0_1_4_1_read_int_reg),
    .crystals_4_2_read(crystals_tower_0_1_4_2_read_int_reg),
    .crystals_4_3_read(crystals_tower_0_1_4_3_read_int_reg),
    .crystals_4_4_read(crystals_tower_0_1_4_4_read_int_reg),
    .ap_ce(grp_getClustersInTower_fu_2574_ap_ce)
);

getClustersInTower grp_getClustersInTower_fu_2628(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .crystals_0_0_read(crystals_tower_1_1_0_0_read_int_reg),
    .crystals_0_1_read(crystals_tower_1_1_0_1_read_int_reg),
    .crystals_0_2_read(crystals_tower_1_1_0_2_read_int_reg),
    .crystals_0_3_read(crystals_tower_1_1_0_3_read_int_reg),
    .crystals_0_4_read(crystals_tower_1_1_0_4_read_int_reg),
    .crystals_1_0_read(crystals_tower_1_1_1_0_read_int_reg),
    .crystals_1_1_read(crystals_tower_1_1_1_1_read_int_reg),
    .crystals_1_2_read(crystals_tower_1_1_1_2_read_int_reg),
    .crystals_1_3_read(crystals_tower_1_1_1_3_read_int_reg),
    .crystals_1_4_read(crystals_tower_1_1_1_4_read_int_reg),
    .crystals_2_0_read(crystals_tower_1_1_2_0_read_int_reg),
    .crystals_2_1_read(crystals_tower_1_1_2_1_read_int_reg),
    .crystals_2_2_read(crystals_tower_1_1_2_2_read_int_reg),
    .crystals_2_3_read(crystals_tower_1_1_2_3_read_int_reg),
    .crystals_2_4_read(crystals_tower_1_1_2_4_read_int_reg),
    .crystals_3_0_read(crystals_tower_1_1_3_0_read_int_reg),
    .crystals_3_1_read(crystals_tower_1_1_3_1_read_int_reg),
    .crystals_3_2_read(crystals_tower_1_1_3_2_read_int_reg),
    .crystals_3_3_read(crystals_tower_1_1_3_3_read_int_reg),
    .crystals_3_4_read(crystals_tower_1_1_3_4_read_int_reg),
    .crystals_4_0_read(crystals_tower_1_1_4_0_read_int_reg),
    .crystals_4_1_read(crystals_tower_1_1_4_1_read_int_reg),
    .crystals_4_2_read(crystals_tower_1_1_4_2_read_int_reg),
    .crystals_4_3_read(crystals_tower_1_1_4_3_read_int_reg),
    .crystals_4_4_read(crystals_tower_1_1_4_4_read_int_reg),
    .ap_ce(grp_getClustersInTower_fu_2628_ap_ce)
);

getClustersInTower grp_getClustersInTower_fu_2682(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .crystals_0_0_read(crystals_tower_2_1_0_0_read_int_reg),
    .crystals_0_1_read(crystals_tower_2_1_0_1_read_int_reg),
    .crystals_0_2_read(crystals_tower_2_1_0_2_read_int_reg),
    .crystals_0_3_read(crystals_tower_2_1_0_3_read_int_reg),
    .crystals_0_4_read(crystals_tower_2_1_0_4_read_int_reg),
    .crystals_1_0_read(crystals_tower_2_1_1_0_read_int_reg),
    .crystals_1_1_read(crystals_tower_2_1_1_1_read_int_reg),
    .crystals_1_2_read(crystals_tower_2_1_1_2_read_int_reg),
    .crystals_1_3_read(crystals_tower_2_1_1_3_read_int_reg),
    .crystals_1_4_read(crystals_tower_2_1_1_4_read_int_reg),
    .crystals_2_0_read(crystals_tower_2_1_2_0_read_int_reg),
    .crystals_2_1_read(crystals_tower_2_1_2_1_read_int_reg),
    .crystals_2_2_read(crystals_tower_2_1_2_2_read_int_reg),
    .crystals_2_3_read(crystals_tower_2_1_2_3_read_int_reg),
    .crystals_2_4_read(crystals_tower_2_1_2_4_read_int_reg),
    .crystals_3_0_read(crystals_tower_2_1_3_0_read_int_reg),
    .crystals_3_1_read(crystals_tower_2_1_3_1_read_int_reg),
    .crystals_3_2_read(crystals_tower_2_1_3_2_read_int_reg),
    .crystals_3_3_read(crystals_tower_2_1_3_3_read_int_reg),
    .crystals_3_4_read(crystals_tower_2_1_3_4_read_int_reg),
    .crystals_4_0_read(crystals_tower_2_1_4_0_read_int_reg),
    .crystals_4_1_read(crystals_tower_2_1_4_1_read_int_reg),
    .crystals_4_2_read(crystals_tower_2_1_4_2_read_int_reg),
    .crystals_4_3_read(crystals_tower_2_1_4_3_read_int_reg),
    .crystals_4_4_read(crystals_tower_2_1_4_4_read_int_reg),
    .ap_ce(grp_getClustersInTower_fu_2682_ap_ce)
);

getClustersInTower grp_getClustersInTower_fu_2736(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .crystals_0_0_read(crystals_tower_0_2_0_0_read_int_reg),
    .crystals_0_1_read(crystals_tower_0_2_0_1_read_int_reg),
    .crystals_0_2_read(crystals_tower_0_2_0_2_read_int_reg),
    .crystals_0_3_read(crystals_tower_0_2_0_3_read_int_reg),
    .crystals_0_4_read(crystals_tower_0_2_0_4_read_int_reg),
    .crystals_1_0_read(crystals_tower_0_2_1_0_read_int_reg),
    .crystals_1_1_read(crystals_tower_0_2_1_1_read_int_reg),
    .crystals_1_2_read(crystals_tower_0_2_1_2_read_int_reg),
    .crystals_1_3_read(crystals_tower_0_2_1_3_read_int_reg),
    .crystals_1_4_read(crystals_tower_0_2_1_4_read_int_reg),
    .crystals_2_0_read(crystals_tower_0_2_2_0_read_int_reg),
    .crystals_2_1_read(crystals_tower_0_2_2_1_read_int_reg),
    .crystals_2_2_read(crystals_tower_0_2_2_2_read_int_reg),
    .crystals_2_3_read(crystals_tower_0_2_2_3_read_int_reg),
    .crystals_2_4_read(crystals_tower_0_2_2_4_read_int_reg),
    .crystals_3_0_read(crystals_tower_0_2_3_0_read_int_reg),
    .crystals_3_1_read(crystals_tower_0_2_3_1_read_int_reg),
    .crystals_3_2_read(crystals_tower_0_2_3_2_read_int_reg),
    .crystals_3_3_read(crystals_tower_0_2_3_3_read_int_reg),
    .crystals_3_4_read(crystals_tower_0_2_3_4_read_int_reg),
    .crystals_4_0_read(crystals_tower_0_2_4_0_read_int_reg),
    .crystals_4_1_read(crystals_tower_0_2_4_1_read_int_reg),
    .crystals_4_2_read(crystals_tower_0_2_4_2_read_int_reg),
    .crystals_4_3_read(crystals_tower_0_2_4_3_read_int_reg),
    .crystals_4_4_read(crystals_tower_0_2_4_4_read_int_reg),
    .ap_ce(grp_getClustersInTower_fu_2736_ap_ce)
);

getClustersInTower grp_getClustersInTower_fu_2790(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .crystals_0_0_read(crystals_tower_1_2_0_0_read_int_reg),
    .crystals_0_1_read(crystals_tower_1_2_0_1_read_int_reg),
    .crystals_0_2_read(crystals_tower_1_2_0_2_read_int_reg),
    .crystals_0_3_read(crystals_tower_1_2_0_3_read_int_reg),
    .crystals_0_4_read(crystals_tower_1_2_0_4_read_int_reg),
    .crystals_1_0_read(crystals_tower_1_2_1_0_read_int_reg),
    .crystals_1_1_read(crystals_tower_1_2_1_1_read_int_reg),
    .crystals_1_2_read(crystals_tower_1_2_1_2_read_int_reg),
    .crystals_1_3_read(crystals_tower_1_2_1_3_read_int_reg),
    .crystals_1_4_read(crystals_tower_1_2_1_4_read_int_reg),
    .crystals_2_0_read(crystals_tower_1_2_2_0_read_int_reg),
    .crystals_2_1_read(crystals_tower_1_2_2_1_read_int_reg),
    .crystals_2_2_read(crystals_tower_1_2_2_2_read_int_reg),
    .crystals_2_3_read(crystals_tower_1_2_2_3_read_int_reg),
    .crystals_2_4_read(crystals_tower_1_2_2_4_read_int_reg),
    .crystals_3_0_read(crystals_tower_1_2_3_0_read_int_reg),
    .crystals_3_1_read(crystals_tower_1_2_3_1_read_int_reg),
    .crystals_3_2_read(crystals_tower_1_2_3_2_read_int_reg),
    .crystals_3_3_read(crystals_tower_1_2_3_3_read_int_reg),
    .crystals_3_4_read(crystals_tower_1_2_3_4_read_int_reg),
    .crystals_4_0_read(crystals_tower_1_2_4_0_read_int_reg),
    .crystals_4_1_read(crystals_tower_1_2_4_1_read_int_reg),
    .crystals_4_2_read(crystals_tower_1_2_4_2_read_int_reg),
    .crystals_4_3_read(crystals_tower_1_2_4_3_read_int_reg),
    .crystals_4_4_read(crystals_tower_1_2_4_4_read_int_reg),
    .ap_ce(grp_getClustersInTower_fu_2790_ap_ce)
);

getClustersInTower grp_getClustersInTower_fu_2844(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .crystals_0_0_read(crystals_tower_2_2_0_0_read_int_reg),
    .crystals_0_1_read(crystals_tower_2_2_0_1_read_int_reg),
    .crystals_0_2_read(crystals_tower_2_2_0_2_read_int_reg),
    .crystals_0_3_read(crystals_tower_2_2_0_3_read_int_reg),
    .crystals_0_4_read(crystals_tower_2_2_0_4_read_int_reg),
    .crystals_1_0_read(crystals_tower_2_2_1_0_read_int_reg),
    .crystals_1_1_read(crystals_tower_2_2_1_1_read_int_reg),
    .crystals_1_2_read(crystals_tower_2_2_1_2_read_int_reg),
    .crystals_1_3_read(crystals_tower_2_2_1_3_read_int_reg),
    .crystals_1_4_read(crystals_tower_2_2_1_4_read_int_reg),
    .crystals_2_0_read(crystals_tower_2_2_2_0_read_int_reg),
    .crystals_2_1_read(crystals_tower_2_2_2_1_read_int_reg),
    .crystals_2_2_read(crystals_tower_2_2_2_2_read_int_reg),
    .crystals_2_3_read(crystals_tower_2_2_2_3_read_int_reg),
    .crystals_2_4_read(crystals_tower_2_2_2_4_read_int_reg),
    .crystals_3_0_read(crystals_tower_2_2_3_0_read_int_reg),
    .crystals_3_1_read(crystals_tower_2_2_3_1_read_int_reg),
    .crystals_3_2_read(crystals_tower_2_2_3_2_read_int_reg),
    .crystals_3_3_read(crystals_tower_2_2_3_3_read_int_reg),
    .crystals_3_4_read(crystals_tower_2_2_3_4_read_int_reg),
    .crystals_4_0_read(crystals_tower_2_2_4_0_read_int_reg),
    .crystals_4_1_read(crystals_tower_2_2_4_1_read_int_reg),
    .crystals_4_2_read(crystals_tower_2_2_4_2_read_int_reg),
    .crystals_4_3_read(crystals_tower_2_2_4_3_read_int_reg),
    .crystals_4_4_read(crystals_tower_2_2_4_4_read_int_reg),
    .ap_ce(grp_getClustersInTower_fu_2844_ap_ce)
);

getClustersInTower grp_getClustersInTower_fu_2898(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .crystals_0_0_read(crystals_tower_0_3_0_0_read_int_reg),
    .crystals_0_1_read(crystals_tower_0_3_0_1_read_int_reg),
    .crystals_0_2_read(crystals_tower_0_3_0_2_read_int_reg),
    .crystals_0_3_read(crystals_tower_0_3_0_3_read_int_reg),
    .crystals_0_4_read(crystals_tower_0_3_0_4_read_int_reg),
    .crystals_1_0_read(crystals_tower_0_3_1_0_read_int_reg),
    .crystals_1_1_read(crystals_tower_0_3_1_1_read_int_reg),
    .crystals_1_2_read(crystals_tower_0_3_1_2_read_int_reg),
    .crystals_1_3_read(crystals_tower_0_3_1_3_read_int_reg),
    .crystals_1_4_read(crystals_tower_0_3_1_4_read_int_reg),
    .crystals_2_0_read(crystals_tower_0_3_2_0_read_int_reg),
    .crystals_2_1_read(crystals_tower_0_3_2_1_read_int_reg),
    .crystals_2_2_read(crystals_tower_0_3_2_2_read_int_reg),
    .crystals_2_3_read(crystals_tower_0_3_2_3_read_int_reg),
    .crystals_2_4_read(crystals_tower_0_3_2_4_read_int_reg),
    .crystals_3_0_read(crystals_tower_0_3_3_0_read_int_reg),
    .crystals_3_1_read(crystals_tower_0_3_3_1_read_int_reg),
    .crystals_3_2_read(crystals_tower_0_3_3_2_read_int_reg),
    .crystals_3_3_read(crystals_tower_0_3_3_3_read_int_reg),
    .crystals_3_4_read(crystals_tower_0_3_3_4_read_int_reg),
    .crystals_4_0_read(crystals_tower_0_3_4_0_read_int_reg),
    .crystals_4_1_read(crystals_tower_0_3_4_1_read_int_reg),
    .crystals_4_2_read(crystals_tower_0_3_4_2_read_int_reg),
    .crystals_4_3_read(crystals_tower_0_3_4_3_read_int_reg),
    .crystals_4_4_read(crystals_tower_0_3_4_4_read_int_reg),
    .ap_ce(grp_getClustersInTower_fu_2898_ap_ce)
);

getClustersInTower grp_getClustersInTower_fu_2952(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .crystals_0_0_read(crystals_tower_1_3_0_0_read_int_reg),
    .crystals_0_1_read(crystals_tower_1_3_0_1_read_int_reg),
    .crystals_0_2_read(crystals_tower_1_3_0_2_read_int_reg),
    .crystals_0_3_read(crystals_tower_1_3_0_3_read_int_reg),
    .crystals_0_4_read(crystals_tower_1_3_0_4_read_int_reg),
    .crystals_1_0_read(crystals_tower_1_3_1_0_read_int_reg),
    .crystals_1_1_read(crystals_tower_1_3_1_1_read_int_reg),
    .crystals_1_2_read(crystals_tower_1_3_1_2_read_int_reg),
    .crystals_1_3_read(crystals_tower_1_3_1_3_read_int_reg),
    .crystals_1_4_read(crystals_tower_1_3_1_4_read_int_reg),
    .crystals_2_0_read(crystals_tower_1_3_2_0_read_int_reg),
    .crystals_2_1_read(crystals_tower_1_3_2_1_read_int_reg),
    .crystals_2_2_read(crystals_tower_1_3_2_2_read_int_reg),
    .crystals_2_3_read(crystals_tower_1_3_2_3_read_int_reg),
    .crystals_2_4_read(crystals_tower_1_3_2_4_read_int_reg),
    .crystals_3_0_read(crystals_tower_1_3_3_0_read_int_reg),
    .crystals_3_1_read(crystals_tower_1_3_3_1_read_int_reg),
    .crystals_3_2_read(crystals_tower_1_3_3_2_read_int_reg),
    .crystals_3_3_read(crystals_tower_1_3_3_3_read_int_reg),
    .crystals_3_4_read(crystals_tower_1_3_3_4_read_int_reg),
    .crystals_4_0_read(crystals_tower_1_3_4_0_read_int_reg),
    .crystals_4_1_read(crystals_tower_1_3_4_1_read_int_reg),
    .crystals_4_2_read(crystals_tower_1_3_4_2_read_int_reg),
    .crystals_4_3_read(crystals_tower_1_3_4_3_read_int_reg),
    .crystals_4_4_read(crystals_tower_1_3_4_4_read_int_reg),
    .ap_ce(grp_getClustersInTower_fu_2952_ap_ce)
);

getClustersInTower grp_getClustersInTower_fu_3006(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .crystals_0_0_read(crystals_tower_2_3_0_0_read_int_reg),
    .crystals_0_1_read(crystals_tower_2_3_0_1_read_int_reg),
    .crystals_0_2_read(crystals_tower_2_3_0_2_read_int_reg),
    .crystals_0_3_read(crystals_tower_2_3_0_3_read_int_reg),
    .crystals_0_4_read(crystals_tower_2_3_0_4_read_int_reg),
    .crystals_1_0_read(crystals_tower_2_3_1_0_read_int_reg),
    .crystals_1_1_read(crystals_tower_2_3_1_1_read_int_reg),
    .crystals_1_2_read(crystals_tower_2_3_1_2_read_int_reg),
    .crystals_1_3_read(crystals_tower_2_3_1_3_read_int_reg),
    .crystals_1_4_read(crystals_tower_2_3_1_4_read_int_reg),
    .crystals_2_0_read(crystals_tower_2_3_2_0_read_int_reg),
    .crystals_2_1_read(crystals_tower_2_3_2_1_read_int_reg),
    .crystals_2_2_read(crystals_tower_2_3_2_2_read_int_reg),
    .crystals_2_3_read(crystals_tower_2_3_2_3_read_int_reg),
    .crystals_2_4_read(crystals_tower_2_3_2_4_read_int_reg),
    .crystals_3_0_read(crystals_tower_2_3_3_0_read_int_reg),
    .crystals_3_1_read(crystals_tower_2_3_3_1_read_int_reg),
    .crystals_3_2_read(crystals_tower_2_3_3_2_read_int_reg),
    .crystals_3_3_read(crystals_tower_2_3_3_3_read_int_reg),
    .crystals_3_4_read(crystals_tower_2_3_3_4_read_int_reg),
    .crystals_4_0_read(crystals_tower_2_3_4_0_read_int_reg),
    .crystals_4_1_read(crystals_tower_2_3_4_1_read_int_reg),
    .crystals_4_2_read(crystals_tower_2_3_4_2_read_int_reg),
    .crystals_4_3_read(crystals_tower_2_3_4_3_read_int_reg),
    .crystals_4_4_read(crystals_tower_2_3_4_4_read_int_reg),
    .ap_ce(grp_getClustersInTower_fu_3006_ap_ce)
);

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        crystals_tower_0_0_0_0_read_int_reg <= crystals_tower_0_0_0_0_read;
        crystals_tower_0_0_0_1_read_int_reg <= crystals_tower_0_0_0_1_read;
        crystals_tower_0_0_0_2_read_int_reg <= crystals_tower_0_0_0_2_read;
        crystals_tower_0_0_0_3_read_int_reg <= crystals_tower_0_0_0_3_read;
        crystals_tower_0_0_0_4_read_int_reg <= crystals_tower_0_0_0_4_read;
        crystals_tower_0_0_1_0_read_int_reg <= crystals_tower_0_0_1_0_read;
        crystals_tower_0_0_1_1_read_int_reg <= crystals_tower_0_0_1_1_read;
        crystals_tower_0_0_1_2_read_int_reg <= crystals_tower_0_0_1_2_read;
        crystals_tower_0_0_1_3_read_int_reg <= crystals_tower_0_0_1_3_read;
        crystals_tower_0_0_1_4_read_int_reg <= crystals_tower_0_0_1_4_read;
        crystals_tower_0_0_2_0_read_int_reg <= crystals_tower_0_0_2_0_read;
        crystals_tower_0_0_2_1_read_int_reg <= crystals_tower_0_0_2_1_read;
        crystals_tower_0_0_2_2_read_int_reg <= crystals_tower_0_0_2_2_read;
        crystals_tower_0_0_2_3_read_int_reg <= crystals_tower_0_0_2_3_read;
        crystals_tower_0_0_2_4_read_int_reg <= crystals_tower_0_0_2_4_read;
        crystals_tower_0_0_3_0_read_int_reg <= crystals_tower_0_0_3_0_read;
        crystals_tower_0_0_3_1_read_int_reg <= crystals_tower_0_0_3_1_read;
        crystals_tower_0_0_3_2_read_int_reg <= crystals_tower_0_0_3_2_read;
        crystals_tower_0_0_3_3_read_int_reg <= crystals_tower_0_0_3_3_read;
        crystals_tower_0_0_3_4_read_int_reg <= crystals_tower_0_0_3_4_read;
        crystals_tower_0_0_4_0_read_int_reg <= crystals_tower_0_0_4_0_read;
        crystals_tower_0_0_4_1_read_int_reg <= crystals_tower_0_0_4_1_read;
        crystals_tower_0_0_4_2_read_int_reg <= crystals_tower_0_0_4_2_read;
        crystals_tower_0_0_4_3_read_int_reg <= crystals_tower_0_0_4_3_read;
        crystals_tower_0_0_4_4_read_int_reg <= crystals_tower_0_0_4_4_read;
        crystals_tower_0_1_0_0_read_int_reg <= crystals_tower_0_1_0_0_read;
        crystals_tower_0_1_0_1_read_int_reg <= crystals_tower_0_1_0_1_read;
        crystals_tower_0_1_0_2_read_int_reg <= crystals_tower_0_1_0_2_read;
        crystals_tower_0_1_0_3_read_int_reg <= crystals_tower_0_1_0_3_read;
        crystals_tower_0_1_0_4_read_int_reg <= crystals_tower_0_1_0_4_read;
        crystals_tower_0_1_1_0_read_int_reg <= crystals_tower_0_1_1_0_read;
        crystals_tower_0_1_1_1_read_int_reg <= crystals_tower_0_1_1_1_read;
        crystals_tower_0_1_1_2_read_int_reg <= crystals_tower_0_1_1_2_read;
        crystals_tower_0_1_1_3_read_int_reg <= crystals_tower_0_1_1_3_read;
        crystals_tower_0_1_1_4_read_int_reg <= crystals_tower_0_1_1_4_read;
        crystals_tower_0_1_2_0_read_int_reg <= crystals_tower_0_1_2_0_read;
        crystals_tower_0_1_2_1_read_int_reg <= crystals_tower_0_1_2_1_read;
        crystals_tower_0_1_2_2_read_int_reg <= crystals_tower_0_1_2_2_read;
        crystals_tower_0_1_2_3_read_int_reg <= crystals_tower_0_1_2_3_read;
        crystals_tower_0_1_2_4_read_int_reg <= crystals_tower_0_1_2_4_read;
        crystals_tower_0_1_3_0_read_int_reg <= crystals_tower_0_1_3_0_read;
        crystals_tower_0_1_3_1_read_int_reg <= crystals_tower_0_1_3_1_read;
        crystals_tower_0_1_3_2_read_int_reg <= crystals_tower_0_1_3_2_read;
        crystals_tower_0_1_3_3_read_int_reg <= crystals_tower_0_1_3_3_read;
        crystals_tower_0_1_3_4_read_int_reg <= crystals_tower_0_1_3_4_read;
        crystals_tower_0_1_4_0_read_int_reg <= crystals_tower_0_1_4_0_read;
        crystals_tower_0_1_4_1_read_int_reg <= crystals_tower_0_1_4_1_read;
        crystals_tower_0_1_4_2_read_int_reg <= crystals_tower_0_1_4_2_read;
        crystals_tower_0_1_4_3_read_int_reg <= crystals_tower_0_1_4_3_read;
        crystals_tower_0_1_4_4_read_int_reg <= crystals_tower_0_1_4_4_read;
        crystals_tower_0_2_0_0_read_int_reg <= crystals_tower_0_2_0_0_read;
        crystals_tower_0_2_0_1_read_int_reg <= crystals_tower_0_2_0_1_read;
        crystals_tower_0_2_0_2_read_int_reg <= crystals_tower_0_2_0_2_read;
        crystals_tower_0_2_0_3_read_int_reg <= crystals_tower_0_2_0_3_read;
        crystals_tower_0_2_0_4_read_int_reg <= crystals_tower_0_2_0_4_read;
        crystals_tower_0_2_1_0_read_int_reg <= crystals_tower_0_2_1_0_read;
        crystals_tower_0_2_1_1_read_int_reg <= crystals_tower_0_2_1_1_read;
        crystals_tower_0_2_1_2_read_int_reg <= crystals_tower_0_2_1_2_read;
        crystals_tower_0_2_1_3_read_int_reg <= crystals_tower_0_2_1_3_read;
        crystals_tower_0_2_1_4_read_int_reg <= crystals_tower_0_2_1_4_read;
        crystals_tower_0_2_2_0_read_int_reg <= crystals_tower_0_2_2_0_read;
        crystals_tower_0_2_2_1_read_int_reg <= crystals_tower_0_2_2_1_read;
        crystals_tower_0_2_2_2_read_int_reg <= crystals_tower_0_2_2_2_read;
        crystals_tower_0_2_2_3_read_int_reg <= crystals_tower_0_2_2_3_read;
        crystals_tower_0_2_2_4_read_int_reg <= crystals_tower_0_2_2_4_read;
        crystals_tower_0_2_3_0_read_int_reg <= crystals_tower_0_2_3_0_read;
        crystals_tower_0_2_3_1_read_int_reg <= crystals_tower_0_2_3_1_read;
        crystals_tower_0_2_3_2_read_int_reg <= crystals_tower_0_2_3_2_read;
        crystals_tower_0_2_3_3_read_int_reg <= crystals_tower_0_2_3_3_read;
        crystals_tower_0_2_3_4_read_int_reg <= crystals_tower_0_2_3_4_read;
        crystals_tower_0_2_4_0_read_int_reg <= crystals_tower_0_2_4_0_read;
        crystals_tower_0_2_4_1_read_int_reg <= crystals_tower_0_2_4_1_read;
        crystals_tower_0_2_4_2_read_int_reg <= crystals_tower_0_2_4_2_read;
        crystals_tower_0_2_4_3_read_int_reg <= crystals_tower_0_2_4_3_read;
        crystals_tower_0_2_4_4_read_int_reg <= crystals_tower_0_2_4_4_read;
        crystals_tower_0_3_0_0_read_int_reg <= crystals_tower_0_3_0_0_read;
        crystals_tower_0_3_0_1_read_int_reg <= crystals_tower_0_3_0_1_read;
        crystals_tower_0_3_0_2_read_int_reg <= crystals_tower_0_3_0_2_read;
        crystals_tower_0_3_0_3_read_int_reg <= crystals_tower_0_3_0_3_read;
        crystals_tower_0_3_0_4_read_int_reg <= crystals_tower_0_3_0_4_read;
        crystals_tower_0_3_1_0_read_int_reg <= crystals_tower_0_3_1_0_read;
        crystals_tower_0_3_1_1_read_int_reg <= crystals_tower_0_3_1_1_read;
        crystals_tower_0_3_1_2_read_int_reg <= crystals_tower_0_3_1_2_read;
        crystals_tower_0_3_1_3_read_int_reg <= crystals_tower_0_3_1_3_read;
        crystals_tower_0_3_1_4_read_int_reg <= crystals_tower_0_3_1_4_read;
        crystals_tower_0_3_2_0_read_int_reg <= crystals_tower_0_3_2_0_read;
        crystals_tower_0_3_2_1_read_int_reg <= crystals_tower_0_3_2_1_read;
        crystals_tower_0_3_2_2_read_int_reg <= crystals_tower_0_3_2_2_read;
        crystals_tower_0_3_2_3_read_int_reg <= crystals_tower_0_3_2_3_read;
        crystals_tower_0_3_2_4_read_int_reg <= crystals_tower_0_3_2_4_read;
        crystals_tower_0_3_3_0_read_int_reg <= crystals_tower_0_3_3_0_read;
        crystals_tower_0_3_3_1_read_int_reg <= crystals_tower_0_3_3_1_read;
        crystals_tower_0_3_3_2_read_int_reg <= crystals_tower_0_3_3_2_read;
        crystals_tower_0_3_3_3_read_int_reg <= crystals_tower_0_3_3_3_read;
        crystals_tower_0_3_3_4_read_int_reg <= crystals_tower_0_3_3_4_read;
        crystals_tower_0_3_4_0_read_int_reg <= crystals_tower_0_3_4_0_read;
        crystals_tower_0_3_4_1_read_int_reg <= crystals_tower_0_3_4_1_read;
        crystals_tower_0_3_4_2_read_int_reg <= crystals_tower_0_3_4_2_read;
        crystals_tower_0_3_4_3_read_int_reg <= crystals_tower_0_3_4_3_read;
        crystals_tower_0_3_4_4_read_int_reg <= crystals_tower_0_3_4_4_read;
        crystals_tower_1_0_0_0_read_int_reg <= crystals_tower_1_0_0_0_read;
        crystals_tower_1_0_0_1_read_int_reg <= crystals_tower_1_0_0_1_read;
        crystals_tower_1_0_0_2_read_int_reg <= crystals_tower_1_0_0_2_read;
        crystals_tower_1_0_0_3_read_int_reg <= crystals_tower_1_0_0_3_read;
        crystals_tower_1_0_0_4_read_int_reg <= crystals_tower_1_0_0_4_read;
        crystals_tower_1_0_1_0_read_int_reg <= crystals_tower_1_0_1_0_read;
        crystals_tower_1_0_1_1_read_int_reg <= crystals_tower_1_0_1_1_read;
        crystals_tower_1_0_1_2_read_int_reg <= crystals_tower_1_0_1_2_read;
        crystals_tower_1_0_1_3_read_int_reg <= crystals_tower_1_0_1_3_read;
        crystals_tower_1_0_1_4_read_int_reg <= crystals_tower_1_0_1_4_read;
        crystals_tower_1_0_2_0_read_int_reg <= crystals_tower_1_0_2_0_read;
        crystals_tower_1_0_2_1_read_int_reg <= crystals_tower_1_0_2_1_read;
        crystals_tower_1_0_2_2_read_int_reg <= crystals_tower_1_0_2_2_read;
        crystals_tower_1_0_2_3_read_int_reg <= crystals_tower_1_0_2_3_read;
        crystals_tower_1_0_2_4_read_int_reg <= crystals_tower_1_0_2_4_read;
        crystals_tower_1_0_3_0_read_int_reg <= crystals_tower_1_0_3_0_read;
        crystals_tower_1_0_3_1_read_int_reg <= crystals_tower_1_0_3_1_read;
        crystals_tower_1_0_3_2_read_int_reg <= crystals_tower_1_0_3_2_read;
        crystals_tower_1_0_3_3_read_int_reg <= crystals_tower_1_0_3_3_read;
        crystals_tower_1_0_3_4_read_int_reg <= crystals_tower_1_0_3_4_read;
        crystals_tower_1_0_4_0_read_int_reg <= crystals_tower_1_0_4_0_read;
        crystals_tower_1_0_4_1_read_int_reg <= crystals_tower_1_0_4_1_read;
        crystals_tower_1_0_4_2_read_int_reg <= crystals_tower_1_0_4_2_read;
        crystals_tower_1_0_4_3_read_int_reg <= crystals_tower_1_0_4_3_read;
        crystals_tower_1_0_4_4_read_int_reg <= crystals_tower_1_0_4_4_read;
        crystals_tower_1_1_0_0_read_int_reg <= crystals_tower_1_1_0_0_read;
        crystals_tower_1_1_0_1_read_int_reg <= crystals_tower_1_1_0_1_read;
        crystals_tower_1_1_0_2_read_int_reg <= crystals_tower_1_1_0_2_read;
        crystals_tower_1_1_0_3_read_int_reg <= crystals_tower_1_1_0_3_read;
        crystals_tower_1_1_0_4_read_int_reg <= crystals_tower_1_1_0_4_read;
        crystals_tower_1_1_1_0_read_int_reg <= crystals_tower_1_1_1_0_read;
        crystals_tower_1_1_1_1_read_int_reg <= crystals_tower_1_1_1_1_read;
        crystals_tower_1_1_1_2_read_int_reg <= crystals_tower_1_1_1_2_read;
        crystals_tower_1_1_1_3_read_int_reg <= crystals_tower_1_1_1_3_read;
        crystals_tower_1_1_1_4_read_int_reg <= crystals_tower_1_1_1_4_read;
        crystals_tower_1_1_2_0_read_int_reg <= crystals_tower_1_1_2_0_read;
        crystals_tower_1_1_2_1_read_int_reg <= crystals_tower_1_1_2_1_read;
        crystals_tower_1_1_2_2_read_int_reg <= crystals_tower_1_1_2_2_read;
        crystals_tower_1_1_2_3_read_int_reg <= crystals_tower_1_1_2_3_read;
        crystals_tower_1_1_2_4_read_int_reg <= crystals_tower_1_1_2_4_read;
        crystals_tower_1_1_3_0_read_int_reg <= crystals_tower_1_1_3_0_read;
        crystals_tower_1_1_3_1_read_int_reg <= crystals_tower_1_1_3_1_read;
        crystals_tower_1_1_3_2_read_int_reg <= crystals_tower_1_1_3_2_read;
        crystals_tower_1_1_3_3_read_int_reg <= crystals_tower_1_1_3_3_read;
        crystals_tower_1_1_3_4_read_int_reg <= crystals_tower_1_1_3_4_read;
        crystals_tower_1_1_4_0_read_int_reg <= crystals_tower_1_1_4_0_read;
        crystals_tower_1_1_4_1_read_int_reg <= crystals_tower_1_1_4_1_read;
        crystals_tower_1_1_4_2_read_int_reg <= crystals_tower_1_1_4_2_read;
        crystals_tower_1_1_4_3_read_int_reg <= crystals_tower_1_1_4_3_read;
        crystals_tower_1_1_4_4_read_int_reg <= crystals_tower_1_1_4_4_read;
        crystals_tower_1_2_0_0_read_int_reg <= crystals_tower_1_2_0_0_read;
        crystals_tower_1_2_0_1_read_int_reg <= crystals_tower_1_2_0_1_read;
        crystals_tower_1_2_0_2_read_int_reg <= crystals_tower_1_2_0_2_read;
        crystals_tower_1_2_0_3_read_int_reg <= crystals_tower_1_2_0_3_read;
        crystals_tower_1_2_0_4_read_int_reg <= crystals_tower_1_2_0_4_read;
        crystals_tower_1_2_1_0_read_int_reg <= crystals_tower_1_2_1_0_read;
        crystals_tower_1_2_1_1_read_int_reg <= crystals_tower_1_2_1_1_read;
        crystals_tower_1_2_1_2_read_int_reg <= crystals_tower_1_2_1_2_read;
        crystals_tower_1_2_1_3_read_int_reg <= crystals_tower_1_2_1_3_read;
        crystals_tower_1_2_1_4_read_int_reg <= crystals_tower_1_2_1_4_read;
        crystals_tower_1_2_2_0_read_int_reg <= crystals_tower_1_2_2_0_read;
        crystals_tower_1_2_2_1_read_int_reg <= crystals_tower_1_2_2_1_read;
        crystals_tower_1_2_2_2_read_int_reg <= crystals_tower_1_2_2_2_read;
        crystals_tower_1_2_2_3_read_int_reg <= crystals_tower_1_2_2_3_read;
        crystals_tower_1_2_2_4_read_int_reg <= crystals_tower_1_2_2_4_read;
        crystals_tower_1_2_3_0_read_int_reg <= crystals_tower_1_2_3_0_read;
        crystals_tower_1_2_3_1_read_int_reg <= crystals_tower_1_2_3_1_read;
        crystals_tower_1_2_3_2_read_int_reg <= crystals_tower_1_2_3_2_read;
        crystals_tower_1_2_3_3_read_int_reg <= crystals_tower_1_2_3_3_read;
        crystals_tower_1_2_3_4_read_int_reg <= crystals_tower_1_2_3_4_read;
        crystals_tower_1_2_4_0_read_int_reg <= crystals_tower_1_2_4_0_read;
        crystals_tower_1_2_4_1_read_int_reg <= crystals_tower_1_2_4_1_read;
        crystals_tower_1_2_4_2_read_int_reg <= crystals_tower_1_2_4_2_read;
        crystals_tower_1_2_4_3_read_int_reg <= crystals_tower_1_2_4_3_read;
        crystals_tower_1_2_4_4_read_int_reg <= crystals_tower_1_2_4_4_read;
        crystals_tower_1_3_0_0_read_int_reg <= crystals_tower_1_3_0_0_read;
        crystals_tower_1_3_0_1_read_int_reg <= crystals_tower_1_3_0_1_read;
        crystals_tower_1_3_0_2_read_int_reg <= crystals_tower_1_3_0_2_read;
        crystals_tower_1_3_0_3_read_int_reg <= crystals_tower_1_3_0_3_read;
        crystals_tower_1_3_0_4_read_int_reg <= crystals_tower_1_3_0_4_read;
        crystals_tower_1_3_1_0_read_int_reg <= crystals_tower_1_3_1_0_read;
        crystals_tower_1_3_1_1_read_int_reg <= crystals_tower_1_3_1_1_read;
        crystals_tower_1_3_1_2_read_int_reg <= crystals_tower_1_3_1_2_read;
        crystals_tower_1_3_1_3_read_int_reg <= crystals_tower_1_3_1_3_read;
        crystals_tower_1_3_1_4_read_int_reg <= crystals_tower_1_3_1_4_read;
        crystals_tower_1_3_2_0_read_int_reg <= crystals_tower_1_3_2_0_read;
        crystals_tower_1_3_2_1_read_int_reg <= crystals_tower_1_3_2_1_read;
        crystals_tower_1_3_2_2_read_int_reg <= crystals_tower_1_3_2_2_read;
        crystals_tower_1_3_2_3_read_int_reg <= crystals_tower_1_3_2_3_read;
        crystals_tower_1_3_2_4_read_int_reg <= crystals_tower_1_3_2_4_read;
        crystals_tower_1_3_3_0_read_int_reg <= crystals_tower_1_3_3_0_read;
        crystals_tower_1_3_3_1_read_int_reg <= crystals_tower_1_3_3_1_read;
        crystals_tower_1_3_3_2_read_int_reg <= crystals_tower_1_3_3_2_read;
        crystals_tower_1_3_3_3_read_int_reg <= crystals_tower_1_3_3_3_read;
        crystals_tower_1_3_3_4_read_int_reg <= crystals_tower_1_3_3_4_read;
        crystals_tower_1_3_4_0_read_int_reg <= crystals_tower_1_3_4_0_read;
        crystals_tower_1_3_4_1_read_int_reg <= crystals_tower_1_3_4_1_read;
        crystals_tower_1_3_4_2_read_int_reg <= crystals_tower_1_3_4_2_read;
        crystals_tower_1_3_4_3_read_int_reg <= crystals_tower_1_3_4_3_read;
        crystals_tower_1_3_4_4_read_int_reg <= crystals_tower_1_3_4_4_read;
        crystals_tower_2_0_0_0_read_int_reg <= crystals_tower_2_0_0_0_read;
        crystals_tower_2_0_0_1_read_int_reg <= crystals_tower_2_0_0_1_read;
        crystals_tower_2_0_0_2_read_int_reg <= crystals_tower_2_0_0_2_read;
        crystals_tower_2_0_0_3_read_int_reg <= crystals_tower_2_0_0_3_read;
        crystals_tower_2_0_0_4_read_int_reg <= crystals_tower_2_0_0_4_read;
        crystals_tower_2_0_1_0_read_int_reg <= crystals_tower_2_0_1_0_read;
        crystals_tower_2_0_1_1_read_int_reg <= crystals_tower_2_0_1_1_read;
        crystals_tower_2_0_1_2_read_int_reg <= crystals_tower_2_0_1_2_read;
        crystals_tower_2_0_1_3_read_int_reg <= crystals_tower_2_0_1_3_read;
        crystals_tower_2_0_1_4_read_int_reg <= crystals_tower_2_0_1_4_read;
        crystals_tower_2_0_2_0_read_int_reg <= crystals_tower_2_0_2_0_read;
        crystals_tower_2_0_2_1_read_int_reg <= crystals_tower_2_0_2_1_read;
        crystals_tower_2_0_2_2_read_int_reg <= crystals_tower_2_0_2_2_read;
        crystals_tower_2_0_2_3_read_int_reg <= crystals_tower_2_0_2_3_read;
        crystals_tower_2_0_2_4_read_int_reg <= crystals_tower_2_0_2_4_read;
        crystals_tower_2_0_3_0_read_int_reg <= crystals_tower_2_0_3_0_read;
        crystals_tower_2_0_3_1_read_int_reg <= crystals_tower_2_0_3_1_read;
        crystals_tower_2_0_3_2_read_int_reg <= crystals_tower_2_0_3_2_read;
        crystals_tower_2_0_3_3_read_int_reg <= crystals_tower_2_0_3_3_read;
        crystals_tower_2_0_3_4_read_int_reg <= crystals_tower_2_0_3_4_read;
        crystals_tower_2_0_4_0_read_int_reg <= crystals_tower_2_0_4_0_read;
        crystals_tower_2_0_4_1_read_int_reg <= crystals_tower_2_0_4_1_read;
        crystals_tower_2_0_4_2_read_int_reg <= crystals_tower_2_0_4_2_read;
        crystals_tower_2_0_4_3_read_int_reg <= crystals_tower_2_0_4_3_read;
        crystals_tower_2_0_4_4_read_int_reg <= crystals_tower_2_0_4_4_read;
        crystals_tower_2_1_0_0_read_int_reg <= crystals_tower_2_1_0_0_read;
        crystals_tower_2_1_0_1_read_int_reg <= crystals_tower_2_1_0_1_read;
        crystals_tower_2_1_0_2_read_int_reg <= crystals_tower_2_1_0_2_read;
        crystals_tower_2_1_0_3_read_int_reg <= crystals_tower_2_1_0_3_read;
        crystals_tower_2_1_0_4_read_int_reg <= crystals_tower_2_1_0_4_read;
        crystals_tower_2_1_1_0_read_int_reg <= crystals_tower_2_1_1_0_read;
        crystals_tower_2_1_1_1_read_int_reg <= crystals_tower_2_1_1_1_read;
        crystals_tower_2_1_1_2_read_int_reg <= crystals_tower_2_1_1_2_read;
        crystals_tower_2_1_1_3_read_int_reg <= crystals_tower_2_1_1_3_read;
        crystals_tower_2_1_1_4_read_int_reg <= crystals_tower_2_1_1_4_read;
        crystals_tower_2_1_2_0_read_int_reg <= crystals_tower_2_1_2_0_read;
        crystals_tower_2_1_2_1_read_int_reg <= crystals_tower_2_1_2_1_read;
        crystals_tower_2_1_2_2_read_int_reg <= crystals_tower_2_1_2_2_read;
        crystals_tower_2_1_2_3_read_int_reg <= crystals_tower_2_1_2_3_read;
        crystals_tower_2_1_2_4_read_int_reg <= crystals_tower_2_1_2_4_read;
        crystals_tower_2_1_3_0_read_int_reg <= crystals_tower_2_1_3_0_read;
        crystals_tower_2_1_3_1_read_int_reg <= crystals_tower_2_1_3_1_read;
        crystals_tower_2_1_3_2_read_int_reg <= crystals_tower_2_1_3_2_read;
        crystals_tower_2_1_3_3_read_int_reg <= crystals_tower_2_1_3_3_read;
        crystals_tower_2_1_3_4_read_int_reg <= crystals_tower_2_1_3_4_read;
        crystals_tower_2_1_4_0_read_int_reg <= crystals_tower_2_1_4_0_read;
        crystals_tower_2_1_4_1_read_int_reg <= crystals_tower_2_1_4_1_read;
        crystals_tower_2_1_4_2_read_int_reg <= crystals_tower_2_1_4_2_read;
        crystals_tower_2_1_4_3_read_int_reg <= crystals_tower_2_1_4_3_read;
        crystals_tower_2_1_4_4_read_int_reg <= crystals_tower_2_1_4_4_read;
        crystals_tower_2_2_0_0_read_int_reg <= crystals_tower_2_2_0_0_read;
        crystals_tower_2_2_0_1_read_int_reg <= crystals_tower_2_2_0_1_read;
        crystals_tower_2_2_0_2_read_int_reg <= crystals_tower_2_2_0_2_read;
        crystals_tower_2_2_0_3_read_int_reg <= crystals_tower_2_2_0_3_read;
        crystals_tower_2_2_0_4_read_int_reg <= crystals_tower_2_2_0_4_read;
        crystals_tower_2_2_1_0_read_int_reg <= crystals_tower_2_2_1_0_read;
        crystals_tower_2_2_1_1_read_int_reg <= crystals_tower_2_2_1_1_read;
        crystals_tower_2_2_1_2_read_int_reg <= crystals_tower_2_2_1_2_read;
        crystals_tower_2_2_1_3_read_int_reg <= crystals_tower_2_2_1_3_read;
        crystals_tower_2_2_1_4_read_int_reg <= crystals_tower_2_2_1_4_read;
        crystals_tower_2_2_2_0_read_int_reg <= crystals_tower_2_2_2_0_read;
        crystals_tower_2_2_2_1_read_int_reg <= crystals_tower_2_2_2_1_read;
        crystals_tower_2_2_2_2_read_int_reg <= crystals_tower_2_2_2_2_read;
        crystals_tower_2_2_2_3_read_int_reg <= crystals_tower_2_2_2_3_read;
        crystals_tower_2_2_2_4_read_int_reg <= crystals_tower_2_2_2_4_read;
        crystals_tower_2_2_3_0_read_int_reg <= crystals_tower_2_2_3_0_read;
        crystals_tower_2_2_3_1_read_int_reg <= crystals_tower_2_2_3_1_read;
        crystals_tower_2_2_3_2_read_int_reg <= crystals_tower_2_2_3_2_read;
        crystals_tower_2_2_3_3_read_int_reg <= crystals_tower_2_2_3_3_read;
        crystals_tower_2_2_3_4_read_int_reg <= crystals_tower_2_2_3_4_read;
        crystals_tower_2_2_4_0_read_int_reg <= crystals_tower_2_2_4_0_read;
        crystals_tower_2_2_4_1_read_int_reg <= crystals_tower_2_2_4_1_read;
        crystals_tower_2_2_4_2_read_int_reg <= crystals_tower_2_2_4_2_read;
        crystals_tower_2_2_4_3_read_int_reg <= crystals_tower_2_2_4_3_read;
        crystals_tower_2_2_4_4_read_int_reg <= crystals_tower_2_2_4_4_read;
        crystals_tower_2_3_0_0_read_int_reg <= crystals_tower_2_3_0_0_read;
        crystals_tower_2_3_0_1_read_int_reg <= crystals_tower_2_3_0_1_read;
        crystals_tower_2_3_0_2_read_int_reg <= crystals_tower_2_3_0_2_read;
        crystals_tower_2_3_0_3_read_int_reg <= crystals_tower_2_3_0_3_read;
        crystals_tower_2_3_0_4_read_int_reg <= crystals_tower_2_3_0_4_read;
        crystals_tower_2_3_1_0_read_int_reg <= crystals_tower_2_3_1_0_read;
        crystals_tower_2_3_1_1_read_int_reg <= crystals_tower_2_3_1_1_read;
        crystals_tower_2_3_1_2_read_int_reg <= crystals_tower_2_3_1_2_read;
        crystals_tower_2_3_1_3_read_int_reg <= crystals_tower_2_3_1_3_read;
        crystals_tower_2_3_1_4_read_int_reg <= crystals_tower_2_3_1_4_read;
        crystals_tower_2_3_2_0_read_int_reg <= crystals_tower_2_3_2_0_read;
        crystals_tower_2_3_2_1_read_int_reg <= crystals_tower_2_3_2_1_read;
        crystals_tower_2_3_2_2_read_int_reg <= crystals_tower_2_3_2_2_read;
        crystals_tower_2_3_2_3_read_int_reg <= crystals_tower_2_3_2_3_read;
        crystals_tower_2_3_2_4_read_int_reg <= crystals_tower_2_3_2_4_read;
        crystals_tower_2_3_3_0_read_int_reg <= crystals_tower_2_3_3_0_read;
        crystals_tower_2_3_3_1_read_int_reg <= crystals_tower_2_3_3_1_read;
        crystals_tower_2_3_3_2_read_int_reg <= crystals_tower_2_3_3_2_read;
        crystals_tower_2_3_3_3_read_int_reg <= crystals_tower_2_3_3_3_read;
        crystals_tower_2_3_3_4_read_int_reg <= crystals_tower_2_3_3_4_read;
        crystals_tower_2_3_4_0_read_int_reg <= crystals_tower_2_3_4_0_read;
        crystals_tower_2_3_4_1_read_int_reg <= crystals_tower_2_3_4_1_read;
        crystals_tower_2_3_4_2_read_int_reg <= crystals_tower_2_3_4_2_read;
        crystals_tower_2_3_4_3_read_int_reg <= crystals_tower_2_3_4_3_read;
        crystals_tower_2_3_4_4_read_int_reg <= crystals_tower_2_3_4_4_read;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_getClustersInTower_fu_2412_ap_ce = 1'b1;
    end else begin
        grp_getClustersInTower_fu_2412_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_getClustersInTower_fu_2466_ap_ce = 1'b1;
    end else begin
        grp_getClustersInTower_fu_2466_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_getClustersInTower_fu_2520_ap_ce = 1'b1;
    end else begin
        grp_getClustersInTower_fu_2520_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_getClustersInTower_fu_2574_ap_ce = 1'b1;
    end else begin
        grp_getClustersInTower_fu_2574_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_getClustersInTower_fu_2628_ap_ce = 1'b1;
    end else begin
        grp_getClustersInTower_fu_2628_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_getClustersInTower_fu_2682_ap_ce = 1'b1;
    end else begin
        grp_getClustersInTower_fu_2682_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_getClustersInTower_fu_2736_ap_ce = 1'b1;
    end else begin
        grp_getClustersInTower_fu_2736_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_getClustersInTower_fu_2790_ap_ce = 1'b1;
    end else begin
        grp_getClustersInTower_fu_2790_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_getClustersInTower_fu_2844_ap_ce = 1'b1;
    end else begin
        grp_getClustersInTower_fu_2844_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_getClustersInTower_fu_2898_ap_ce = 1'b1;
    end else begin
        grp_getClustersInTower_fu_2898_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_getClustersInTower_fu_2952_ap_ce = 1'b1;
    end else begin
        grp_getClustersInTower_fu_2952_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_getClustersInTower_fu_3006_ap_ce = 1'b1;
    end else begin
        grp_getClustersInTower_fu_3006_ap_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

endmodule //getClustersin3x4Regi
