// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _getClustersInTower_HH_
#define _getClustersInTower_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "getPeakBinOf5.h"
#include "algo_unpacked_muxbkb.h"

namespace ap_rtl {

struct getClustersInTower : public sc_module {
    // Port declarations 28
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<16> > crystals_0_0_read;
    sc_in< sc_lv<16> > crystals_0_1_read;
    sc_in< sc_lv<16> > crystals_0_2_read;
    sc_in< sc_lv<16> > crystals_0_3_read;
    sc_in< sc_lv<16> > crystals_0_4_read;
    sc_in< sc_lv<16> > crystals_1_0_read;
    sc_in< sc_lv<16> > crystals_1_1_read;
    sc_in< sc_lv<16> > crystals_1_2_read;
    sc_in< sc_lv<16> > crystals_1_3_read;
    sc_in< sc_lv<16> > crystals_1_4_read;
    sc_in< sc_lv<16> > crystals_2_0_read;
    sc_in< sc_lv<16> > crystals_2_1_read;
    sc_in< sc_lv<16> > crystals_2_2_read;
    sc_in< sc_lv<16> > crystals_2_3_read;
    sc_in< sc_lv<16> > crystals_2_4_read;
    sc_in< sc_lv<16> > crystals_3_0_read;
    sc_in< sc_lv<16> > crystals_3_1_read;
    sc_in< sc_lv<16> > crystals_3_2_read;
    sc_in< sc_lv<16> > crystals_3_3_read;
    sc_in< sc_lv<16> > crystals_3_4_read;
    sc_in< sc_lv<16> > crystals_4_0_read;
    sc_in< sc_lv<16> > crystals_4_1_read;
    sc_in< sc_lv<16> > crystals_4_2_read;
    sc_in< sc_lv<16> > crystals_4_3_read;
    sc_in< sc_lv<16> > crystals_4_4_read;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    getClustersInTower(sc_module_name name);
    SC_HAS_PROCESS(getClustersInTower);

    ~getClustersInTower();

    sc_trace_file* mVcdFile;

    getPeakBinOf5* grp_getPeakBinOf5_fu_216;
    getPeakBinOf5* grp_getPeakBinOf5_fu_226;
    algo_unpacked_muxbkb<1,1,16,16,16,16,16,3,16>* algo_unpacked_muxbkb_U7;
    algo_unpacked_muxbkb<1,1,16,16,16,16,16,3,16>* algo_unpacked_muxbkb_U8;
    sc_signal< sc_lv<16> > phiStripSum_0_fu_254_p2;
    sc_signal< sc_lv<16> > phiStripSum_0_reg_523;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<16> > phiStripSum_0_reg_523_pp0_iter1_reg;
    sc_signal< sc_lv<16> > phiStripSum_1_fu_278_p2;
    sc_signal< sc_lv<16> > phiStripSum_1_reg_529;
    sc_signal< sc_lv<16> > phiStripSum_1_reg_529_pp0_iter1_reg;
    sc_signal< sc_lv<16> > phiStripSum_2_fu_302_p2;
    sc_signal< sc_lv<16> > phiStripSum_2_reg_535;
    sc_signal< sc_lv<16> > phiStripSum_2_reg_535_pp0_iter1_reg;
    sc_signal< sc_lv<16> > phiStripSum_3_fu_326_p2;
    sc_signal< sc_lv<16> > phiStripSum_3_reg_541;
    sc_signal< sc_lv<16> > phiStripSum_3_reg_541_pp0_iter1_reg;
    sc_signal< sc_lv<16> > phiStripSum_4_fu_350_p2;
    sc_signal< sc_lv<16> > phiStripSum_4_reg_547;
    sc_signal< sc_lv<16> > phiStripSum_4_reg_547_pp0_iter1_reg;
    sc_signal< sc_lv<16> > etaStripSum_0_fu_374_p2;
    sc_signal< sc_lv<16> > etaStripSum_0_reg_553;
    sc_signal< sc_lv<16> > etaStripSum_0_reg_553_pp0_iter1_reg;
    sc_signal< sc_lv<16> > etaStripSum_0_reg_553_pp0_iter2_reg;
    sc_signal< sc_lv<16> > etaStripSum_1_fu_398_p2;
    sc_signal< sc_lv<16> > etaStripSum_1_reg_560;
    sc_signal< sc_lv<16> > etaStripSum_1_reg_560_pp0_iter1_reg;
    sc_signal< sc_lv<16> > etaStripSum_1_reg_560_pp0_iter2_reg;
    sc_signal< sc_lv<16> > etaStripSum_2_fu_422_p2;
    sc_signal< sc_lv<16> > etaStripSum_2_reg_567;
    sc_signal< sc_lv<16> > etaStripSum_2_reg_567_pp0_iter1_reg;
    sc_signal< sc_lv<16> > etaStripSum_2_reg_567_pp0_iter2_reg;
    sc_signal< sc_lv<16> > etaStripSum_3_fu_446_p2;
    sc_signal< sc_lv<16> > etaStripSum_3_reg_574;
    sc_signal< sc_lv<16> > etaStripSum_3_reg_574_pp0_iter1_reg;
    sc_signal< sc_lv<16> > etaStripSum_3_reg_574_pp0_iter2_reg;
    sc_signal< sc_lv<16> > etaStripSum_4_fu_470_p2;
    sc_signal< sc_lv<16> > etaStripSum_4_reg_581;
    sc_signal< sc_lv<16> > etaStripSum_4_reg_581_pp0_iter1_reg;
    sc_signal< sc_lv<16> > etaStripSum_4_reg_581_pp0_iter2_reg;
    sc_signal< sc_lv<16> > tmp_43_4_fu_489_p2;
    sc_signal< sc_lv<16> > tmp_43_4_reg_588;
    sc_signal< sc_lv<3> > grp_getPeakBinOf5_fu_216_ap_return;
    sc_signal< sc_logic > grp_getPeakBinOf5_fu_216_ap_ce;
    sc_signal< sc_lv<3> > grp_getPeakBinOf5_fu_226_ap_return;
    sc_signal< sc_logic > grp_getPeakBinOf5_fu_226_ap_ce;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<16> > tmp5_fu_242_p2;
    sc_signal< sc_lv<16> > tmp6_fu_248_p2;
    sc_signal< sc_lv<16> > tmp_fu_236_p2;
    sc_signal< sc_lv<16> > tmp8_fu_266_p2;
    sc_signal< sc_lv<16> > tmp9_fu_272_p2;
    sc_signal< sc_lv<16> > tmp7_fu_260_p2;
    sc_signal< sc_lv<16> > tmp11_fu_290_p2;
    sc_signal< sc_lv<16> > tmp12_fu_296_p2;
    sc_signal< sc_lv<16> > tmp10_fu_284_p2;
    sc_signal< sc_lv<16> > tmp14_fu_314_p2;
    sc_signal< sc_lv<16> > tmp15_fu_320_p2;
    sc_signal< sc_lv<16> > tmp13_fu_308_p2;
    sc_signal< sc_lv<16> > tmp17_fu_338_p2;
    sc_signal< sc_lv<16> > tmp18_fu_344_p2;
    sc_signal< sc_lv<16> > tmp16_fu_332_p2;
    sc_signal< sc_lv<16> > tmp20_fu_362_p2;
    sc_signal< sc_lv<16> > tmp21_fu_368_p2;
    sc_signal< sc_lv<16> > tmp19_fu_356_p2;
    sc_signal< sc_lv<16> > tmp23_fu_386_p2;
    sc_signal< sc_lv<16> > tmp24_fu_392_p2;
    sc_signal< sc_lv<16> > tmp22_fu_380_p2;
    sc_signal< sc_lv<16> > tmp26_fu_410_p2;
    sc_signal< sc_lv<16> > tmp27_fu_416_p2;
    sc_signal< sc_lv<16> > tmp25_fu_404_p2;
    sc_signal< sc_lv<16> > tmp29_fu_434_p2;
    sc_signal< sc_lv<16> > tmp30_fu_440_p2;
    sc_signal< sc_lv<16> > tmp28_fu_428_p2;
    sc_signal< sc_lv<16> > tmp32_fu_458_p2;
    sc_signal< sc_lv<16> > tmp33_fu_464_p2;
    sc_signal< sc_lv<16> > tmp31_fu_452_p2;
    sc_signal< sc_lv<16> > tmp35_fu_480_p2;
    sc_signal< sc_lv<16> > tmp36_fu_484_p2;
    sc_signal< sc_lv<16> > tmp34_fu_476_p2;
    sc_signal< sc_lv<3> > empty_fu_501_p6;
    sc_signal< sc_lv<16> > empty_fu_501_p7;
    sc_signal< sc_lv<16> > empty_9_fu_512_p7;
    sc_signal< sc_logic > ap_ce_reg;
    sc_signal< sc_lv<16> > crystals_0_0_read_int_reg;
    sc_signal< sc_lv<16> > crystals_0_1_read_int_reg;
    sc_signal< sc_lv<16> > crystals_0_2_read_int_reg;
    sc_signal< sc_lv<16> > crystals_0_3_read_int_reg;
    sc_signal< sc_lv<16> > crystals_0_4_read_int_reg;
    sc_signal< sc_lv<16> > crystals_1_0_read_int_reg;
    sc_signal< sc_lv<16> > crystals_1_1_read_int_reg;
    sc_signal< sc_lv<16> > crystals_1_2_read_int_reg;
    sc_signal< sc_lv<16> > crystals_1_3_read_int_reg;
    sc_signal< sc_lv<16> > crystals_1_4_read_int_reg;
    sc_signal< sc_lv<16> > crystals_2_0_read_int_reg;
    sc_signal< sc_lv<16> > crystals_2_1_read_int_reg;
    sc_signal< sc_lv<16> > crystals_2_2_read_int_reg;
    sc_signal< sc_lv<16> > crystals_2_3_read_int_reg;
    sc_signal< sc_lv<16> > crystals_2_4_read_int_reg;
    sc_signal< sc_lv<16> > crystals_3_0_read_int_reg;
    sc_signal< sc_lv<16> > crystals_3_1_read_int_reg;
    sc_signal< sc_lv<16> > crystals_3_2_read_int_reg;
    sc_signal< sc_lv<16> > crystals_3_3_read_int_reg;
    sc_signal< sc_lv<16> > crystals_3_4_read_int_reg;
    sc_signal< sc_lv<16> > crystals_4_0_read_int_reg;
    sc_signal< sc_lv<16> > crystals_4_1_read_int_reg;
    sc_signal< sc_lv<16> > crystals_4_2_read_int_reg;
    sc_signal< sc_lv<16> > crystals_4_3_read_int_reg;
    sc_signal< sc_lv<16> > crystals_4_4_read_int_reg;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<3> ap_const_lv3_7;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_block_state3_pp0_stage0_iter2();
    void thread_ap_block_state4_pp0_stage0_iter3();
    void thread_empty_fu_501_p6();
    void thread_etaStripSum_0_fu_374_p2();
    void thread_etaStripSum_1_fu_398_p2();
    void thread_etaStripSum_2_fu_422_p2();
    void thread_etaStripSum_3_fu_446_p2();
    void thread_etaStripSum_4_fu_470_p2();
    void thread_grp_getPeakBinOf5_fu_216_ap_ce();
    void thread_grp_getPeakBinOf5_fu_226_ap_ce();
    void thread_phiStripSum_0_fu_254_p2();
    void thread_phiStripSum_1_fu_278_p2();
    void thread_phiStripSum_2_fu_302_p2();
    void thread_phiStripSum_3_fu_326_p2();
    void thread_phiStripSum_4_fu_350_p2();
    void thread_tmp10_fu_284_p2();
    void thread_tmp11_fu_290_p2();
    void thread_tmp12_fu_296_p2();
    void thread_tmp13_fu_308_p2();
    void thread_tmp14_fu_314_p2();
    void thread_tmp15_fu_320_p2();
    void thread_tmp16_fu_332_p2();
    void thread_tmp17_fu_338_p2();
    void thread_tmp18_fu_344_p2();
    void thread_tmp19_fu_356_p2();
    void thread_tmp20_fu_362_p2();
    void thread_tmp21_fu_368_p2();
    void thread_tmp22_fu_380_p2();
    void thread_tmp23_fu_386_p2();
    void thread_tmp24_fu_392_p2();
    void thread_tmp25_fu_404_p2();
    void thread_tmp26_fu_410_p2();
    void thread_tmp27_fu_416_p2();
    void thread_tmp28_fu_428_p2();
    void thread_tmp29_fu_434_p2();
    void thread_tmp30_fu_440_p2();
    void thread_tmp31_fu_452_p2();
    void thread_tmp32_fu_458_p2();
    void thread_tmp33_fu_464_p2();
    void thread_tmp34_fu_476_p2();
    void thread_tmp35_fu_480_p2();
    void thread_tmp36_fu_484_p2();
    void thread_tmp5_fu_242_p2();
    void thread_tmp6_fu_248_p2();
    void thread_tmp7_fu_260_p2();
    void thread_tmp8_fu_266_p2();
    void thread_tmp9_fu_272_p2();
    void thread_tmp_43_4_fu_489_p2();
    void thread_tmp_fu_236_p2();
};

}

using namespace ap_rtl;

#endif
