// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "getPeakBinOf5.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic getPeakBinOf5::ap_const_logic_1 = sc_dt::Log_1;
const bool getPeakBinOf5::ap_const_boolean_1 = true;
const bool getPeakBinOf5::ap_const_boolean_0 = false;
const sc_lv<32> getPeakBinOf5::ap_const_lv32_1 = "1";
const sc_lv<32> getPeakBinOf5::ap_const_lv32_F = "1111";
const sc_lv<16> getPeakBinOf5::ap_const_lv16_1 = "1";
const sc_lv<2> getPeakBinOf5::ap_const_lv2_0 = "00";
const sc_lv<1> getPeakBinOf5::ap_const_lv1_0 = "0";
const sc_lv<3> getPeakBinOf5::ap_const_lv3_4 = "100";
const sc_lv<3> getPeakBinOf5::ap_const_lv3_3 = "11";
const sc_lv<3> getPeakBinOf5::ap_const_lv3_2 = "10";
const sc_lv<3> getPeakBinOf5::ap_const_lv3_0 = "000";
const sc_lv<1> getPeakBinOf5::ap_const_lv1_1 = "1";
const sc_lv<3> getPeakBinOf5::ap_const_lv3_1 = "1";
const sc_logic getPeakBinOf5::ap_const_logic_0 = sc_dt::Log_0;

getPeakBinOf5::getPeakBinOf5(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1);

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( sel_tmp6_fu_323_p2 );
    sensitive << ( sel_tmp4_fu_309_p3 );

    SC_METHOD(thread_iAve_fu_281_p3);
    sensitive << ( tmp_15_fu_275_p2 );

    SC_METHOD(thread_iEtSum_fu_220_p2);
    sensitive << ( tmp_6_fu_208_p2 );
    sensitive << ( tmp3_fu_214_p2 );

    SC_METHOD(thread_sel_tmp1_fu_295_p2);
    sensitive << ( tmp4_fu_289_p2 );
    sensitive << ( tmp_7_fu_226_p2 );

    SC_METHOD(thread_sel_tmp2_fu_301_p3);
    sensitive << ( sel_tmp1_fu_295_p2 );
    sensitive << ( iAve_fu_281_p3 );

    SC_METHOD(thread_sel_tmp4_fu_309_p3);
    sensitive << ( tmp_7_fu_226_p2 );
    sensitive << ( sel_tmp2_fu_301_p3 );

    SC_METHOD(thread_sel_tmp5_fu_317_p2);
    sensitive << ( tmp_11_fu_250_p2 );

    SC_METHOD(thread_sel_tmp6_fu_323_p2);
    sensitive << ( tmp_7_fu_226_p2 );
    sensitive << ( sel_tmp5_fu_317_p2 );

    SC_METHOD(thread_tmp1_fu_162_p3);
    sensitive << ( tmp5_fu_156_p2 );

    SC_METHOD(thread_tmp2_fu_190_p2);
    sensitive << ( tmp_fu_128_p2 );
    sensitive << ( tmp_16_fu_124_p1 );

    SC_METHOD(thread_tmp3_fu_214_p2);
    sensitive << ( tmp1_fu_162_p3 );
    sensitive << ( tmp_20_fu_180_p1 );

    SC_METHOD(thread_tmp4_fu_289_p2);
    sensitive << ( tmp_11_fu_250_p2 );
    sensitive << ( tmp_13_fu_262_p2 );

    SC_METHOD(thread_tmp5_fu_156_p2);
    sensitive << ( tmp_18_fu_148_p1 );
    sensitive << ( tmp_19_fu_152_p1 );

    SC_METHOD(thread_tmp8_fu_184_p2);
    sensitive << ( et_1_read );
    sensitive << ( tmp_2_fu_96_p1 );

    SC_METHOD(thread_tmp9_fu_196_p2);
    sensitive << ( tmp_5_fu_110_p1 );
    sensitive << ( tmp2_fu_190_p2 );

    SC_METHOD(thread_tmp_10_fu_239_p3);
    sensitive << ( etSum_read_reg_337 );

    SC_METHOD(thread_tmp_11_fu_250_p2);
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_10_fu_239_p3 );
    sensitive << ( tmp_13_cast_fu_233_p1 );

    SC_METHOD(thread_tmp_12_fu_256_p2);
    sensitive << ( tmp_14_cast1_fu_236_p1 );
    sensitive << ( tmp_15_cast_fu_246_p1 );

    SC_METHOD(thread_tmp_13_cast1_fu_230_p1);
    sensitive << ( iEtSum_reg_345 );

    SC_METHOD(thread_tmp_13_cast_fu_233_p1);
    sensitive << ( iEtSum_reg_345 );

    SC_METHOD(thread_tmp_13_fu_262_p2);
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_13_cast1_fu_230_p1 );
    sensitive << ( tmp_12_fu_256_p2 );

    SC_METHOD(thread_tmp_14_cast1_fu_236_p1);
    sensitive << ( etSum_read_reg_337 );

    SC_METHOD(thread_tmp_14_fu_268_p3);
    sensitive << ( etSum_read_reg_337 );

    SC_METHOD(thread_tmp_15_cast_fu_246_p1);
    sensitive << ( tmp_10_fu_239_p3 );

    SC_METHOD(thread_tmp_15_fu_275_p2);
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_13_cast1_fu_230_p1 );
    sensitive << ( tmp_14_fu_268_p3 );

    SC_METHOD(thread_tmp_16_fu_124_p1);
    sensitive << ( tmp_1_fu_114_p4 );

    SC_METHOD(thread_tmp_17_fu_144_p1);
    sensitive << ( tmp_3_fu_134_p4 );

    SC_METHOD(thread_tmp_18_fu_148_p1);
    sensitive << ( et_4_read );

    SC_METHOD(thread_tmp_19_fu_152_p1);
    sensitive << ( et_3_read );

    SC_METHOD(thread_tmp_1_fu_114_p4);
    sensitive << ( et_2_read );

    SC_METHOD(thread_tmp_20_fu_180_p1);
    sensitive << ( tmp_4_fu_170_p4 );

    SC_METHOD(thread_tmp_2_fu_96_p1);
    sensitive << ( tmp_9_fu_86_p4 );

    SC_METHOD(thread_tmp_3_fu_134_p4);
    sensitive << ( et_3_read );

    SC_METHOD(thread_tmp_4_fu_170_p4);
    sensitive << ( et_4_read );

    SC_METHOD(thread_tmp_5_fu_110_p1);
    sensitive << ( tmp_s_fu_100_p4 );

    SC_METHOD(thread_tmp_6_fu_208_p2);
    sensitive << ( tmp_8_fu_202_p2 );
    sensitive << ( tmp_17_fu_144_p1 );

    SC_METHOD(thread_tmp_7_fu_226_p2);
    sensitive << ( etSum_read_reg_337 );
    sensitive << ( ap_ce );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( iEtSum_reg_345 );

    SC_METHOD(thread_tmp_8_fu_202_p2);
    sensitive << ( tmp8_fu_184_p2 );
    sensitive << ( tmp9_fu_196_p2 );

    SC_METHOD(thread_tmp_9_fu_86_p4);
    sensitive << ( et_0_read );

    SC_METHOD(thread_tmp_fu_128_p2);
    sensitive << ( et_2_read );

    SC_METHOD(thread_tmp_s_fu_100_p4);
    sensitive << ( et_1_read );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "getPeakBinOf5_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, et_0_read, "(port)et_0_read");
    sc_trace(mVcdFile, et_1_read, "(port)et_1_read");
    sc_trace(mVcdFile, et_2_read, "(port)et_2_read");
    sc_trace(mVcdFile, et_3_read, "(port)et_3_read");
    sc_trace(mVcdFile, et_4_read, "(port)et_4_read");
    sc_trace(mVcdFile, etSum, "(port)etSum");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, etSum_read_reg_337, "etSum_read_reg_337");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0, "ap_block_state1_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1, "ap_block_state2_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, iEtSum_fu_220_p2, "iEtSum_fu_220_p2");
    sc_trace(mVcdFile, iEtSum_reg_345, "iEtSum_reg_345");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_9_fu_86_p4, "tmp_9_fu_86_p4");
    sc_trace(mVcdFile, tmp_s_fu_100_p4, "tmp_s_fu_100_p4");
    sc_trace(mVcdFile, tmp_1_fu_114_p4, "tmp_1_fu_114_p4");
    sc_trace(mVcdFile, tmp_3_fu_134_p4, "tmp_3_fu_134_p4");
    sc_trace(mVcdFile, tmp_18_fu_148_p1, "tmp_18_fu_148_p1");
    sc_trace(mVcdFile, tmp_19_fu_152_p1, "tmp_19_fu_152_p1");
    sc_trace(mVcdFile, tmp5_fu_156_p2, "tmp5_fu_156_p2");
    sc_trace(mVcdFile, tmp_4_fu_170_p4, "tmp_4_fu_170_p4");
    sc_trace(mVcdFile, tmp_2_fu_96_p1, "tmp_2_fu_96_p1");
    sc_trace(mVcdFile, tmp_fu_128_p2, "tmp_fu_128_p2");
    sc_trace(mVcdFile, tmp_16_fu_124_p1, "tmp_16_fu_124_p1");
    sc_trace(mVcdFile, tmp_5_fu_110_p1, "tmp_5_fu_110_p1");
    sc_trace(mVcdFile, tmp2_fu_190_p2, "tmp2_fu_190_p2");
    sc_trace(mVcdFile, tmp8_fu_184_p2, "tmp8_fu_184_p2");
    sc_trace(mVcdFile, tmp9_fu_196_p2, "tmp9_fu_196_p2");
    sc_trace(mVcdFile, tmp_8_fu_202_p2, "tmp_8_fu_202_p2");
    sc_trace(mVcdFile, tmp_17_fu_144_p1, "tmp_17_fu_144_p1");
    sc_trace(mVcdFile, tmp1_fu_162_p3, "tmp1_fu_162_p3");
    sc_trace(mVcdFile, tmp_20_fu_180_p1, "tmp_20_fu_180_p1");
    sc_trace(mVcdFile, tmp_6_fu_208_p2, "tmp_6_fu_208_p2");
    sc_trace(mVcdFile, tmp3_fu_214_p2, "tmp3_fu_214_p2");
    sc_trace(mVcdFile, tmp_10_fu_239_p3, "tmp_10_fu_239_p3");
    sc_trace(mVcdFile, tmp_13_cast_fu_233_p1, "tmp_13_cast_fu_233_p1");
    sc_trace(mVcdFile, tmp_14_cast1_fu_236_p1, "tmp_14_cast1_fu_236_p1");
    sc_trace(mVcdFile, tmp_15_cast_fu_246_p1, "tmp_15_cast_fu_246_p1");
    sc_trace(mVcdFile, tmp_13_cast1_fu_230_p1, "tmp_13_cast1_fu_230_p1");
    sc_trace(mVcdFile, tmp_12_fu_256_p2, "tmp_12_fu_256_p2");
    sc_trace(mVcdFile, tmp_14_fu_268_p3, "tmp_14_fu_268_p3");
    sc_trace(mVcdFile, tmp_15_fu_275_p2, "tmp_15_fu_275_p2");
    sc_trace(mVcdFile, tmp_11_fu_250_p2, "tmp_11_fu_250_p2");
    sc_trace(mVcdFile, tmp_13_fu_262_p2, "tmp_13_fu_262_p2");
    sc_trace(mVcdFile, tmp4_fu_289_p2, "tmp4_fu_289_p2");
    sc_trace(mVcdFile, tmp_7_fu_226_p2, "tmp_7_fu_226_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_295_p2, "sel_tmp1_fu_295_p2");
    sc_trace(mVcdFile, iAve_fu_281_p3, "iAve_fu_281_p3");
    sc_trace(mVcdFile, sel_tmp2_fu_301_p3, "sel_tmp2_fu_301_p3");
    sc_trace(mVcdFile, sel_tmp5_fu_317_p2, "sel_tmp5_fu_317_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_323_p2, "sel_tmp6_fu_323_p2");
    sc_trace(mVcdFile, sel_tmp4_fu_309_p3, "sel_tmp4_fu_309_p3");
#endif

    }
}

getPeakBinOf5::~getPeakBinOf5() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void getPeakBinOf5::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        etSum_read_reg_337 = etSum.read();
        iEtSum_reg_345 = iEtSum_fu_220_p2.read();
    }
}

void getPeakBinOf5::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void getPeakBinOf5::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void getPeakBinOf5::thread_ap_block_state1_pp0_stage0_iter0() {
    ap_block_state1_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void getPeakBinOf5::thread_ap_block_state2_pp0_stage0_iter1() {
    ap_block_state2_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void getPeakBinOf5::thread_ap_return() {
    ap_return = (!sel_tmp6_fu_323_p2.read()[0].is_01())? sc_lv<3>(): ((sel_tmp6_fu_323_p2.read()[0].to_bool())? ap_const_lv3_1: sel_tmp4_fu_309_p3.read());
}

void getPeakBinOf5::thread_iAve_fu_281_p3() {
    iAve_fu_281_p3 = (!tmp_15_fu_275_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_15_fu_275_p2.read()[0].to_bool())? ap_const_lv3_4: ap_const_lv3_3);
}

void getPeakBinOf5::thread_iEtSum_fu_220_p2() {
    iEtSum_fu_220_p2 = (!tmp_6_fu_208_p2.read().is_01() || !tmp3_fu_214_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_6_fu_208_p2.read()) + sc_biguint<16>(tmp3_fu_214_p2.read()));
}

void getPeakBinOf5::thread_sel_tmp1_fu_295_p2() {
    sel_tmp1_fu_295_p2 = (tmp4_fu_289_p2.read() & tmp_7_fu_226_p2.read());
}

void getPeakBinOf5::thread_sel_tmp2_fu_301_p3() {
    sel_tmp2_fu_301_p3 = (!sel_tmp1_fu_295_p2.read()[0].is_01())? sc_lv<3>(): ((sel_tmp1_fu_295_p2.read()[0].to_bool())? iAve_fu_281_p3.read(): ap_const_lv3_2);
}

void getPeakBinOf5::thread_sel_tmp4_fu_309_p3() {
    sel_tmp4_fu_309_p3 = (!tmp_7_fu_226_p2.read()[0].is_01())? sc_lv<3>(): ((tmp_7_fu_226_p2.read()[0].to_bool())? sel_tmp2_fu_301_p3.read(): ap_const_lv3_0);
}

void getPeakBinOf5::thread_sel_tmp5_fu_317_p2() {
    sel_tmp5_fu_317_p2 = (tmp_11_fu_250_p2.read() ^ ap_const_lv1_1);
}

void getPeakBinOf5::thread_sel_tmp6_fu_323_p2() {
    sel_tmp6_fu_323_p2 = (tmp_7_fu_226_p2.read() & sel_tmp5_fu_317_p2.read());
}

void getPeakBinOf5::thread_tmp1_fu_162_p3() {
    tmp1_fu_162_p3 = esl_concat<14,2>(tmp5_fu_156_p2.read(), ap_const_lv2_0);
}

void getPeakBinOf5::thread_tmp2_fu_190_p2() {
    tmp2_fu_190_p2 = (!tmp_fu_128_p2.read().is_01() || !tmp_16_fu_124_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_fu_128_p2.read()) + sc_biguint<16>(tmp_16_fu_124_p1.read()));
}

void getPeakBinOf5::thread_tmp3_fu_214_p2() {
    tmp3_fu_214_p2 = (!tmp1_fu_162_p3.read().is_01() || !tmp_20_fu_180_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp1_fu_162_p3.read()) + sc_biguint<16>(tmp_20_fu_180_p1.read()));
}

void getPeakBinOf5::thread_tmp4_fu_289_p2() {
    tmp4_fu_289_p2 = (tmp_11_fu_250_p2.read() & tmp_13_fu_262_p2.read());
}

void getPeakBinOf5::thread_tmp5_fu_156_p2() {
    tmp5_fu_156_p2 = (!tmp_18_fu_148_p1.read().is_01() || !tmp_19_fu_152_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(tmp_18_fu_148_p1.read()) + sc_biguint<14>(tmp_19_fu_152_p1.read()));
}

void getPeakBinOf5::thread_tmp8_fu_184_p2() {
    tmp8_fu_184_p2 = (!tmp_2_fu_96_p1.read().is_01() || !et_1_read.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_2_fu_96_p1.read()) + sc_biguint<16>(et_1_read.read()));
}

void getPeakBinOf5::thread_tmp9_fu_196_p2() {
    tmp9_fu_196_p2 = (!tmp_5_fu_110_p1.read().is_01() || !tmp2_fu_190_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_5_fu_110_p1.read()) + sc_biguint<16>(tmp2_fu_190_p2.read()));
}

void getPeakBinOf5::thread_tmp_10_fu_239_p3() {
    tmp_10_fu_239_p3 = esl_concat<16,1>(etSum_read_reg_337.read(), ap_const_lv1_0);
}

void getPeakBinOf5::thread_tmp_11_fu_250_p2() {
    tmp_11_fu_250_p2 = (!tmp_13_cast_fu_233_p1.read().is_01() || !tmp_10_fu_239_p3.read().is_01())? sc_lv<1>(): (sc_biguint<17>(tmp_13_cast_fu_233_p1.read()) > sc_biguint<17>(tmp_10_fu_239_p3.read()));
}

void getPeakBinOf5::thread_tmp_12_fu_256_p2() {
    tmp_12_fu_256_p2 = (!tmp_14_cast1_fu_236_p1.read().is_01() || !tmp_15_cast_fu_246_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp_14_cast1_fu_236_p1.read()) + sc_biguint<18>(tmp_15_cast_fu_246_p1.read()));
}

void getPeakBinOf5::thread_tmp_13_cast1_fu_230_p1() {
    tmp_13_cast1_fu_230_p1 = esl_zext<18,16>(iEtSum_reg_345.read());
}

void getPeakBinOf5::thread_tmp_13_cast_fu_233_p1() {
    tmp_13_cast_fu_233_p1 = esl_zext<17,16>(iEtSum_reg_345.read());
}

void getPeakBinOf5::thread_tmp_13_fu_262_p2() {
    tmp_13_fu_262_p2 = (!tmp_13_cast1_fu_230_p1.read().is_01() || !tmp_12_fu_256_p2.read().is_01())? sc_lv<1>(): (sc_biguint<18>(tmp_13_cast1_fu_230_p1.read()) > sc_biguint<18>(tmp_12_fu_256_p2.read()));
}

void getPeakBinOf5::thread_tmp_14_cast1_fu_236_p1() {
    tmp_14_cast1_fu_236_p1 = esl_zext<18,16>(etSum_read_reg_337.read());
}

void getPeakBinOf5::thread_tmp_14_fu_268_p3() {
    tmp_14_fu_268_p3 = esl_concat<16,2>(etSum_read_reg_337.read(), ap_const_lv2_0);
}

void getPeakBinOf5::thread_tmp_15_cast_fu_246_p1() {
    tmp_15_cast_fu_246_p1 = esl_zext<18,17>(tmp_10_fu_239_p3.read());
}

void getPeakBinOf5::thread_tmp_15_fu_275_p2() {
    tmp_15_fu_275_p2 = (!tmp_13_cast1_fu_230_p1.read().is_01() || !tmp_14_fu_268_p3.read().is_01())? sc_lv<1>(): (sc_biguint<18>(tmp_13_cast1_fu_230_p1.read()) > sc_biguint<18>(tmp_14_fu_268_p3.read()));
}

void getPeakBinOf5::thread_tmp_16_fu_124_p1() {
    tmp_16_fu_124_p1 = esl_zext<16,15>(tmp_1_fu_114_p4.read());
}

void getPeakBinOf5::thread_tmp_17_fu_144_p1() {
    tmp_17_fu_144_p1 = esl_zext<16,15>(tmp_3_fu_134_p4.read());
}

void getPeakBinOf5::thread_tmp_18_fu_148_p1() {
    tmp_18_fu_148_p1 = et_4_read.read().range(14-1, 0);
}

void getPeakBinOf5::thread_tmp_19_fu_152_p1() {
    tmp_19_fu_152_p1 = et_3_read.read().range(14-1, 0);
}

void getPeakBinOf5::thread_tmp_1_fu_114_p4() {
    tmp_1_fu_114_p4 = et_2_read.read().range(15, 1);
}

void getPeakBinOf5::thread_tmp_20_fu_180_p1() {
    tmp_20_fu_180_p1 = esl_zext<16,15>(tmp_4_fu_170_p4.read());
}

void getPeakBinOf5::thread_tmp_2_fu_96_p1() {
    tmp_2_fu_96_p1 = esl_zext<16,15>(tmp_9_fu_86_p4.read());
}

void getPeakBinOf5::thread_tmp_3_fu_134_p4() {
    tmp_3_fu_134_p4 = et_3_read.read().range(15, 1);
}

void getPeakBinOf5::thread_tmp_4_fu_170_p4() {
    tmp_4_fu_170_p4 = et_4_read.read().range(15, 1);
}

void getPeakBinOf5::thread_tmp_5_fu_110_p1() {
    tmp_5_fu_110_p1 = esl_zext<16,15>(tmp_s_fu_100_p4.read());
}

void getPeakBinOf5::thread_tmp_6_fu_208_p2() {
    tmp_6_fu_208_p2 = (!tmp_8_fu_202_p2.read().is_01() || !tmp_17_fu_144_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp_8_fu_202_p2.read()) - sc_biguint<16>(tmp_17_fu_144_p1.read()));
}

void getPeakBinOf5::thread_tmp_7_fu_226_p2() {
    tmp_7_fu_226_p2 = (!iEtSum_reg_345.read().is_01() || !etSum_read_reg_337.read().is_01())? sc_lv<1>(): (sc_biguint<16>(iEtSum_reg_345.read()) > sc_biguint<16>(etSum_read_reg_337.read()));
}

void getPeakBinOf5::thread_tmp_8_fu_202_p2() {
    tmp_8_fu_202_p2 = (!tmp8_fu_184_p2.read().is_01() || !tmp9_fu_196_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(tmp8_fu_184_p2.read()) + sc_biguint<16>(tmp9_fu_196_p2.read()));
}

void getPeakBinOf5::thread_tmp_9_fu_86_p4() {
    tmp_9_fu_86_p4 = et_0_read.read().range(15, 1);
}

void getPeakBinOf5::thread_tmp_fu_128_p2() {
    tmp_fu_128_p2 = (!ap_const_lv16_1.is_01())? sc_lv<16>(): et_2_read.read() << (unsigned short)ap_const_lv16_1.to_uint();
}

void getPeakBinOf5::thread_tmp_s_fu_100_p4() {
    tmp_s_fu_100_p4 = et_1_read.read().range(15, 1);
}

}

