// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module getClustersInCard (
        ap_clk,
        ap_rst,
        crystals_0_read,
        crystals_1_read,
        crystals_2_read,
        crystals_3_read,
        crystals_4_read,
        crystals_5_read,
        crystals_6_read,
        crystals_7_read,
        crystals_8_read,
        crystals_9_read,
        crystals_10_read,
        crystals_11_read,
        crystals_12_read,
        crystals_13_read,
        crystals_14_read,
        crystals_15_read,
        crystals_16_read,
        crystals_17_read,
        crystals_18_read,
        crystals_19_read,
        crystals_20_read,
        crystals_21_read,
        crystals_22_read,
        crystals_23_read,
        crystals_24_read,
        crystals_25_read,
        crystals_26_read,
        crystals_27_read,
        crystals_28_read,
        crystals_29_read,
        crystals_30_read,
        crystals_31_read,
        crystals_32_read,
        crystals_33_read,
        crystals_34_read,
        crystals_35_read,
        crystals_36_read,
        crystals_37_read,
        crystals_38_read,
        crystals_39_read,
        crystals_40_read,
        crystals_41_read,
        crystals_42_read,
        crystals_43_read,
        crystals_44_read,
        crystals_45_read,
        crystals_46_read,
        crystals_47_read,
        crystals_48_read,
        crystals_49_read,
        crystals_50_read,
        crystals_51_read,
        crystals_52_read,
        crystals_53_read,
        crystals_54_read,
        crystals_55_read,
        crystals_56_read,
        crystals_57_read,
        crystals_58_read,
        crystals_59_read,
        crystals_60_read,
        crystals_61_read,
        crystals_62_read,
        crystals_63_read,
        crystals_64_read,
        crystals_65_read,
        crystals_66_read,
        crystals_67_read,
        crystals_68_read,
        crystals_69_read,
        crystals_70_read,
        crystals_71_read,
        crystals_72_read,
        crystals_73_read,
        crystals_74_read,
        crystals_75_read,
        crystals_76_read,
        crystals_77_read,
        crystals_78_read,
        crystals_79_read,
        crystals_80_read,
        crystals_81_read,
        crystals_82_read,
        crystals_83_read,
        crystals_84_read,
        crystals_85_read,
        crystals_86_read,
        crystals_87_read,
        crystals_88_read,
        crystals_89_read,
        crystals_90_read,
        crystals_91_read,
        crystals_92_read,
        crystals_93_read,
        crystals_94_read,
        crystals_95_read,
        crystals_96_read,
        crystals_97_read,
        crystals_98_read,
        crystals_99_read,
        crystals_100_read,
        crystals_101_read,
        crystals_102_read,
        crystals_103_read,
        crystals_104_read,
        crystals_105_read,
        crystals_106_read,
        crystals_107_read,
        crystals_108_read,
        crystals_109_read,
        crystals_110_read,
        crystals_111_read,
        crystals_112_read,
        crystals_113_read,
        crystals_114_read,
        crystals_115_read,
        crystals_116_read,
        crystals_117_read,
        crystals_118_read,
        crystals_119_read,
        crystals_120_read,
        crystals_121_read,
        crystals_122_read,
        crystals_123_read,
        crystals_124_read,
        crystals_125_read,
        crystals_126_read,
        crystals_127_read,
        crystals_128_read,
        crystals_129_read,
        crystals_130_read,
        crystals_131_read,
        crystals_132_read,
        crystals_133_read,
        crystals_134_read,
        crystals_135_read,
        crystals_136_read,
        crystals_137_read,
        crystals_138_read,
        crystals_139_read,
        crystals_140_read,
        crystals_141_read,
        crystals_142_read,
        crystals_143_read,
        crystals_144_read,
        crystals_145_read,
        crystals_146_read,
        crystals_147_read,
        crystals_148_read,
        crystals_149_read,
        crystals_150_read,
        crystals_151_read,
        crystals_152_read,
        crystals_153_read,
        crystals_154_read,
        crystals_155_read,
        crystals_156_read,
        crystals_157_read,
        crystals_158_read,
        crystals_159_read,
        crystals_160_read,
        crystals_161_read,
        crystals_162_read,
        crystals_163_read,
        crystals_164_read,
        crystals_165_read,
        crystals_166_read,
        crystals_167_read,
        crystals_168_read,
        crystals_169_read,
        crystals_170_read,
        crystals_171_read,
        crystals_172_read,
        crystals_173_read,
        crystals_174_read,
        crystals_175_read,
        crystals_176_read,
        crystals_177_read,
        crystals_178_read,
        crystals_179_read,
        crystals_180_read,
        crystals_181_read,
        crystals_182_read,
        crystals_183_read,
        crystals_184_read,
        crystals_185_read,
        crystals_186_read,
        crystals_187_read,
        crystals_188_read,
        crystals_189_read,
        crystals_190_read,
        crystals_191_read,
        crystals_192_read,
        crystals_193_read,
        crystals_194_read,
        crystals_195_read,
        crystals_196_read,
        crystals_197_read,
        crystals_198_read,
        crystals_199_read,
        crystals_200_read,
        crystals_201_read,
        crystals_202_read,
        crystals_203_read,
        crystals_204_read,
        crystals_205_read,
        crystals_206_read,
        crystals_207_read,
        crystals_208_read,
        crystals_209_read,
        crystals_210_read,
        crystals_211_read,
        crystals_212_read,
        crystals_213_read,
        crystals_214_read,
        crystals_215_read,
        crystals_216_read,
        crystals_217_read,
        crystals_218_read,
        crystals_219_read,
        crystals_220_read,
        crystals_221_read,
        crystals_222_read,
        crystals_223_read,
        crystals_224_read,
        crystals_225_read,
        crystals_226_read,
        crystals_227_read,
        crystals_228_read,
        crystals_229_read,
        crystals_230_read,
        crystals_231_read,
        crystals_232_read,
        crystals_233_read,
        crystals_234_read,
        crystals_235_read,
        crystals_236_read,
        crystals_237_read,
        crystals_238_read,
        crystals_239_read,
        crystals_240_read,
        crystals_241_read,
        crystals_242_read,
        crystals_243_read,
        crystals_244_read,
        crystals_245_read,
        crystals_246_read,
        crystals_247_read,
        crystals_248_read,
        crystals_249_read,
        crystals_250_read,
        crystals_251_read,
        crystals_252_read,
        crystals_253_read,
        crystals_254_read,
        crystals_255_read,
        crystals_256_read,
        crystals_257_read,
        crystals_258_read,
        crystals_259_read,
        crystals_260_read,
        crystals_261_read,
        crystals_262_read,
        crystals_263_read,
        crystals_264_read,
        crystals_265_read,
        crystals_266_read,
        crystals_267_read,
        crystals_268_read,
        crystals_269_read,
        crystals_270_read,
        crystals_271_read,
        crystals_272_read,
        crystals_273_read,
        crystals_274_read,
        crystals_275_read,
        crystals_276_read,
        crystals_277_read,
        crystals_278_read,
        crystals_279_read,
        crystals_280_read,
        crystals_281_read,
        crystals_282_read,
        crystals_283_read,
        crystals_284_read,
        crystals_285_read,
        crystals_286_read,
        crystals_287_read,
        crystals_288_read,
        crystals_289_read,
        crystals_290_read,
        crystals_291_read,
        crystals_292_read,
        crystals_293_read,
        crystals_294_read,
        crystals_295_read,
        crystals_296_read,
        crystals_297_read,
        crystals_298_read,
        crystals_299_read,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] crystals_0_read;
input  [15:0] crystals_1_read;
input  [15:0] crystals_2_read;
input  [15:0] crystals_3_read;
input  [15:0] crystals_4_read;
input  [15:0] crystals_5_read;
input  [15:0] crystals_6_read;
input  [15:0] crystals_7_read;
input  [15:0] crystals_8_read;
input  [15:0] crystals_9_read;
input  [15:0] crystals_10_read;
input  [15:0] crystals_11_read;
input  [15:0] crystals_12_read;
input  [15:0] crystals_13_read;
input  [15:0] crystals_14_read;
input  [15:0] crystals_15_read;
input  [15:0] crystals_16_read;
input  [15:0] crystals_17_read;
input  [15:0] crystals_18_read;
input  [15:0] crystals_19_read;
input  [15:0] crystals_20_read;
input  [15:0] crystals_21_read;
input  [15:0] crystals_22_read;
input  [15:0] crystals_23_read;
input  [15:0] crystals_24_read;
input  [15:0] crystals_25_read;
input  [15:0] crystals_26_read;
input  [15:0] crystals_27_read;
input  [15:0] crystals_28_read;
input  [15:0] crystals_29_read;
input  [15:0] crystals_30_read;
input  [15:0] crystals_31_read;
input  [15:0] crystals_32_read;
input  [15:0] crystals_33_read;
input  [15:0] crystals_34_read;
input  [15:0] crystals_35_read;
input  [15:0] crystals_36_read;
input  [15:0] crystals_37_read;
input  [15:0] crystals_38_read;
input  [15:0] crystals_39_read;
input  [15:0] crystals_40_read;
input  [15:0] crystals_41_read;
input  [15:0] crystals_42_read;
input  [15:0] crystals_43_read;
input  [15:0] crystals_44_read;
input  [15:0] crystals_45_read;
input  [15:0] crystals_46_read;
input  [15:0] crystals_47_read;
input  [15:0] crystals_48_read;
input  [15:0] crystals_49_read;
input  [15:0] crystals_50_read;
input  [15:0] crystals_51_read;
input  [15:0] crystals_52_read;
input  [15:0] crystals_53_read;
input  [15:0] crystals_54_read;
input  [15:0] crystals_55_read;
input  [15:0] crystals_56_read;
input  [15:0] crystals_57_read;
input  [15:0] crystals_58_read;
input  [15:0] crystals_59_read;
input  [15:0] crystals_60_read;
input  [15:0] crystals_61_read;
input  [15:0] crystals_62_read;
input  [15:0] crystals_63_read;
input  [15:0] crystals_64_read;
input  [15:0] crystals_65_read;
input  [15:0] crystals_66_read;
input  [15:0] crystals_67_read;
input  [15:0] crystals_68_read;
input  [15:0] crystals_69_read;
input  [15:0] crystals_70_read;
input  [15:0] crystals_71_read;
input  [15:0] crystals_72_read;
input  [15:0] crystals_73_read;
input  [15:0] crystals_74_read;
input  [15:0] crystals_75_read;
input  [15:0] crystals_76_read;
input  [15:0] crystals_77_read;
input  [15:0] crystals_78_read;
input  [15:0] crystals_79_read;
input  [15:0] crystals_80_read;
input  [15:0] crystals_81_read;
input  [15:0] crystals_82_read;
input  [15:0] crystals_83_read;
input  [15:0] crystals_84_read;
input  [15:0] crystals_85_read;
input  [15:0] crystals_86_read;
input  [15:0] crystals_87_read;
input  [15:0] crystals_88_read;
input  [15:0] crystals_89_read;
input  [15:0] crystals_90_read;
input  [15:0] crystals_91_read;
input  [15:0] crystals_92_read;
input  [15:0] crystals_93_read;
input  [15:0] crystals_94_read;
input  [15:0] crystals_95_read;
input  [15:0] crystals_96_read;
input  [15:0] crystals_97_read;
input  [15:0] crystals_98_read;
input  [15:0] crystals_99_read;
input  [15:0] crystals_100_read;
input  [15:0] crystals_101_read;
input  [15:0] crystals_102_read;
input  [15:0] crystals_103_read;
input  [15:0] crystals_104_read;
input  [15:0] crystals_105_read;
input  [15:0] crystals_106_read;
input  [15:0] crystals_107_read;
input  [15:0] crystals_108_read;
input  [15:0] crystals_109_read;
input  [15:0] crystals_110_read;
input  [15:0] crystals_111_read;
input  [15:0] crystals_112_read;
input  [15:0] crystals_113_read;
input  [15:0] crystals_114_read;
input  [15:0] crystals_115_read;
input  [15:0] crystals_116_read;
input  [15:0] crystals_117_read;
input  [15:0] crystals_118_read;
input  [15:0] crystals_119_read;
input  [15:0] crystals_120_read;
input  [15:0] crystals_121_read;
input  [15:0] crystals_122_read;
input  [15:0] crystals_123_read;
input  [15:0] crystals_124_read;
input  [15:0] crystals_125_read;
input  [15:0] crystals_126_read;
input  [15:0] crystals_127_read;
input  [15:0] crystals_128_read;
input  [15:0] crystals_129_read;
input  [15:0] crystals_130_read;
input  [15:0] crystals_131_read;
input  [15:0] crystals_132_read;
input  [15:0] crystals_133_read;
input  [15:0] crystals_134_read;
input  [15:0] crystals_135_read;
input  [15:0] crystals_136_read;
input  [15:0] crystals_137_read;
input  [15:0] crystals_138_read;
input  [15:0] crystals_139_read;
input  [15:0] crystals_140_read;
input  [15:0] crystals_141_read;
input  [15:0] crystals_142_read;
input  [15:0] crystals_143_read;
input  [15:0] crystals_144_read;
input  [15:0] crystals_145_read;
input  [15:0] crystals_146_read;
input  [15:0] crystals_147_read;
input  [15:0] crystals_148_read;
input  [15:0] crystals_149_read;
input  [15:0] crystals_150_read;
input  [15:0] crystals_151_read;
input  [15:0] crystals_152_read;
input  [15:0] crystals_153_read;
input  [15:0] crystals_154_read;
input  [15:0] crystals_155_read;
input  [15:0] crystals_156_read;
input  [15:0] crystals_157_read;
input  [15:0] crystals_158_read;
input  [15:0] crystals_159_read;
input  [15:0] crystals_160_read;
input  [15:0] crystals_161_read;
input  [15:0] crystals_162_read;
input  [15:0] crystals_163_read;
input  [15:0] crystals_164_read;
input  [15:0] crystals_165_read;
input  [15:0] crystals_166_read;
input  [15:0] crystals_167_read;
input  [15:0] crystals_168_read;
input  [15:0] crystals_169_read;
input  [15:0] crystals_170_read;
input  [15:0] crystals_171_read;
input  [15:0] crystals_172_read;
input  [15:0] crystals_173_read;
input  [15:0] crystals_174_read;
input  [15:0] crystals_175_read;
input  [15:0] crystals_176_read;
input  [15:0] crystals_177_read;
input  [15:0] crystals_178_read;
input  [15:0] crystals_179_read;
input  [15:0] crystals_180_read;
input  [15:0] crystals_181_read;
input  [15:0] crystals_182_read;
input  [15:0] crystals_183_read;
input  [15:0] crystals_184_read;
input  [15:0] crystals_185_read;
input  [15:0] crystals_186_read;
input  [15:0] crystals_187_read;
input  [15:0] crystals_188_read;
input  [15:0] crystals_189_read;
input  [15:0] crystals_190_read;
input  [15:0] crystals_191_read;
input  [15:0] crystals_192_read;
input  [15:0] crystals_193_read;
input  [15:0] crystals_194_read;
input  [15:0] crystals_195_read;
input  [15:0] crystals_196_read;
input  [15:0] crystals_197_read;
input  [15:0] crystals_198_read;
input  [15:0] crystals_199_read;
input  [15:0] crystals_200_read;
input  [15:0] crystals_201_read;
input  [15:0] crystals_202_read;
input  [15:0] crystals_203_read;
input  [15:0] crystals_204_read;
input  [15:0] crystals_205_read;
input  [15:0] crystals_206_read;
input  [15:0] crystals_207_read;
input  [15:0] crystals_208_read;
input  [15:0] crystals_209_read;
input  [15:0] crystals_210_read;
input  [15:0] crystals_211_read;
input  [15:0] crystals_212_read;
input  [15:0] crystals_213_read;
input  [15:0] crystals_214_read;
input  [15:0] crystals_215_read;
input  [15:0] crystals_216_read;
input  [15:0] crystals_217_read;
input  [15:0] crystals_218_read;
input  [15:0] crystals_219_read;
input  [15:0] crystals_220_read;
input  [15:0] crystals_221_read;
input  [15:0] crystals_222_read;
input  [15:0] crystals_223_read;
input  [15:0] crystals_224_read;
input  [15:0] crystals_225_read;
input  [15:0] crystals_226_read;
input  [15:0] crystals_227_read;
input  [15:0] crystals_228_read;
input  [15:0] crystals_229_read;
input  [15:0] crystals_230_read;
input  [15:0] crystals_231_read;
input  [15:0] crystals_232_read;
input  [15:0] crystals_233_read;
input  [15:0] crystals_234_read;
input  [15:0] crystals_235_read;
input  [15:0] crystals_236_read;
input  [15:0] crystals_237_read;
input  [15:0] crystals_238_read;
input  [15:0] crystals_239_read;
input  [15:0] crystals_240_read;
input  [15:0] crystals_241_read;
input  [15:0] crystals_242_read;
input  [15:0] crystals_243_read;
input  [15:0] crystals_244_read;
input  [15:0] crystals_245_read;
input  [15:0] crystals_246_read;
input  [15:0] crystals_247_read;
input  [15:0] crystals_248_read;
input  [15:0] crystals_249_read;
input  [15:0] crystals_250_read;
input  [15:0] crystals_251_read;
input  [15:0] crystals_252_read;
input  [15:0] crystals_253_read;
input  [15:0] crystals_254_read;
input  [15:0] crystals_255_read;
input  [15:0] crystals_256_read;
input  [15:0] crystals_257_read;
input  [15:0] crystals_258_read;
input  [15:0] crystals_259_read;
input  [15:0] crystals_260_read;
input  [15:0] crystals_261_read;
input  [15:0] crystals_262_read;
input  [15:0] crystals_263_read;
input  [15:0] crystals_264_read;
input  [15:0] crystals_265_read;
input  [15:0] crystals_266_read;
input  [15:0] crystals_267_read;
input  [15:0] crystals_268_read;
input  [15:0] crystals_269_read;
input  [15:0] crystals_270_read;
input  [15:0] crystals_271_read;
input  [15:0] crystals_272_read;
input  [15:0] crystals_273_read;
input  [15:0] crystals_274_read;
input  [15:0] crystals_275_read;
input  [15:0] crystals_276_read;
input  [15:0] crystals_277_read;
input  [15:0] crystals_278_read;
input  [15:0] crystals_279_read;
input  [15:0] crystals_280_read;
input  [15:0] crystals_281_read;
input  [15:0] crystals_282_read;
input  [15:0] crystals_283_read;
input  [15:0] crystals_284_read;
input  [15:0] crystals_285_read;
input  [15:0] crystals_286_read;
input  [15:0] crystals_287_read;
input  [15:0] crystals_288_read;
input  [15:0] crystals_289_read;
input  [15:0] crystals_290_read;
input  [15:0] crystals_291_read;
input  [15:0] crystals_292_read;
input  [15:0] crystals_293_read;
input  [15:0] crystals_294_read;
input  [15:0] crystals_295_read;
input  [15:0] crystals_296_read;
input  [15:0] crystals_297_read;
input  [15:0] crystals_298_read;
input  [15:0] crystals_299_read;
input   ap_ce;

wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
reg    grp_getClustersin3x4Regi_fu_2412_ap_ce;
wire    ap_block_pp0_stage0;
reg    ap_ce_reg;
reg   [15:0] crystals_0_read_int_reg;
reg   [15:0] crystals_1_read_int_reg;
reg   [15:0] crystals_2_read_int_reg;
reg   [15:0] crystals_3_read_int_reg;
reg   [15:0] crystals_4_read_int_reg;
reg   [15:0] crystals_5_read_int_reg;
reg   [15:0] crystals_6_read_int_reg;
reg   [15:0] crystals_7_read_int_reg;
reg   [15:0] crystals_8_read_int_reg;
reg   [15:0] crystals_9_read_int_reg;
reg   [15:0] crystals_10_read_int_reg;
reg   [15:0] crystals_11_read_int_reg;
reg   [15:0] crystals_12_read_int_reg;
reg   [15:0] crystals_13_read_int_reg;
reg   [15:0] crystals_14_read_int_reg;
reg   [15:0] crystals_15_read_int_reg;
reg   [15:0] crystals_16_read_int_reg;
reg   [15:0] crystals_17_read_int_reg;
reg   [15:0] crystals_18_read_int_reg;
reg   [15:0] crystals_19_read_int_reg;
reg   [15:0] crystals_20_read_int_reg;
reg   [15:0] crystals_21_read_int_reg;
reg   [15:0] crystals_22_read_int_reg;
reg   [15:0] crystals_23_read_int_reg;
reg   [15:0] crystals_24_read_int_reg;
reg   [15:0] crystals_25_read_int_reg;
reg   [15:0] crystals_26_read_int_reg;
reg   [15:0] crystals_27_read_int_reg;
reg   [15:0] crystals_28_read_int_reg;
reg   [15:0] crystals_29_read_int_reg;
reg   [15:0] crystals_30_read_int_reg;
reg   [15:0] crystals_31_read_int_reg;
reg   [15:0] crystals_32_read_int_reg;
reg   [15:0] crystals_33_read_int_reg;
reg   [15:0] crystals_34_read_int_reg;
reg   [15:0] crystals_35_read_int_reg;
reg   [15:0] crystals_36_read_int_reg;
reg   [15:0] crystals_37_read_int_reg;
reg   [15:0] crystals_38_read_int_reg;
reg   [15:0] crystals_39_read_int_reg;
reg   [15:0] crystals_40_read_int_reg;
reg   [15:0] crystals_41_read_int_reg;
reg   [15:0] crystals_42_read_int_reg;
reg   [15:0] crystals_43_read_int_reg;
reg   [15:0] crystals_44_read_int_reg;
reg   [15:0] crystals_45_read_int_reg;
reg   [15:0] crystals_46_read_int_reg;
reg   [15:0] crystals_47_read_int_reg;
reg   [15:0] crystals_48_read_int_reg;
reg   [15:0] crystals_49_read_int_reg;
reg   [15:0] crystals_50_read_int_reg;
reg   [15:0] crystals_51_read_int_reg;
reg   [15:0] crystals_52_read_int_reg;
reg   [15:0] crystals_53_read_int_reg;
reg   [15:0] crystals_54_read_int_reg;
reg   [15:0] crystals_55_read_int_reg;
reg   [15:0] crystals_56_read_int_reg;
reg   [15:0] crystals_57_read_int_reg;
reg   [15:0] crystals_58_read_int_reg;
reg   [15:0] crystals_59_read_int_reg;
reg   [15:0] crystals_60_read_int_reg;
reg   [15:0] crystals_61_read_int_reg;
reg   [15:0] crystals_62_read_int_reg;
reg   [15:0] crystals_63_read_int_reg;
reg   [15:0] crystals_64_read_int_reg;
reg   [15:0] crystals_65_read_int_reg;
reg   [15:0] crystals_66_read_int_reg;
reg   [15:0] crystals_67_read_int_reg;
reg   [15:0] crystals_68_read_int_reg;
reg   [15:0] crystals_69_read_int_reg;
reg   [15:0] crystals_70_read_int_reg;
reg   [15:0] crystals_71_read_int_reg;
reg   [15:0] crystals_72_read_int_reg;
reg   [15:0] crystals_73_read_int_reg;
reg   [15:0] crystals_74_read_int_reg;
reg   [15:0] crystals_75_read_int_reg;
reg   [15:0] crystals_76_read_int_reg;
reg   [15:0] crystals_77_read_int_reg;
reg   [15:0] crystals_78_read_int_reg;
reg   [15:0] crystals_79_read_int_reg;
reg   [15:0] crystals_80_read_int_reg;
reg   [15:0] crystals_81_read_int_reg;
reg   [15:0] crystals_82_read_int_reg;
reg   [15:0] crystals_83_read_int_reg;
reg   [15:0] crystals_84_read_int_reg;
reg   [15:0] crystals_85_read_int_reg;
reg   [15:0] crystals_86_read_int_reg;
reg   [15:0] crystals_87_read_int_reg;
reg   [15:0] crystals_88_read_int_reg;
reg   [15:0] crystals_89_read_int_reg;
reg   [15:0] crystals_90_read_int_reg;
reg   [15:0] crystals_91_read_int_reg;
reg   [15:0] crystals_92_read_int_reg;
reg   [15:0] crystals_93_read_int_reg;
reg   [15:0] crystals_94_read_int_reg;
reg   [15:0] crystals_95_read_int_reg;
reg   [15:0] crystals_96_read_int_reg;
reg   [15:0] crystals_97_read_int_reg;
reg   [15:0] crystals_98_read_int_reg;
reg   [15:0] crystals_99_read_int_reg;
reg   [15:0] crystals_100_read_int_reg;
reg   [15:0] crystals_101_read_int_reg;
reg   [15:0] crystals_102_read_int_reg;
reg   [15:0] crystals_103_read_int_reg;
reg   [15:0] crystals_104_read_int_reg;
reg   [15:0] crystals_105_read_int_reg;
reg   [15:0] crystals_106_read_int_reg;
reg   [15:0] crystals_107_read_int_reg;
reg   [15:0] crystals_108_read_int_reg;
reg   [15:0] crystals_109_read_int_reg;
reg   [15:0] crystals_110_read_int_reg;
reg   [15:0] crystals_111_read_int_reg;
reg   [15:0] crystals_112_read_int_reg;
reg   [15:0] crystals_113_read_int_reg;
reg   [15:0] crystals_114_read_int_reg;
reg   [15:0] crystals_115_read_int_reg;
reg   [15:0] crystals_116_read_int_reg;
reg   [15:0] crystals_117_read_int_reg;
reg   [15:0] crystals_118_read_int_reg;
reg   [15:0] crystals_119_read_int_reg;
reg   [15:0] crystals_120_read_int_reg;
reg   [15:0] crystals_121_read_int_reg;
reg   [15:0] crystals_122_read_int_reg;
reg   [15:0] crystals_123_read_int_reg;
reg   [15:0] crystals_124_read_int_reg;
reg   [15:0] crystals_125_read_int_reg;
reg   [15:0] crystals_126_read_int_reg;
reg   [15:0] crystals_127_read_int_reg;
reg   [15:0] crystals_128_read_int_reg;
reg   [15:0] crystals_129_read_int_reg;
reg   [15:0] crystals_130_read_int_reg;
reg   [15:0] crystals_131_read_int_reg;
reg   [15:0] crystals_132_read_int_reg;
reg   [15:0] crystals_133_read_int_reg;
reg   [15:0] crystals_134_read_int_reg;
reg   [15:0] crystals_135_read_int_reg;
reg   [15:0] crystals_136_read_int_reg;
reg   [15:0] crystals_137_read_int_reg;
reg   [15:0] crystals_138_read_int_reg;
reg   [15:0] crystals_139_read_int_reg;
reg   [15:0] crystals_140_read_int_reg;
reg   [15:0] crystals_141_read_int_reg;
reg   [15:0] crystals_142_read_int_reg;
reg   [15:0] crystals_143_read_int_reg;
reg   [15:0] crystals_144_read_int_reg;
reg   [15:0] crystals_145_read_int_reg;
reg   [15:0] crystals_146_read_int_reg;
reg   [15:0] crystals_147_read_int_reg;
reg   [15:0] crystals_148_read_int_reg;
reg   [15:0] crystals_149_read_int_reg;
reg   [15:0] crystals_150_read_int_reg;
reg   [15:0] crystals_151_read_int_reg;
reg   [15:0] crystals_152_read_int_reg;
reg   [15:0] crystals_153_read_int_reg;
reg   [15:0] crystals_154_read_int_reg;
reg   [15:0] crystals_155_read_int_reg;
reg   [15:0] crystals_156_read_int_reg;
reg   [15:0] crystals_157_read_int_reg;
reg   [15:0] crystals_158_read_int_reg;
reg   [15:0] crystals_159_read_int_reg;
reg   [15:0] crystals_160_read_int_reg;
reg   [15:0] crystals_161_read_int_reg;
reg   [15:0] crystals_162_read_int_reg;
reg   [15:0] crystals_163_read_int_reg;
reg   [15:0] crystals_164_read_int_reg;
reg   [15:0] crystals_165_read_int_reg;
reg   [15:0] crystals_166_read_int_reg;
reg   [15:0] crystals_167_read_int_reg;
reg   [15:0] crystals_168_read_int_reg;
reg   [15:0] crystals_169_read_int_reg;
reg   [15:0] crystals_170_read_int_reg;
reg   [15:0] crystals_171_read_int_reg;
reg   [15:0] crystals_172_read_int_reg;
reg   [15:0] crystals_173_read_int_reg;
reg   [15:0] crystals_174_read_int_reg;
reg   [15:0] crystals_175_read_int_reg;
reg   [15:0] crystals_176_read_int_reg;
reg   [15:0] crystals_177_read_int_reg;
reg   [15:0] crystals_178_read_int_reg;
reg   [15:0] crystals_179_read_int_reg;
reg   [15:0] crystals_180_read_int_reg;
reg   [15:0] crystals_181_read_int_reg;
reg   [15:0] crystals_182_read_int_reg;
reg   [15:0] crystals_183_read_int_reg;
reg   [15:0] crystals_184_read_int_reg;
reg   [15:0] crystals_185_read_int_reg;
reg   [15:0] crystals_186_read_int_reg;
reg   [15:0] crystals_187_read_int_reg;
reg   [15:0] crystals_188_read_int_reg;
reg   [15:0] crystals_189_read_int_reg;
reg   [15:0] crystals_190_read_int_reg;
reg   [15:0] crystals_191_read_int_reg;
reg   [15:0] crystals_192_read_int_reg;
reg   [15:0] crystals_193_read_int_reg;
reg   [15:0] crystals_194_read_int_reg;
reg   [15:0] crystals_195_read_int_reg;
reg   [15:0] crystals_196_read_int_reg;
reg   [15:0] crystals_197_read_int_reg;
reg   [15:0] crystals_198_read_int_reg;
reg   [15:0] crystals_199_read_int_reg;
reg   [15:0] crystals_200_read_int_reg;
reg   [15:0] crystals_201_read_int_reg;
reg   [15:0] crystals_202_read_int_reg;
reg   [15:0] crystals_203_read_int_reg;
reg   [15:0] crystals_204_read_int_reg;
reg   [15:0] crystals_205_read_int_reg;
reg   [15:0] crystals_206_read_int_reg;
reg   [15:0] crystals_207_read_int_reg;
reg   [15:0] crystals_208_read_int_reg;
reg   [15:0] crystals_209_read_int_reg;
reg   [15:0] crystals_210_read_int_reg;
reg   [15:0] crystals_211_read_int_reg;
reg   [15:0] crystals_212_read_int_reg;
reg   [15:0] crystals_213_read_int_reg;
reg   [15:0] crystals_214_read_int_reg;
reg   [15:0] crystals_215_read_int_reg;
reg   [15:0] crystals_216_read_int_reg;
reg   [15:0] crystals_217_read_int_reg;
reg   [15:0] crystals_218_read_int_reg;
reg   [15:0] crystals_219_read_int_reg;
reg   [15:0] crystals_220_read_int_reg;
reg   [15:0] crystals_221_read_int_reg;
reg   [15:0] crystals_222_read_int_reg;
reg   [15:0] crystals_223_read_int_reg;
reg   [15:0] crystals_224_read_int_reg;
reg   [15:0] crystals_225_read_int_reg;
reg   [15:0] crystals_226_read_int_reg;
reg   [15:0] crystals_227_read_int_reg;
reg   [15:0] crystals_228_read_int_reg;
reg   [15:0] crystals_229_read_int_reg;
reg   [15:0] crystals_230_read_int_reg;
reg   [15:0] crystals_231_read_int_reg;
reg   [15:0] crystals_232_read_int_reg;
reg   [15:0] crystals_233_read_int_reg;
reg   [15:0] crystals_234_read_int_reg;
reg   [15:0] crystals_235_read_int_reg;
reg   [15:0] crystals_236_read_int_reg;
reg   [15:0] crystals_237_read_int_reg;
reg   [15:0] crystals_238_read_int_reg;
reg   [15:0] crystals_239_read_int_reg;
reg   [15:0] crystals_240_read_int_reg;
reg   [15:0] crystals_241_read_int_reg;
reg   [15:0] crystals_242_read_int_reg;
reg   [15:0] crystals_243_read_int_reg;
reg   [15:0] crystals_244_read_int_reg;
reg   [15:0] crystals_245_read_int_reg;
reg   [15:0] crystals_246_read_int_reg;
reg   [15:0] crystals_247_read_int_reg;
reg   [15:0] crystals_248_read_int_reg;
reg   [15:0] crystals_249_read_int_reg;
reg   [15:0] crystals_250_read_int_reg;
reg   [15:0] crystals_251_read_int_reg;
reg   [15:0] crystals_252_read_int_reg;
reg   [15:0] crystals_253_read_int_reg;
reg   [15:0] crystals_254_read_int_reg;
reg   [15:0] crystals_255_read_int_reg;
reg   [15:0] crystals_256_read_int_reg;
reg   [15:0] crystals_257_read_int_reg;
reg   [15:0] crystals_258_read_int_reg;
reg   [15:0] crystals_259_read_int_reg;
reg   [15:0] crystals_260_read_int_reg;
reg   [15:0] crystals_261_read_int_reg;
reg   [15:0] crystals_262_read_int_reg;
reg   [15:0] crystals_263_read_int_reg;
reg   [15:0] crystals_264_read_int_reg;
reg   [15:0] crystals_265_read_int_reg;
reg   [15:0] crystals_266_read_int_reg;
reg   [15:0] crystals_267_read_int_reg;
reg   [15:0] crystals_268_read_int_reg;
reg   [15:0] crystals_269_read_int_reg;
reg   [15:0] crystals_270_read_int_reg;
reg   [15:0] crystals_271_read_int_reg;
reg   [15:0] crystals_272_read_int_reg;
reg   [15:0] crystals_273_read_int_reg;
reg   [15:0] crystals_274_read_int_reg;
reg   [15:0] crystals_275_read_int_reg;
reg   [15:0] crystals_276_read_int_reg;
reg   [15:0] crystals_277_read_int_reg;
reg   [15:0] crystals_278_read_int_reg;
reg   [15:0] crystals_279_read_int_reg;
reg   [15:0] crystals_280_read_int_reg;
reg   [15:0] crystals_281_read_int_reg;
reg   [15:0] crystals_282_read_int_reg;
reg   [15:0] crystals_283_read_int_reg;
reg   [15:0] crystals_284_read_int_reg;
reg   [15:0] crystals_285_read_int_reg;
reg   [15:0] crystals_286_read_int_reg;
reg   [15:0] crystals_287_read_int_reg;
reg   [15:0] crystals_288_read_int_reg;
reg   [15:0] crystals_289_read_int_reg;
reg   [15:0] crystals_290_read_int_reg;
reg   [15:0] crystals_291_read_int_reg;
reg   [15:0] crystals_292_read_int_reg;
reg   [15:0] crystals_293_read_int_reg;
reg   [15:0] crystals_294_read_int_reg;
reg   [15:0] crystals_295_read_int_reg;
reg   [15:0] crystals_296_read_int_reg;
reg   [15:0] crystals_297_read_int_reg;
reg   [15:0] crystals_298_read_int_reg;
reg   [15:0] crystals_299_read_int_reg;

getClustersin3x4Regi grp_getClustersin3x4Regi_fu_2412(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .crystals_tower_0_0_0_0_read(crystals_0_read_int_reg),
    .crystals_tower_0_0_0_1_read(crystals_1_read_int_reg),
    .crystals_tower_0_0_0_2_read(crystals_2_read_int_reg),
    .crystals_tower_0_0_0_3_read(crystals_3_read_int_reg),
    .crystals_tower_0_0_0_4_read(crystals_4_read_int_reg),
    .crystals_tower_0_0_1_0_read(crystals_5_read_int_reg),
    .crystals_tower_0_0_1_1_read(crystals_6_read_int_reg),
    .crystals_tower_0_0_1_2_read(crystals_7_read_int_reg),
    .crystals_tower_0_0_1_3_read(crystals_8_read_int_reg),
    .crystals_tower_0_0_1_4_read(crystals_9_read_int_reg),
    .crystals_tower_0_0_2_0_read(crystals_10_read_int_reg),
    .crystals_tower_0_0_2_1_read(crystals_11_read_int_reg),
    .crystals_tower_0_0_2_2_read(crystals_12_read_int_reg),
    .crystals_tower_0_0_2_3_read(crystals_13_read_int_reg),
    .crystals_tower_0_0_2_4_read(crystals_14_read_int_reg),
    .crystals_tower_0_0_3_0_read(crystals_15_read_int_reg),
    .crystals_tower_0_0_3_1_read(crystals_16_read_int_reg),
    .crystals_tower_0_0_3_2_read(crystals_17_read_int_reg),
    .crystals_tower_0_0_3_3_read(crystals_18_read_int_reg),
    .crystals_tower_0_0_3_4_read(crystals_19_read_int_reg),
    .crystals_tower_0_0_4_0_read(crystals_20_read_int_reg),
    .crystals_tower_0_0_4_1_read(crystals_21_read_int_reg),
    .crystals_tower_0_0_4_2_read(crystals_22_read_int_reg),
    .crystals_tower_0_0_4_3_read(crystals_23_read_int_reg),
    .crystals_tower_0_0_4_4_read(crystals_24_read_int_reg),
    .crystals_tower_0_1_0_0_read(crystals_25_read_int_reg),
    .crystals_tower_0_1_0_1_read(crystals_26_read_int_reg),
    .crystals_tower_0_1_0_2_read(crystals_27_read_int_reg),
    .crystals_tower_0_1_0_3_read(crystals_28_read_int_reg),
    .crystals_tower_0_1_0_4_read(crystals_29_read_int_reg),
    .crystals_tower_0_1_1_0_read(crystals_30_read_int_reg),
    .crystals_tower_0_1_1_1_read(crystals_31_read_int_reg),
    .crystals_tower_0_1_1_2_read(crystals_32_read_int_reg),
    .crystals_tower_0_1_1_3_read(crystals_33_read_int_reg),
    .crystals_tower_0_1_1_4_read(crystals_34_read_int_reg),
    .crystals_tower_0_1_2_0_read(crystals_35_read_int_reg),
    .crystals_tower_0_1_2_1_read(crystals_36_read_int_reg),
    .crystals_tower_0_1_2_2_read(crystals_37_read_int_reg),
    .crystals_tower_0_1_2_3_read(crystals_38_read_int_reg),
    .crystals_tower_0_1_2_4_read(crystals_39_read_int_reg),
    .crystals_tower_0_1_3_0_read(crystals_40_read_int_reg),
    .crystals_tower_0_1_3_1_read(crystals_41_read_int_reg),
    .crystals_tower_0_1_3_2_read(crystals_42_read_int_reg),
    .crystals_tower_0_1_3_3_read(crystals_43_read_int_reg),
    .crystals_tower_0_1_3_4_read(crystals_44_read_int_reg),
    .crystals_tower_0_1_4_0_read(crystals_45_read_int_reg),
    .crystals_tower_0_1_4_1_read(crystals_46_read_int_reg),
    .crystals_tower_0_1_4_2_read(crystals_47_read_int_reg),
    .crystals_tower_0_1_4_3_read(crystals_48_read_int_reg),
    .crystals_tower_0_1_4_4_read(crystals_49_read_int_reg),
    .crystals_tower_0_2_0_0_read(crystals_50_read_int_reg),
    .crystals_tower_0_2_0_1_read(crystals_51_read_int_reg),
    .crystals_tower_0_2_0_2_read(crystals_52_read_int_reg),
    .crystals_tower_0_2_0_3_read(crystals_53_read_int_reg),
    .crystals_tower_0_2_0_4_read(crystals_54_read_int_reg),
    .crystals_tower_0_2_1_0_read(crystals_55_read_int_reg),
    .crystals_tower_0_2_1_1_read(crystals_56_read_int_reg),
    .crystals_tower_0_2_1_2_read(crystals_57_read_int_reg),
    .crystals_tower_0_2_1_3_read(crystals_58_read_int_reg),
    .crystals_tower_0_2_1_4_read(crystals_59_read_int_reg),
    .crystals_tower_0_2_2_0_read(crystals_60_read_int_reg),
    .crystals_tower_0_2_2_1_read(crystals_61_read_int_reg),
    .crystals_tower_0_2_2_2_read(crystals_62_read_int_reg),
    .crystals_tower_0_2_2_3_read(crystals_63_read_int_reg),
    .crystals_tower_0_2_2_4_read(crystals_64_read_int_reg),
    .crystals_tower_0_2_3_0_read(crystals_65_read_int_reg),
    .crystals_tower_0_2_3_1_read(crystals_66_read_int_reg),
    .crystals_tower_0_2_3_2_read(crystals_67_read_int_reg),
    .crystals_tower_0_2_3_3_read(crystals_68_read_int_reg),
    .crystals_tower_0_2_3_4_read(crystals_69_read_int_reg),
    .crystals_tower_0_2_4_0_read(crystals_70_read_int_reg),
    .crystals_tower_0_2_4_1_read(crystals_71_read_int_reg),
    .crystals_tower_0_2_4_2_read(crystals_72_read_int_reg),
    .crystals_tower_0_2_4_3_read(crystals_73_read_int_reg),
    .crystals_tower_0_2_4_4_read(crystals_74_read_int_reg),
    .crystals_tower_0_3_0_0_read(crystals_75_read_int_reg),
    .crystals_tower_0_3_0_1_read(crystals_76_read_int_reg),
    .crystals_tower_0_3_0_2_read(crystals_77_read_int_reg),
    .crystals_tower_0_3_0_3_read(crystals_78_read_int_reg),
    .crystals_tower_0_3_0_4_read(crystals_79_read_int_reg),
    .crystals_tower_0_3_1_0_read(crystals_80_read_int_reg),
    .crystals_tower_0_3_1_1_read(crystals_81_read_int_reg),
    .crystals_tower_0_3_1_2_read(crystals_82_read_int_reg),
    .crystals_tower_0_3_1_3_read(crystals_83_read_int_reg),
    .crystals_tower_0_3_1_4_read(crystals_84_read_int_reg),
    .crystals_tower_0_3_2_0_read(crystals_85_read_int_reg),
    .crystals_tower_0_3_2_1_read(crystals_86_read_int_reg),
    .crystals_tower_0_3_2_2_read(crystals_87_read_int_reg),
    .crystals_tower_0_3_2_3_read(crystals_88_read_int_reg),
    .crystals_tower_0_3_2_4_read(crystals_89_read_int_reg),
    .crystals_tower_0_3_3_0_read(crystals_90_read_int_reg),
    .crystals_tower_0_3_3_1_read(crystals_91_read_int_reg),
    .crystals_tower_0_3_3_2_read(crystals_92_read_int_reg),
    .crystals_tower_0_3_3_3_read(crystals_93_read_int_reg),
    .crystals_tower_0_3_3_4_read(crystals_94_read_int_reg),
    .crystals_tower_0_3_4_0_read(crystals_95_read_int_reg),
    .crystals_tower_0_3_4_1_read(crystals_96_read_int_reg),
    .crystals_tower_0_3_4_2_read(crystals_97_read_int_reg),
    .crystals_tower_0_3_4_3_read(crystals_98_read_int_reg),
    .crystals_tower_0_3_4_4_read(crystals_99_read_int_reg),
    .crystals_tower_1_0_0_0_read(crystals_100_read_int_reg),
    .crystals_tower_1_0_0_1_read(crystals_101_read_int_reg),
    .crystals_tower_1_0_0_2_read(crystals_102_read_int_reg),
    .crystals_tower_1_0_0_3_read(crystals_103_read_int_reg),
    .crystals_tower_1_0_0_4_read(crystals_104_read_int_reg),
    .crystals_tower_1_0_1_0_read(crystals_105_read_int_reg),
    .crystals_tower_1_0_1_1_read(crystals_106_read_int_reg),
    .crystals_tower_1_0_1_2_read(crystals_107_read_int_reg),
    .crystals_tower_1_0_1_3_read(crystals_108_read_int_reg),
    .crystals_tower_1_0_1_4_read(crystals_109_read_int_reg),
    .crystals_tower_1_0_2_0_read(crystals_110_read_int_reg),
    .crystals_tower_1_0_2_1_read(crystals_111_read_int_reg),
    .crystals_tower_1_0_2_2_read(crystals_112_read_int_reg),
    .crystals_tower_1_0_2_3_read(crystals_113_read_int_reg),
    .crystals_tower_1_0_2_4_read(crystals_114_read_int_reg),
    .crystals_tower_1_0_3_0_read(crystals_115_read_int_reg),
    .crystals_tower_1_0_3_1_read(crystals_116_read_int_reg),
    .crystals_tower_1_0_3_2_read(crystals_117_read_int_reg),
    .crystals_tower_1_0_3_3_read(crystals_118_read_int_reg),
    .crystals_tower_1_0_3_4_read(crystals_119_read_int_reg),
    .crystals_tower_1_0_4_0_read(crystals_120_read_int_reg),
    .crystals_tower_1_0_4_1_read(crystals_121_read_int_reg),
    .crystals_tower_1_0_4_2_read(crystals_122_read_int_reg),
    .crystals_tower_1_0_4_3_read(crystals_123_read_int_reg),
    .crystals_tower_1_0_4_4_read(crystals_124_read_int_reg),
    .crystals_tower_1_1_0_0_read(crystals_125_read_int_reg),
    .crystals_tower_1_1_0_1_read(crystals_126_read_int_reg),
    .crystals_tower_1_1_0_2_read(crystals_127_read_int_reg),
    .crystals_tower_1_1_0_3_read(crystals_128_read_int_reg),
    .crystals_tower_1_1_0_4_read(crystals_129_read_int_reg),
    .crystals_tower_1_1_1_0_read(crystals_130_read_int_reg),
    .crystals_tower_1_1_1_1_read(crystals_131_read_int_reg),
    .crystals_tower_1_1_1_2_read(crystals_132_read_int_reg),
    .crystals_tower_1_1_1_3_read(crystals_133_read_int_reg),
    .crystals_tower_1_1_1_4_read(crystals_134_read_int_reg),
    .crystals_tower_1_1_2_0_read(crystals_135_read_int_reg),
    .crystals_tower_1_1_2_1_read(crystals_136_read_int_reg),
    .crystals_tower_1_1_2_2_read(crystals_137_read_int_reg),
    .crystals_tower_1_1_2_3_read(crystals_138_read_int_reg),
    .crystals_tower_1_1_2_4_read(crystals_139_read_int_reg),
    .crystals_tower_1_1_3_0_read(crystals_140_read_int_reg),
    .crystals_tower_1_1_3_1_read(crystals_141_read_int_reg),
    .crystals_tower_1_1_3_2_read(crystals_142_read_int_reg),
    .crystals_tower_1_1_3_3_read(crystals_143_read_int_reg),
    .crystals_tower_1_1_3_4_read(crystals_144_read_int_reg),
    .crystals_tower_1_1_4_0_read(crystals_145_read_int_reg),
    .crystals_tower_1_1_4_1_read(crystals_146_read_int_reg),
    .crystals_tower_1_1_4_2_read(crystals_147_read_int_reg),
    .crystals_tower_1_1_4_3_read(crystals_148_read_int_reg),
    .crystals_tower_1_1_4_4_read(crystals_149_read_int_reg),
    .crystals_tower_1_2_0_0_read(crystals_150_read_int_reg),
    .crystals_tower_1_2_0_1_read(crystals_151_read_int_reg),
    .crystals_tower_1_2_0_2_read(crystals_152_read_int_reg),
    .crystals_tower_1_2_0_3_read(crystals_153_read_int_reg),
    .crystals_tower_1_2_0_4_read(crystals_154_read_int_reg),
    .crystals_tower_1_2_1_0_read(crystals_155_read_int_reg),
    .crystals_tower_1_2_1_1_read(crystals_156_read_int_reg),
    .crystals_tower_1_2_1_2_read(crystals_157_read_int_reg),
    .crystals_tower_1_2_1_3_read(crystals_158_read_int_reg),
    .crystals_tower_1_2_1_4_read(crystals_159_read_int_reg),
    .crystals_tower_1_2_2_0_read(crystals_160_read_int_reg),
    .crystals_tower_1_2_2_1_read(crystals_161_read_int_reg),
    .crystals_tower_1_2_2_2_read(crystals_162_read_int_reg),
    .crystals_tower_1_2_2_3_read(crystals_163_read_int_reg),
    .crystals_tower_1_2_2_4_read(crystals_164_read_int_reg),
    .crystals_tower_1_2_3_0_read(crystals_165_read_int_reg),
    .crystals_tower_1_2_3_1_read(crystals_166_read_int_reg),
    .crystals_tower_1_2_3_2_read(crystals_167_read_int_reg),
    .crystals_tower_1_2_3_3_read(crystals_168_read_int_reg),
    .crystals_tower_1_2_3_4_read(crystals_169_read_int_reg),
    .crystals_tower_1_2_4_0_read(crystals_170_read_int_reg),
    .crystals_tower_1_2_4_1_read(crystals_171_read_int_reg),
    .crystals_tower_1_2_4_2_read(crystals_172_read_int_reg),
    .crystals_tower_1_2_4_3_read(crystals_173_read_int_reg),
    .crystals_tower_1_2_4_4_read(crystals_174_read_int_reg),
    .crystals_tower_1_3_0_0_read(crystals_175_read_int_reg),
    .crystals_tower_1_3_0_1_read(crystals_176_read_int_reg),
    .crystals_tower_1_3_0_2_read(crystals_177_read_int_reg),
    .crystals_tower_1_3_0_3_read(crystals_178_read_int_reg),
    .crystals_tower_1_3_0_4_read(crystals_179_read_int_reg),
    .crystals_tower_1_3_1_0_read(crystals_180_read_int_reg),
    .crystals_tower_1_3_1_1_read(crystals_181_read_int_reg),
    .crystals_tower_1_3_1_2_read(crystals_182_read_int_reg),
    .crystals_tower_1_3_1_3_read(crystals_183_read_int_reg),
    .crystals_tower_1_3_1_4_read(crystals_184_read_int_reg),
    .crystals_tower_1_3_2_0_read(crystals_185_read_int_reg),
    .crystals_tower_1_3_2_1_read(crystals_186_read_int_reg),
    .crystals_tower_1_3_2_2_read(crystals_187_read_int_reg),
    .crystals_tower_1_3_2_3_read(crystals_188_read_int_reg),
    .crystals_tower_1_3_2_4_read(crystals_189_read_int_reg),
    .crystals_tower_1_3_3_0_read(crystals_190_read_int_reg),
    .crystals_tower_1_3_3_1_read(crystals_191_read_int_reg),
    .crystals_tower_1_3_3_2_read(crystals_192_read_int_reg),
    .crystals_tower_1_3_3_3_read(crystals_193_read_int_reg),
    .crystals_tower_1_3_3_4_read(crystals_194_read_int_reg),
    .crystals_tower_1_3_4_0_read(crystals_195_read_int_reg),
    .crystals_tower_1_3_4_1_read(crystals_196_read_int_reg),
    .crystals_tower_1_3_4_2_read(crystals_197_read_int_reg),
    .crystals_tower_1_3_4_3_read(crystals_198_read_int_reg),
    .crystals_tower_1_3_4_4_read(crystals_199_read_int_reg),
    .crystals_tower_2_0_0_0_read(crystals_200_read_int_reg),
    .crystals_tower_2_0_0_1_read(crystals_201_read_int_reg),
    .crystals_tower_2_0_0_2_read(crystals_202_read_int_reg),
    .crystals_tower_2_0_0_3_read(crystals_203_read_int_reg),
    .crystals_tower_2_0_0_4_read(crystals_204_read_int_reg),
    .crystals_tower_2_0_1_0_read(crystals_205_read_int_reg),
    .crystals_tower_2_0_1_1_read(crystals_206_read_int_reg),
    .crystals_tower_2_0_1_2_read(crystals_207_read_int_reg),
    .crystals_tower_2_0_1_3_read(crystals_208_read_int_reg),
    .crystals_tower_2_0_1_4_read(crystals_209_read_int_reg),
    .crystals_tower_2_0_2_0_read(crystals_210_read_int_reg),
    .crystals_tower_2_0_2_1_read(crystals_211_read_int_reg),
    .crystals_tower_2_0_2_2_read(crystals_212_read_int_reg),
    .crystals_tower_2_0_2_3_read(crystals_213_read_int_reg),
    .crystals_tower_2_0_2_4_read(crystals_214_read_int_reg),
    .crystals_tower_2_0_3_0_read(crystals_215_read_int_reg),
    .crystals_tower_2_0_3_1_read(crystals_216_read_int_reg),
    .crystals_tower_2_0_3_2_read(crystals_217_read_int_reg),
    .crystals_tower_2_0_3_3_read(crystals_218_read_int_reg),
    .crystals_tower_2_0_3_4_read(crystals_219_read_int_reg),
    .crystals_tower_2_0_4_0_read(crystals_220_read_int_reg),
    .crystals_tower_2_0_4_1_read(crystals_221_read_int_reg),
    .crystals_tower_2_0_4_2_read(crystals_222_read_int_reg),
    .crystals_tower_2_0_4_3_read(crystals_223_read_int_reg),
    .crystals_tower_2_0_4_4_read(crystals_224_read_int_reg),
    .crystals_tower_2_1_0_0_read(crystals_225_read_int_reg),
    .crystals_tower_2_1_0_1_read(crystals_226_read_int_reg),
    .crystals_tower_2_1_0_2_read(crystals_227_read_int_reg),
    .crystals_tower_2_1_0_3_read(crystals_228_read_int_reg),
    .crystals_tower_2_1_0_4_read(crystals_229_read_int_reg),
    .crystals_tower_2_1_1_0_read(crystals_230_read_int_reg),
    .crystals_tower_2_1_1_1_read(crystals_231_read_int_reg),
    .crystals_tower_2_1_1_2_read(crystals_232_read_int_reg),
    .crystals_tower_2_1_1_3_read(crystals_233_read_int_reg),
    .crystals_tower_2_1_1_4_read(crystals_234_read_int_reg),
    .crystals_tower_2_1_2_0_read(crystals_235_read_int_reg),
    .crystals_tower_2_1_2_1_read(crystals_236_read_int_reg),
    .crystals_tower_2_1_2_2_read(crystals_237_read_int_reg),
    .crystals_tower_2_1_2_3_read(crystals_238_read_int_reg),
    .crystals_tower_2_1_2_4_read(crystals_239_read_int_reg),
    .crystals_tower_2_1_3_0_read(crystals_240_read_int_reg),
    .crystals_tower_2_1_3_1_read(crystals_241_read_int_reg),
    .crystals_tower_2_1_3_2_read(crystals_242_read_int_reg),
    .crystals_tower_2_1_3_3_read(crystals_243_read_int_reg),
    .crystals_tower_2_1_3_4_read(crystals_244_read_int_reg),
    .crystals_tower_2_1_4_0_read(crystals_245_read_int_reg),
    .crystals_tower_2_1_4_1_read(crystals_246_read_int_reg),
    .crystals_tower_2_1_4_2_read(crystals_247_read_int_reg),
    .crystals_tower_2_1_4_3_read(crystals_248_read_int_reg),
    .crystals_tower_2_1_4_4_read(crystals_249_read_int_reg),
    .crystals_tower_2_2_0_0_read(crystals_250_read_int_reg),
    .crystals_tower_2_2_0_1_read(crystals_251_read_int_reg),
    .crystals_tower_2_2_0_2_read(crystals_252_read_int_reg),
    .crystals_tower_2_2_0_3_read(crystals_253_read_int_reg),
    .crystals_tower_2_2_0_4_read(crystals_254_read_int_reg),
    .crystals_tower_2_2_1_0_read(crystals_255_read_int_reg),
    .crystals_tower_2_2_1_1_read(crystals_256_read_int_reg),
    .crystals_tower_2_2_1_2_read(crystals_257_read_int_reg),
    .crystals_tower_2_2_1_3_read(crystals_258_read_int_reg),
    .crystals_tower_2_2_1_4_read(crystals_259_read_int_reg),
    .crystals_tower_2_2_2_0_read(crystals_260_read_int_reg),
    .crystals_tower_2_2_2_1_read(crystals_261_read_int_reg),
    .crystals_tower_2_2_2_2_read(crystals_262_read_int_reg),
    .crystals_tower_2_2_2_3_read(crystals_263_read_int_reg),
    .crystals_tower_2_2_2_4_read(crystals_264_read_int_reg),
    .crystals_tower_2_2_3_0_read(crystals_265_read_int_reg),
    .crystals_tower_2_2_3_1_read(crystals_266_read_int_reg),
    .crystals_tower_2_2_3_2_read(crystals_267_read_int_reg),
    .crystals_tower_2_2_3_3_read(crystals_268_read_int_reg),
    .crystals_tower_2_2_3_4_read(crystals_269_read_int_reg),
    .crystals_tower_2_2_4_0_read(crystals_270_read_int_reg),
    .crystals_tower_2_2_4_1_read(crystals_271_read_int_reg),
    .crystals_tower_2_2_4_2_read(crystals_272_read_int_reg),
    .crystals_tower_2_2_4_3_read(crystals_273_read_int_reg),
    .crystals_tower_2_2_4_4_read(crystals_274_read_int_reg),
    .crystals_tower_2_3_0_0_read(crystals_275_read_int_reg),
    .crystals_tower_2_3_0_1_read(crystals_276_read_int_reg),
    .crystals_tower_2_3_0_2_read(crystals_277_read_int_reg),
    .crystals_tower_2_3_0_3_read(crystals_278_read_int_reg),
    .crystals_tower_2_3_0_4_read(crystals_279_read_int_reg),
    .crystals_tower_2_3_1_0_read(crystals_280_read_int_reg),
    .crystals_tower_2_3_1_1_read(crystals_281_read_int_reg),
    .crystals_tower_2_3_1_2_read(crystals_282_read_int_reg),
    .crystals_tower_2_3_1_3_read(crystals_283_read_int_reg),
    .crystals_tower_2_3_1_4_read(crystals_284_read_int_reg),
    .crystals_tower_2_3_2_0_read(crystals_285_read_int_reg),
    .crystals_tower_2_3_2_1_read(crystals_286_read_int_reg),
    .crystals_tower_2_3_2_2_read(crystals_287_read_int_reg),
    .crystals_tower_2_3_2_3_read(crystals_288_read_int_reg),
    .crystals_tower_2_3_2_4_read(crystals_289_read_int_reg),
    .crystals_tower_2_3_3_0_read(crystals_290_read_int_reg),
    .crystals_tower_2_3_3_1_read(crystals_291_read_int_reg),
    .crystals_tower_2_3_3_2_read(crystals_292_read_int_reg),
    .crystals_tower_2_3_3_3_read(crystals_293_read_int_reg),
    .crystals_tower_2_3_3_4_read(crystals_294_read_int_reg),
    .crystals_tower_2_3_4_0_read(crystals_295_read_int_reg),
    .crystals_tower_2_3_4_1_read(crystals_296_read_int_reg),
    .crystals_tower_2_3_4_2_read(crystals_297_read_int_reg),
    .crystals_tower_2_3_4_3_read(crystals_298_read_int_reg),
    .crystals_tower_2_3_4_4_read(crystals_299_read_int_reg),
    .ap_ce(grp_getClustersin3x4Regi_fu_2412_ap_ce)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        crystals_0_read_int_reg <= crystals_0_read;
        crystals_100_read_int_reg <= crystals_100_read;
        crystals_101_read_int_reg <= crystals_101_read;
        crystals_102_read_int_reg <= crystals_102_read;
        crystals_103_read_int_reg <= crystals_103_read;
        crystals_104_read_int_reg <= crystals_104_read;
        crystals_105_read_int_reg <= crystals_105_read;
        crystals_106_read_int_reg <= crystals_106_read;
        crystals_107_read_int_reg <= crystals_107_read;
        crystals_108_read_int_reg <= crystals_108_read;
        crystals_109_read_int_reg <= crystals_109_read;
        crystals_10_read_int_reg <= crystals_10_read;
        crystals_110_read_int_reg <= crystals_110_read;
        crystals_111_read_int_reg <= crystals_111_read;
        crystals_112_read_int_reg <= crystals_112_read;
        crystals_113_read_int_reg <= crystals_113_read;
        crystals_114_read_int_reg <= crystals_114_read;
        crystals_115_read_int_reg <= crystals_115_read;
        crystals_116_read_int_reg <= crystals_116_read;
        crystals_117_read_int_reg <= crystals_117_read;
        crystals_118_read_int_reg <= crystals_118_read;
        crystals_119_read_int_reg <= crystals_119_read;
        crystals_11_read_int_reg <= crystals_11_read;
        crystals_120_read_int_reg <= crystals_120_read;
        crystals_121_read_int_reg <= crystals_121_read;
        crystals_122_read_int_reg <= crystals_122_read;
        crystals_123_read_int_reg <= crystals_123_read;
        crystals_124_read_int_reg <= crystals_124_read;
        crystals_125_read_int_reg <= crystals_125_read;
        crystals_126_read_int_reg <= crystals_126_read;
        crystals_127_read_int_reg <= crystals_127_read;
        crystals_128_read_int_reg <= crystals_128_read;
        crystals_129_read_int_reg <= crystals_129_read;
        crystals_12_read_int_reg <= crystals_12_read;
        crystals_130_read_int_reg <= crystals_130_read;
        crystals_131_read_int_reg <= crystals_131_read;
        crystals_132_read_int_reg <= crystals_132_read;
        crystals_133_read_int_reg <= crystals_133_read;
        crystals_134_read_int_reg <= crystals_134_read;
        crystals_135_read_int_reg <= crystals_135_read;
        crystals_136_read_int_reg <= crystals_136_read;
        crystals_137_read_int_reg <= crystals_137_read;
        crystals_138_read_int_reg <= crystals_138_read;
        crystals_139_read_int_reg <= crystals_139_read;
        crystals_13_read_int_reg <= crystals_13_read;
        crystals_140_read_int_reg <= crystals_140_read;
        crystals_141_read_int_reg <= crystals_141_read;
        crystals_142_read_int_reg <= crystals_142_read;
        crystals_143_read_int_reg <= crystals_143_read;
        crystals_144_read_int_reg <= crystals_144_read;
        crystals_145_read_int_reg <= crystals_145_read;
        crystals_146_read_int_reg <= crystals_146_read;
        crystals_147_read_int_reg <= crystals_147_read;
        crystals_148_read_int_reg <= crystals_148_read;
        crystals_149_read_int_reg <= crystals_149_read;
        crystals_14_read_int_reg <= crystals_14_read;
        crystals_150_read_int_reg <= crystals_150_read;
        crystals_151_read_int_reg <= crystals_151_read;
        crystals_152_read_int_reg <= crystals_152_read;
        crystals_153_read_int_reg <= crystals_153_read;
        crystals_154_read_int_reg <= crystals_154_read;
        crystals_155_read_int_reg <= crystals_155_read;
        crystals_156_read_int_reg <= crystals_156_read;
        crystals_157_read_int_reg <= crystals_157_read;
        crystals_158_read_int_reg <= crystals_158_read;
        crystals_159_read_int_reg <= crystals_159_read;
        crystals_15_read_int_reg <= crystals_15_read;
        crystals_160_read_int_reg <= crystals_160_read;
        crystals_161_read_int_reg <= crystals_161_read;
        crystals_162_read_int_reg <= crystals_162_read;
        crystals_163_read_int_reg <= crystals_163_read;
        crystals_164_read_int_reg <= crystals_164_read;
        crystals_165_read_int_reg <= crystals_165_read;
        crystals_166_read_int_reg <= crystals_166_read;
        crystals_167_read_int_reg <= crystals_167_read;
        crystals_168_read_int_reg <= crystals_168_read;
        crystals_169_read_int_reg <= crystals_169_read;
        crystals_16_read_int_reg <= crystals_16_read;
        crystals_170_read_int_reg <= crystals_170_read;
        crystals_171_read_int_reg <= crystals_171_read;
        crystals_172_read_int_reg <= crystals_172_read;
        crystals_173_read_int_reg <= crystals_173_read;
        crystals_174_read_int_reg <= crystals_174_read;
        crystals_175_read_int_reg <= crystals_175_read;
        crystals_176_read_int_reg <= crystals_176_read;
        crystals_177_read_int_reg <= crystals_177_read;
        crystals_178_read_int_reg <= crystals_178_read;
        crystals_179_read_int_reg <= crystals_179_read;
        crystals_17_read_int_reg <= crystals_17_read;
        crystals_180_read_int_reg <= crystals_180_read;
        crystals_181_read_int_reg <= crystals_181_read;
        crystals_182_read_int_reg <= crystals_182_read;
        crystals_183_read_int_reg <= crystals_183_read;
        crystals_184_read_int_reg <= crystals_184_read;
        crystals_185_read_int_reg <= crystals_185_read;
        crystals_186_read_int_reg <= crystals_186_read;
        crystals_187_read_int_reg <= crystals_187_read;
        crystals_188_read_int_reg <= crystals_188_read;
        crystals_189_read_int_reg <= crystals_189_read;
        crystals_18_read_int_reg <= crystals_18_read;
        crystals_190_read_int_reg <= crystals_190_read;
        crystals_191_read_int_reg <= crystals_191_read;
        crystals_192_read_int_reg <= crystals_192_read;
        crystals_193_read_int_reg <= crystals_193_read;
        crystals_194_read_int_reg <= crystals_194_read;
        crystals_195_read_int_reg <= crystals_195_read;
        crystals_196_read_int_reg <= crystals_196_read;
        crystals_197_read_int_reg <= crystals_197_read;
        crystals_198_read_int_reg <= crystals_198_read;
        crystals_199_read_int_reg <= crystals_199_read;
        crystals_19_read_int_reg <= crystals_19_read;
        crystals_1_read_int_reg <= crystals_1_read;
        crystals_200_read_int_reg <= crystals_200_read;
        crystals_201_read_int_reg <= crystals_201_read;
        crystals_202_read_int_reg <= crystals_202_read;
        crystals_203_read_int_reg <= crystals_203_read;
        crystals_204_read_int_reg <= crystals_204_read;
        crystals_205_read_int_reg <= crystals_205_read;
        crystals_206_read_int_reg <= crystals_206_read;
        crystals_207_read_int_reg <= crystals_207_read;
        crystals_208_read_int_reg <= crystals_208_read;
        crystals_209_read_int_reg <= crystals_209_read;
        crystals_20_read_int_reg <= crystals_20_read;
        crystals_210_read_int_reg <= crystals_210_read;
        crystals_211_read_int_reg <= crystals_211_read;
        crystals_212_read_int_reg <= crystals_212_read;
        crystals_213_read_int_reg <= crystals_213_read;
        crystals_214_read_int_reg <= crystals_214_read;
        crystals_215_read_int_reg <= crystals_215_read;
        crystals_216_read_int_reg <= crystals_216_read;
        crystals_217_read_int_reg <= crystals_217_read;
        crystals_218_read_int_reg <= crystals_218_read;
        crystals_219_read_int_reg <= crystals_219_read;
        crystals_21_read_int_reg <= crystals_21_read;
        crystals_220_read_int_reg <= crystals_220_read;
        crystals_221_read_int_reg <= crystals_221_read;
        crystals_222_read_int_reg <= crystals_222_read;
        crystals_223_read_int_reg <= crystals_223_read;
        crystals_224_read_int_reg <= crystals_224_read;
        crystals_225_read_int_reg <= crystals_225_read;
        crystals_226_read_int_reg <= crystals_226_read;
        crystals_227_read_int_reg <= crystals_227_read;
        crystals_228_read_int_reg <= crystals_228_read;
        crystals_229_read_int_reg <= crystals_229_read;
        crystals_22_read_int_reg <= crystals_22_read;
        crystals_230_read_int_reg <= crystals_230_read;
        crystals_231_read_int_reg <= crystals_231_read;
        crystals_232_read_int_reg <= crystals_232_read;
        crystals_233_read_int_reg <= crystals_233_read;
        crystals_234_read_int_reg <= crystals_234_read;
        crystals_235_read_int_reg <= crystals_235_read;
        crystals_236_read_int_reg <= crystals_236_read;
        crystals_237_read_int_reg <= crystals_237_read;
        crystals_238_read_int_reg <= crystals_238_read;
        crystals_239_read_int_reg <= crystals_239_read;
        crystals_23_read_int_reg <= crystals_23_read;
        crystals_240_read_int_reg <= crystals_240_read;
        crystals_241_read_int_reg <= crystals_241_read;
        crystals_242_read_int_reg <= crystals_242_read;
        crystals_243_read_int_reg <= crystals_243_read;
        crystals_244_read_int_reg <= crystals_244_read;
        crystals_245_read_int_reg <= crystals_245_read;
        crystals_246_read_int_reg <= crystals_246_read;
        crystals_247_read_int_reg <= crystals_247_read;
        crystals_248_read_int_reg <= crystals_248_read;
        crystals_249_read_int_reg <= crystals_249_read;
        crystals_24_read_int_reg <= crystals_24_read;
        crystals_250_read_int_reg <= crystals_250_read;
        crystals_251_read_int_reg <= crystals_251_read;
        crystals_252_read_int_reg <= crystals_252_read;
        crystals_253_read_int_reg <= crystals_253_read;
        crystals_254_read_int_reg <= crystals_254_read;
        crystals_255_read_int_reg <= crystals_255_read;
        crystals_256_read_int_reg <= crystals_256_read;
        crystals_257_read_int_reg <= crystals_257_read;
        crystals_258_read_int_reg <= crystals_258_read;
        crystals_259_read_int_reg <= crystals_259_read;
        crystals_25_read_int_reg <= crystals_25_read;
        crystals_260_read_int_reg <= crystals_260_read;
        crystals_261_read_int_reg <= crystals_261_read;
        crystals_262_read_int_reg <= crystals_262_read;
        crystals_263_read_int_reg <= crystals_263_read;
        crystals_264_read_int_reg <= crystals_264_read;
        crystals_265_read_int_reg <= crystals_265_read;
        crystals_266_read_int_reg <= crystals_266_read;
        crystals_267_read_int_reg <= crystals_267_read;
        crystals_268_read_int_reg <= crystals_268_read;
        crystals_269_read_int_reg <= crystals_269_read;
        crystals_26_read_int_reg <= crystals_26_read;
        crystals_270_read_int_reg <= crystals_270_read;
        crystals_271_read_int_reg <= crystals_271_read;
        crystals_272_read_int_reg <= crystals_272_read;
        crystals_273_read_int_reg <= crystals_273_read;
        crystals_274_read_int_reg <= crystals_274_read;
        crystals_275_read_int_reg <= crystals_275_read;
        crystals_276_read_int_reg <= crystals_276_read;
        crystals_277_read_int_reg <= crystals_277_read;
        crystals_278_read_int_reg <= crystals_278_read;
        crystals_279_read_int_reg <= crystals_279_read;
        crystals_27_read_int_reg <= crystals_27_read;
        crystals_280_read_int_reg <= crystals_280_read;
        crystals_281_read_int_reg <= crystals_281_read;
        crystals_282_read_int_reg <= crystals_282_read;
        crystals_283_read_int_reg <= crystals_283_read;
        crystals_284_read_int_reg <= crystals_284_read;
        crystals_285_read_int_reg <= crystals_285_read;
        crystals_286_read_int_reg <= crystals_286_read;
        crystals_287_read_int_reg <= crystals_287_read;
        crystals_288_read_int_reg <= crystals_288_read;
        crystals_289_read_int_reg <= crystals_289_read;
        crystals_28_read_int_reg <= crystals_28_read;
        crystals_290_read_int_reg <= crystals_290_read;
        crystals_291_read_int_reg <= crystals_291_read;
        crystals_292_read_int_reg <= crystals_292_read;
        crystals_293_read_int_reg <= crystals_293_read;
        crystals_294_read_int_reg <= crystals_294_read;
        crystals_295_read_int_reg <= crystals_295_read;
        crystals_296_read_int_reg <= crystals_296_read;
        crystals_297_read_int_reg <= crystals_297_read;
        crystals_298_read_int_reg <= crystals_298_read;
        crystals_299_read_int_reg <= crystals_299_read;
        crystals_29_read_int_reg <= crystals_29_read;
        crystals_2_read_int_reg <= crystals_2_read;
        crystals_30_read_int_reg <= crystals_30_read;
        crystals_31_read_int_reg <= crystals_31_read;
        crystals_32_read_int_reg <= crystals_32_read;
        crystals_33_read_int_reg <= crystals_33_read;
        crystals_34_read_int_reg <= crystals_34_read;
        crystals_35_read_int_reg <= crystals_35_read;
        crystals_36_read_int_reg <= crystals_36_read;
        crystals_37_read_int_reg <= crystals_37_read;
        crystals_38_read_int_reg <= crystals_38_read;
        crystals_39_read_int_reg <= crystals_39_read;
        crystals_3_read_int_reg <= crystals_3_read;
        crystals_40_read_int_reg <= crystals_40_read;
        crystals_41_read_int_reg <= crystals_41_read;
        crystals_42_read_int_reg <= crystals_42_read;
        crystals_43_read_int_reg <= crystals_43_read;
        crystals_44_read_int_reg <= crystals_44_read;
        crystals_45_read_int_reg <= crystals_45_read;
        crystals_46_read_int_reg <= crystals_46_read;
        crystals_47_read_int_reg <= crystals_47_read;
        crystals_48_read_int_reg <= crystals_48_read;
        crystals_49_read_int_reg <= crystals_49_read;
        crystals_4_read_int_reg <= crystals_4_read;
        crystals_50_read_int_reg <= crystals_50_read;
        crystals_51_read_int_reg <= crystals_51_read;
        crystals_52_read_int_reg <= crystals_52_read;
        crystals_53_read_int_reg <= crystals_53_read;
        crystals_54_read_int_reg <= crystals_54_read;
        crystals_55_read_int_reg <= crystals_55_read;
        crystals_56_read_int_reg <= crystals_56_read;
        crystals_57_read_int_reg <= crystals_57_read;
        crystals_58_read_int_reg <= crystals_58_read;
        crystals_59_read_int_reg <= crystals_59_read;
        crystals_5_read_int_reg <= crystals_5_read;
        crystals_60_read_int_reg <= crystals_60_read;
        crystals_61_read_int_reg <= crystals_61_read;
        crystals_62_read_int_reg <= crystals_62_read;
        crystals_63_read_int_reg <= crystals_63_read;
        crystals_64_read_int_reg <= crystals_64_read;
        crystals_65_read_int_reg <= crystals_65_read;
        crystals_66_read_int_reg <= crystals_66_read;
        crystals_67_read_int_reg <= crystals_67_read;
        crystals_68_read_int_reg <= crystals_68_read;
        crystals_69_read_int_reg <= crystals_69_read;
        crystals_6_read_int_reg <= crystals_6_read;
        crystals_70_read_int_reg <= crystals_70_read;
        crystals_71_read_int_reg <= crystals_71_read;
        crystals_72_read_int_reg <= crystals_72_read;
        crystals_73_read_int_reg <= crystals_73_read;
        crystals_74_read_int_reg <= crystals_74_read;
        crystals_75_read_int_reg <= crystals_75_read;
        crystals_76_read_int_reg <= crystals_76_read;
        crystals_77_read_int_reg <= crystals_77_read;
        crystals_78_read_int_reg <= crystals_78_read;
        crystals_79_read_int_reg <= crystals_79_read;
        crystals_7_read_int_reg <= crystals_7_read;
        crystals_80_read_int_reg <= crystals_80_read;
        crystals_81_read_int_reg <= crystals_81_read;
        crystals_82_read_int_reg <= crystals_82_read;
        crystals_83_read_int_reg <= crystals_83_read;
        crystals_84_read_int_reg <= crystals_84_read;
        crystals_85_read_int_reg <= crystals_85_read;
        crystals_86_read_int_reg <= crystals_86_read;
        crystals_87_read_int_reg <= crystals_87_read;
        crystals_88_read_int_reg <= crystals_88_read;
        crystals_89_read_int_reg <= crystals_89_read;
        crystals_8_read_int_reg <= crystals_8_read;
        crystals_90_read_int_reg <= crystals_90_read;
        crystals_91_read_int_reg <= crystals_91_read;
        crystals_92_read_int_reg <= crystals_92_read;
        crystals_93_read_int_reg <= crystals_93_read;
        crystals_94_read_int_reg <= crystals_94_read;
        crystals_95_read_int_reg <= crystals_95_read;
        crystals_96_read_int_reg <= crystals_96_read;
        crystals_97_read_int_reg <= crystals_97_read;
        crystals_98_read_int_reg <= crystals_98_read;
        crystals_99_read_int_reg <= crystals_99_read;
        crystals_9_read_int_reg <= crystals_9_read;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_getClustersin3x4Regi_fu_2412_ap_ce = 1'b1;
    end else begin
        grp_getClustersin3x4Regi_fu_2412_ap_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

endmodule //getClustersInCard
